### ISSUE TITLE
[question] Does Aedes work with nginx proxy_protocol on?

### ISSUE THREAD

**Issue by nolimitdev** [moscajs/aedes#1016]
Connection to Aedes directly on port e.g. 1234 works, also works via nginx when `proxy_protocol on` is removed from config bellow. When `proxy_protocol on` is set MQTT Explorer client say "Disconnected from server" NPM mqtt client does nothing - no connect event no error event. Tested with older and also latest nginx. As MQTT client tested lates MQTT Explorer and latest NPM `mqtt`. I saw in issues that proxy protocol was actively solved in many years ago, so I have expected it is working nowadays. Thank you for any hint what could be wrong.

```
stream {
  server {
      listen 1883;
      proxy_protocol on;
      proxy_pass 127.0.0.1:1234;
  }
}
```

My goal is to get client IP address when he is connected via nginx proxy.

**Comment by robertsLando** [comment]
Sorry dunno how to help here, @getlarge any clue?

**Comment by getlarge** [comment]
@nolimitdev It works; however, you must help Aedes decode the Proxy protocol; check out this [lib](https://github.com/moscajs/aedes-protocol-decoder) I wrote a few years ago.

**Comment by nolimitdev** [comment]
@getlarge thank you for hint, I will try it soon and let you know

**Comment by nolimitdev** [comment]
Great! It is working! You are the king!
