### ISSUE TITLE
[question] Invalid header flag bits, must be 0x0 for puback packet

### ISSUE THREAD

**Issue by davidCcD** [moscajs/aedes#1017]
Hello, dear, I am sure my aedes broker works fine that I can connect it via mqtt protocol in app, but I met an error when I try to connect to my aedes broker via Chrome browser with ws protocol. Aedes in nodeJs emitted this error: 

_connectionError Error: Invalid header flag bits, must be 0x0 for puback packet_

I don't know how to fix it. I think it's not frontend bug (it's a Vue webpage) because I changed the host from my broker to other broker (a free public broker for test) as below, it connected successfully and works. So it should be a bug in my aedes bug?

// host:"192.168.1.6", // <-- this is my aedes.js broker
host:"broker.emqx.io", // <-- this is a free public broker for test

My broker can be connected succuessfully via App such MQTTX with mqtt://192.168.1.6:8083/mqtt, but failed via web browser with ws://192.168.1.6:8083/mqtt with error "Invalid header flag bits, must be 0x0 for puback packet" , this is the problem I have now.

**Broker**
aedesjs 0.51.3

**Environment**
node.js 20.9.0

**Client**
mqtt.js 5.10.1

**Minimal Reproduction**

_NodeJs side, code:_
aedes.on('connectionError', function (client, error) {
console.log('\x1b[31m' + (client ? client.id : client) + '\x1b[0m' + ' connectionError' + error.toString());
});

_VueJs side, code:_
const connection = {
protocol: "ws",
protocolId: 'MQTT',
protocolVersion:4,
host:"192.168.1.6", // <-- this is my aedes.js broker, it works fail
// host:"broker.emqx.io", // <-- this is a free public broker for test, it works fine
port: 8083,
clientId: "vue3_123456",
username: "username",
password: "password",
clean: true,
connectTimeout: 3000,
reconnectPeriod: 4000
};

**Debug logs**

_NodeJs side, emitted this log:_
null connectionError Error: Invalid header flag bits, must be 0x0 for puback packet

_Chrome side, log:_
WebSocket connection to 'ws://192.168.1.6:8083/mqtt' failed:
aS @ mqtt.js?v=1422640a:11542
uS @ mqtt.js?v=1422640a:11556
s @ mqtt.js?v=1422640a:11832
connect @ mqtt.js?v=1422640a:9852
_reconnect @ mqtt.js?v=1422640a:10079
(anonymous) @ mqtt.js?v=1422640a:10083

**Comment by robertsLando** [comment]
PR?

**Comment by davidCcD** [comment]
> PR? Aedes is using mqtt-packet parser to parse packets so the issue may be there

Dear, my server code is:

`const Aedes = require('aedes');//aedes 0.51.3
const net = require('net');//node.js 20.9.0

function startAedes() {
    const aedes = Aedes({
        a: 'BROKER_aedes',
        // mq,
        // persistence
    });

    // I seems no matter true or false, results are same
    const options = { ws: false };

    const mqttServer = net.createServer(aedes.handle, options);
   
    mqttServer.listen(8083, '0.0.0.0', function () {
        console.log('MQTT(BROKER_' + aedes.id + ') listening port 8083.');
    });

    mqttServer.on('error', function (err) {
        console.log('MQTT error: ', err);
        process.exit(1);
    });

    aedes.preConnect = function (client, packet, callback) {
        console.log('a client: \x1b[31m' + (client ? client.conn.remoteAddress : client) + '\x1b[0m preConnect');
         callback(null, true)
    }

    aedes.authenticate = function (client, username, password, callback) {
        console.log('client.id is: ' + client.id + ', username is: ' + username.toString() + ', password is: ' + password.toString())
        callback(null, true)       
    }

    aedes.on('client', function (client) {
        console.log('\x1b[33m' + (client ? client.id : client) + '\x1b[0m' + ' client connect to broker ' + aedes.id);
    });

    aedes.on('clientReady', function (client) {
        console.log('\x1b[33m' + (client ? client.id : client) + '\x1b[0m' + ' client ready connect to broker ' + aedes.id);
    });

    aedes.on('clientDisconnect', function (client) {
        console.log('\x1b[31m' + (client ? client.id : client) + '\x1b[0m' + ' client connect end ');
    });

    aedes.on('clientError', function (client, error) {
        console.log('\x1b[31m' + (client ? client.id : client) + '\x1b[0m' + ' client connect error ' + error.toString());
    });

    // Emitted when an error occurs. Unlike clientError, it raises only when client is uninitialized.
    aedes.on('connectionError', function (client, error) {
        console.log('\x1b[31m' + (client ? client.id : client) + '\x1b[0m' + ' connectionError ' + error.toString());
    });

    aedes.on('connackSent', function (packet, client) {
        console.log('connackSent 1 -> ' + (client ? client.id : client) );
        console.log('connackSent 2 -> ' + (packet ? packet.topic : 'packet is null'));
    });

    aedes.on('keepaliveTimeout', function (client, error) {
        console.log('\x1b[31m' + (client ? client.id : client) + '\x1b[0m' + ' keepaliveTimeout ' + error.toString());
    });

    aedes.on('ping', function (packet, client) {
        console.log('\x1b[31m' + (client ? client.id : client) + '\x1b[0m' + ' client send Ping');
    });

    aedes.on('ack', function (packet, client) {
        console.log('ack: \x1b[31m' + (client ? client.id : client) + '\x1b[0m' + ' content: ' + packet);
    });

    aedes.on('publish', function (packet, client) {
        if (client) {
            console.log('client publish\x1b[31m' + (client ? client.id : client) + '\x1b[0m' + ' publish, topic: ' + packet.topic + ', content: ' + packet.payload.toString());
            mqttTopic.route(packet.topic, packet.payload)
        }
    });

    aedes.on('subscribe', function (subscriptions, client) {
        console.log('client publish: \x1b[31m' + (client ? client.id : client) + '\x1b[0m' + ' subscript: ' + subscriptions[0].topic);
    });

    aedes.authorizeSubscribe = function (client, sub, callback) {
        callback(null, sub)
    }

    aedes.on('unsubscribe', function (unsubscriptions, client) {
        console.log('client publish: \x1b[31m' + (client ? client.id : client) + '\x1b[0m' + 'unsubscript: ' + unsubscriptions);
    });
    
}

startAedes();`

My client code is a vue file, now I changed to a js file for your reference, below:

`const mqtt = require('mqtt');//mqtt 5.10.1

const subscription = {topic: "topic1", qos: 0};

// 1. When host is is "broker.emqx.io", connections are success.
// no matter protocol is mqtt(with port 1883) or ws(with port 8083),
// 2. When host is "192.168.1.6",
// connect success if and protocol is mqtt(with port 8083),
// connect fail if protocol is ws(with port 8083. My Aedes port didn't modify),
// NodeJs(Aedes) log: null connectionError Error: Invalid header flag bits, must be 0x0 for puback packet
const connection = {
    protocol: "mqtt",
    //   protocol: "ws",
    protocolId: 'MQTT',
    protocolVersion: 4,
    host: "broker.emqx.io",
    //   host: "192.168.1.6",
    port: 8083,
    clientId: "vue3_123456",
    username: "username",
    password: "password",
    clean: true,
    connectTimeout: 30000,
    reconnectPeriod: 4000
};

let client = { connected: false };

const createConnection = () => {
    try {
        const { protocol, host, port, ...options } = connection;
        const connectUrl = `${protocol}://${host}:${port}/mqtt`;
        client = mqtt.connect(connectUrl, options);

        if (client.on) {
            client.on("connect", () => {
                console.log("connection successful");
                doSubscribe();
            });

            client.on("error", error => {
                console.log("connection error:", error);
            });

            client.on("message", (topic, message) => {
                receivedMessages.value = receivedMessages.value.concat(
                    message.toString()
                );
                console.log(`received message: ${message} from topic: ${topic}`);
            });
        }
    } catch (error) {
        console.log("mqtt.connect error:", error);
    }
};

const doSubscribe = () => {
    const { topic, qos } = subscription;
    client.subscribe(
        topic,
        { qos },
        (error, granted) => {
            if (error) {
                console.log("subscribe error:", error);
                return;
            }
            console.log("subscribe successfully:", granted);
        }
    );
};

createConnection()`

After start server, you can try client:

1. When host is "broker.emqx.io", connections are success.
no matter protocol is mqtt(with port 1883) or ws(with port 8083),

2. When host is "192.168.1.6" (you may change as your server IP),
connect success if and protocol is mqtt(with port 8083),
connect fail if protocol is ws(with port 8083. My Aedes port didn't modify, always 8083, options = { ws: false } try ws: true get the same result ),
NodeJs(Aedes) log: null connectionError Error: Invalid header flag bits, must be 0x0 for puback packet

**Comment by robertsLando** [comment]
https://github.com/mqttjs/mqtt-packet

**Comment by davidCcD** [comment]
> https://github.com/mqttjs/mqtt-packet

Thank you, Dear. I resolved this problem by using different port and code, the ws protocol should use const ws = require('websocket-stream').
