### ISSUE TITLE
[question] whether event clientDisconnect working right way ?

### ISSUE THREAD

**Issue by yarncode** [moscajs/aedes#1021]
Hi, Currently i have some esp32 device for connection iot using mqtt protocol but when power off device so, on server not received event clientDisconnect, sometime i receive event clientDisconnect after 10 to 15 minute, is there any function like ping pong or heartbeat, this to detect device disconect right away, i hope this func make event work right way

**Comment by Gianluca-Casagrande-Stiga** [comment]
Hi, you should set a shorter keep alive timeout on client side, that regulate the PING frequency that let the broker understand if the device is "online" or not.
For example, if you set 10sec of keepalive, the clientDisconnect will appear after few seconds of the power off.

**Comment by yarncode** [comment]
> Hi, you should set a shorter keep alive timeout on client side, that regulate the PING frequency that let the broker understand if the device is "online" or not. For example, if you set 10sec of keepalive, the clientDisconnect will appear after few seconds of the power off.

thank u so mush, it seems work so good with me
