### ISSUE TITLE
[feat] server side triggered subscriptions for clients

### ISSUE THREAD

**Issue by behrad** [moscajs/aedes#129]
provide functions to add/remove subscriptions for a client like

```js
aedes#addSubscription(clientId, [{topic, qos}], cb)
aedes#removeSubscription(clientId, [topic], cb)
```
the only issue providing these with  the current `aedes.handleSubscribe` is lack of client object in above cases. 
Two models I propose:
1. Can we change handleSubscribe to be safe when client object is not a real connected object? in this model if a clientId is connected, broker can provide the client instance.

2. Can we move these two into `aedes-persistence`, then the meaning of them will be changed to only store subscriptions.

**Comment by mcollina** [comment]
I am +1 with 1, it might be the easier one to implement.

**Comment by behrad** [comment]
Main point about this is how to call subscribe on the actual client instance in a multi instance environment @mcollina. This can be solved either

1. Providing a core inter-node messaging inside aedes using e.g. the internal `mqemitter` inside aedes! this also can be used for other commiunication needs in a clustered env.

2. calling addSubscriptions with a third kind of a value like `serverSub: true`, this way the node with the connected client instance can call `client.subscribe`. this has to be implemented with care, not to collide with current `handleSubscribe` logic.

**Comment by mcollina** [comment]
I think that's a good use for $SYS topics, so +1 for approach 1.

**Comment by elixiao** [comment]
Has this api been done yet ? It's very useful in many cases.

**Comment by gnought** [comment]
don't know if I understand the point.

`addSubscriptions` with `client` argument has already been moved into https://github.com/mcollina/aedes-persistence/blob/master/persistence.js#L74, and `removeSubscriptions` also https://github.com/mcollina/aedes-persistence/blob/master/persistence.js#L106

and `client.subscribe` also pass `client` object to `handleSubscribe` in https://github.com/mcollina/aedes/blob/master/lib/client.js#L195

@elixiao could you elaborate more about your cases?

**Comment by behrad** [comment]
I haven't reviewed latest changes @gnought However this issue was about having an API to subscribe a user to a topic.
Normally subscribe happens from a connected client. Here we want to be able to subscribe on behalf of an offline connect

**Comment by elixiao** [comment]
@gnought  @behrad Is there an api which can subscribe topics for already connected clients? Not from client side by `client.subscribe(topics, cb)` but server side by api like `aedes.addSubscription(clientId, topics, cb)`

**Comment by gnought** [comment]
it sounds like server has a capability to add/remove a subscription for a client, rather than client requests to subscribe/unsubscribe a topic by himself. May we know what the usage is for?

**Comment by elixiao** [comment]
@gnought In my case, I attach aedes to my server. The server side database stores the publish/subscribe relationship which varies over time. The rules are: 

1. when client has attribute A then it should subscribe topic A. 
2. when client's attribute becomes B then it should unsubscribe topic A and subscribe topic B. 

I think it's very convenient to addSubscription/removeSubscription on server side.

**Comment by robertsLando** [comment]
@mcollina Is this a feature that needs to be added?

**Comment by mcollina** [comment]
I think this is already there
Il 23 gen 2020, 13:47 +0100, Daniel Lando <notifications@github.com>, ha scritto:
