### ISSUE TITLE
Cluster mode support

### ISSUE THREAD

**Issue by mcollina** [moscajs/aedes#146]
This could use a combination of https://www.npmjs.com/package/level-party and https://www.npmjs.com/package/mqemitter-child-process with https://github.com/mcollina/aedes-persistence-level.

It probably just needs some docs and an example.

**Comment by cordovapolymer** [comment]
@mcollina , you mentioned aedes-persistence-level, what do you think about cluster support for other persistences?

**Comment by mcollina** [comment]
@cordovapolymer other persistences will automatically work, as they use an external database and broker.

**Comment by bsommardahl** [comment]
@mcollina Do you mean that clustering will automatically work as long as the brokers are all using the same external database?

**Comment by GavinDmello** [comment]
@bsommardahl  Yes.

**Comment by robertsLando** [comment]
@mcollina I have a working example, should I create a separate report or do you prefere a pull request?

**Comment by mcollina** [comment]
A pull request would be amazing, thanks!

Il giorno mar 29 ott 2019 alle 13:35 Daniel Lando <notifications@github.com>
ha scritto:

**Comment by robertsLando** [comment]
@mcollina this can be closed

**Comment by mcollina** [comment]
@robertsLando you should have write permission now, so you should be able to close those yourself.

**Comment by robertsLando** [comment]
@mcollina Nope, cannot close issues or do anything

**Comment by mcollina** [comment]
should be fixed now.
