### ISSUE TITLE
Implementing TTL for packets / topics - ways to go about

### ISSUE THREAD

**Issue by syberkitten** [moscajs/aedes#157]
As I understand there is no TTL for packets and topics
meaning that outgoing packets or subscribed topics will be left
for ever in the persistence layer if they are not delivered or unsubscribed
as such. (same goes for topics)

I wish to create a management layer for the persistency layer (or above it),
according to my defined rules, so that this layer is not 
part of the broker and can run in a different node process.

(most of the Erlang MQTT brokers have something of that mechanism,
in form of special actors designed for management)

my first thought on the matter is to actually add timestamp
to the packets and subscriptions, then go deeper down the rabbit hole.

I've been evaluating a few brokers (including Mosca / EMQ and VerneMQ)
and found that no broker was ever
consistent with one another, in terms of dealing with subscriptions
and retained messages.

Aedes being barebone can fit well in a larger IOT Eco-system
without dragging you down to work around poorly engineered or poorly tested
products (with too many assumptions about the usage),
and lets you design your own flow and behavior.

Would appreciate any relevant guidelines that come to mind,
if any.. )

**Comment by ckrey** [comment]
You may want to have a look at the upcomig [MQTT Version 5 specification](http://docs.oasis-open.org/mqtt/mqtt/v5.0/csprd01/mqtt-v5.0-csprd01.html)

with regards to their definition of 
* Session Expiry Interval
* Publication Expiry Interval

**Comment by behrad** [comment]
@syberkitten You can also check current packet TTL implementation in [redis persistence](https://github.com/mcollina/aedes-persistence-redis)

**Comment by robertsLando** [comment]
Some persistences like redis and mongo already support ttl
