### ISSUE TITLE
Connection mqtt or websocket through apache proxy

### ISSUE THREAD

**Issue by psummo** [moscajs/aedes#182]
I try to open connection from my c# client to my Aedes broker, after set proxy on apache. What's the correct setting? over websocket I recive error about "Not client connection confirm recived", over mqtt crash for timeout.
[My Aedes Broker](https://pastebin.com/ZhRtFCNc)
[My Apache proxy settings](https://pastebin.com/R6LHwkEt)

I have proxy_wstunnel enable. I know that itsn't an Aedes problem, but online there are only solution for mosquitto that use a particular module.
Thanks

**Comment by cordovapolymer** [comment]
@psummo try using [this solution](https://stackoverflow.com/a/35141086)
