### ISSUE TITLE
100% CPU and server crashes after connecting 9k clients with each publish 1 msg/s

### ISSUE THREAD

**Issue by urmik** [moscajs/aedes#192]
Hello,

I have default latest aedes server installed on my Ubnutu machine.
From client side,  
1) There are multiple concurrent connections with each sending 1 message/sec to a particular topic.
2) I am also trying to subscribe to same topic from another single connection.
It works well till 8K or 9K connections with each sending 1 message per second and one subscriber to same topic,
But more than 9K connections, my aedes process consumed 100 % CPU  and stopped responding. 
I have got below error from server side
"MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 201 drain listeners added. Use emitter.setMaxListeners() to increase limit"

I have tried to increase concurrency limit as well as tried to set concurrency to 0 but it didn't work.
I am testing with QOS 0 without persistence. 

Please help.

**Comment by GavinDmello** [comment]
What's the configuration of your machine? 
Maybe you're running out of socket descriptors. You may have to look at the memory and the socket states while testing.

**Comment by urmik** [comment]
Thanks for reply.
Please find my below machine configuration:
Ubuntu 14.04 server
RAM 16 GB
NodeJS - v9.8.0
npm - 5.7.1
aedes - 0.33.0

ulimit -n 1024000
net.core.rmem_default = 212992
net.core.rmem_max = 212992
net.core.wmem_default = 212992
net.core.wmem_max = 212992

net.core.rmem_default=536870912
net.core.wmem_default=536870912
net.core.rmem_max=536870912
net.core.wmem_max=536870912

net.ipv4.tcp_rmem="4096 16384 33554432"
net.ipv4.tcp_wmem="4096 16384 33554432"
net.ipv4.tcp_mem="786432 1048576 26777216"

net.ipv4.tcp_max_tw_buckets=360000
net.ipv4.tcp_max_syn_backlog=10000
vm.min_free_kbytes=65536
vm.swappiness=0
net.core.somaxconn=100000
net.core.netdev_max_backlog = 100000
fs.file-max=1636204

I have observed  that 
1) If I start 10k concurrent connections and each publishing 1 msg/sec on single topic then aedes process consumed around 60 to 80 % CPU.
2)Then If I start single subscriber to same topic , then aedes process consumed over 100 % CPU and my aedes server stopped accepting new connections.

Did i miss any configuration?
Please help.

**Comment by GavinDmello** [comment]
Could you upload the client and simple server script that you are using? It would help in figuring out what's going on.

**Comment by urmik** [comment]
I have been testing with following benchmark script from my other LAN system

https://github.com/emqtt/emqtt_benchmark

 ./emqtt_bench_sub -h 192.168.0.161 -p 1883 -c 1 -i 10 -t topic
./emqtt_bench_pub -h 192.168.0.161 -p 1883 -c 10000 -I 1000 -t topic -s 256

My server side code is
```javascript
var aedes = require('aedes')()
var server = require('net').createServer(aedes.handle)
process.env.port=1883
server.listen(process.env.port, function () {
    console.log(process.pid, 'server listening on port', process.env.port)
})

aedes.on('clientError', function (client, err) {
    console.log(process.pid,' client error ', client.id, err.message)
})

aedes.on('publish', function (packet, client) {
    //console.log(packet, ' message from client ', client)
})

aedes.on('client', function (client) {
    //console.log(process.pid, ' new client ', client.id)
})
aedes.on('clientDisconnect', function (client) {
    console.log(process.pid, ' Disconnect client ', client.id)
})
```

I have also tried to developed my own  benchmark script using MQTT.JS

Publisher script

```javascript

var mqtt = require('mqtt')
var clients=[];
var publishers=[];
var parallel = require('fastparallel')({released: publishCompleted,results: true})

var host = 'mqtt://192.168.0.161:1883';
var numOfClients=10000; //max count of clients
var connectionIntervals=10 //interval of connecting to the broker in milliseconds 
var numOfConn=0; //start number

var counter = 0
var Totalcnt = 0
var interval = 1000
function count() {
    Totalcnt+=counter;
    console.log('Sent Total='+Totalcnt+', rate='+ counter / interval * 1000 ,'msg/sec')
    counter = 0
}

var createConnections= setInterval(function(){
    numOfConn++;
    if(numOfConn > numOfClients)
    {
        clearInterval(createConnections)
    }
    else{
        var options = {
            clientId: "Publisher_" + numOfConn+"_"+UniqueId(10),
        };
        clients[numOfConn] = mqtt.connect(host, options);
        clients[numOfConn].on('connect',function(){
            console.log(new Date(),'connected',options.clientId);
            publishers.push(options.clientId.split('_')[1]);
        })

        clients[numOfConn].on('close', function () {
            console.log(new Date(),"disconnected:" + options.clientId);
            clearInterval(createConnections)
        });
    }
},connectionIntervals)
        startPublish();

function startPublish(){
    setInterval(function(){
        if(publishers.length > 0)
        {
            parallel(
              {}, 
              parallelPblish, 
              publishers, 
              done 
            )
        }
    
    },1000)
    setInterval(count, interval)
}

function done (err, results) {
    //console.log('published, results:', results)
}
function publishCompleted () {
    //console.log('publish completed!')
}
function parallelPblish(clnt, cb) {
    clients[clnt].publish('topic1', 'payload', function(){
        counter++;
        cb();
    })

}

function UniqueId(Size) {
    var text = "";
    var possible = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";

    for (var j = 0; j < Size; j++) {
        text += possible.charAt(Math.floor(Math.random() * possible.length));
    }

    return text;
}

```

Subscriber script

```javascript

var mqtt = require('mqtt')
var client = mqtt.connect({ port: 1883, host: '192.168.0.161', clean: true, keepalive: 0, clientId: "Subscriber" })

var counter = 0
var interval = 1000

function count() {
    console.log('received/s', counter / interval * 1000)
    counter = 0
}

setInterval(count, interval)

client.on('connect', function () {
	console.log('connected');
    count()
    this.subscribe('topic')
    this.on('message', function () {
        counter++
    })
})

```
Using my script, i can publish and subcribe 10K connections with each sending 1 msg/sec and CPU usage consumed around 80 % but when I try to connect more than 10k, my server stopped responding and CPU usage goes to 100 %.

**Comment by GavinDmello** [comment]
Assuming you're using the Erlang scripts, your setup looks good. 
I don't really have the equipment to reproduce this. Maybe @mcollina could help.
There are a few synchronous functions we could use with fast parallel but apart from that, I don't really see what could be a bottleneck with QoS 0.

**Comment by urmik** [comment]
Thanks.
How many concurrent connections Aedes should handle with this configuration machine? Or what is your max number with your benchmark testing with pub/sub messages? 
Do i need to take care anything else while deployment to achieve more concurrency and high message rate?

**Comment by urmik** [comment]
I want to use aedes in production. 50K IDLE concurrent connections using single process are fine but how can I achieve rate around 50K pub/sub messages per sec? 
Can you guide me? or It is not possible using single aedes process?

**Comment by behrad** [comment]
> how can I achieve rate around 50K pub/sub messages per sec?

I'm afraid you can't with one Aedes instance
I suggest you to first establish idle 50K connections, then increase publishing (QOS=0) rate to see how much it goes up. we would like to hear your number :)

Then add a few extra Aedes instances using cluster or pm2 module and re-run your tests, then calculate Aedes scalability factor.

**Comment by GavinDmello** [comment]
@urmik  I would suggest going for mqemitter redis.

**Comment by behrad** [comment]
> is there any other way to communicate between two aedes instances?

mqemitter-redis OR mqemitter-cs

**Comment by urmik** [comment]
I have started two aedes instances with mqemitter-redis using pm2.
I am using redis version 3.2.6.
I have tried to implement same test case again
- I have created 45K connections from 3 different machines, each machine holds 15K connections. I checked that connections handle in round robin fashion between two instances(each machine holds 22.5K connections).
- After few minutes I have started publishing messages (with QOS=0) from one machine in increasing mode (started from 1K, 2K, upto 5K) and observed that publishing 4K msg/sec to single topic(2K messages publish from one instance, 2K messages publish from other instance), aedes works fine and subscriber gets 3K-5K msg/sec.
- After increasing to publish 5K msg/sec, publishers publish 5K mgs/sec but subscriber receives messages as below and one of aedes instance(in which subscriber connected) stopped accepting new connection
rate=5413 msg/sec
rate=0 msg/sec
rate=0 msg/sec
rate=0 msg/sec
rate=6119 msg/sec
rate=7033 msg/sec
rate=11494 msg/sec
rate=11704 msg/sec
rate=11444 msg/sec
rate=9053 msg/sec
rate=0 msg/sec
rate=0 msg/sec
rate=0 msg/sec
rate=3329 msg/sec
rate=8795 msg/sec
rate=10619 msg/sec

I am excepting , i should get rate around 25K msg/sec with couple of instances. Am I missing anything or doing anything wrong?

**Comment by urmik** [comment]
@behrad Did I miss any mqemitter-redis related settings? Can you guide me to achieve maximum rate with scaling aedes instances?

**Comment by behrad** [comment]
Can you post your setup code so that we can run your clients and server?

**Comment by urmik** [comment]
Server Side

```Javascript
var aedes = require('aedes')({
    mq: require('mqemitter-redis')()
})
var server = require('net').createServer(aedes.handle)
var port = 1883
server.listen(port, function () {
    console.log(process.pid, 'server listening on port', port)
})

aedes.on('clientError', function (client, err) {
    console.log(process.pid,' client error ', client.id, err.message)
})

aedes.on('publish', function (packet, client) {
    //console.log(packet, ' message from client ', client)
})
aedes.on('client', function (client) {
    console.log(process.pid, ' new client ', client.id)
})
aedes.on('clientDisconnect', function (client) {
    console.log(process.pid, ' Disconnect client ', client.id)
})

```
Client Subscribe Script

```Javascript

var mqtt = require('mqtt')
var clients=[];

//Configurations
var host = 'mqtt://192.168.0.161:1883';
var numOfClients=1;
var connectionIntervals=10 //in milliseconds
var numOfConn=0;

//Subscribe Counter
var counter = 0
var Totalcnt = 0
var interval = 1000
function count() {
    Totalcnt+=counter;
    console.log('Receive Total='+Totalcnt+', rate='+ counter / interval * 1000,'msg/sec')
    counter = 0
}
setInterval(count,interval);


var createConnections= setInterval(function(){
    numOfConn++;
    if(numOfConn > numOfClients)
    {
        clearInterval(createConnections)
    }
    else{
        var options = {
            clientId: "SubUser_" + numOfConn+"_"+UniqueId(10),
        };
        clients[numOfConn] = mqtt.connect(host, options);
        clients[numOfConn].on('connect',function(){
            console.log(new Date(),'connected',options.clientId);
            //this.subscribe('channel_'+options.clientId.split('_')[1])
            this.subscribe('channel1')
            this.on('message', function () {
                counter++
            })
        })

        clients[numOfConn].on('close', function () {
            console.log(new Date(),"disconnected:" + options.clientId);
            clearInterval(createConnections)
        });
    }
},connectionIntervals)

function UniqueId(Size) {
    var text = "";
    var possible = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";

    for (var j = 0; j < Size; j++) {
        text += possible.charAt(Math.floor(Math.random() * possible.length));
    }

    return text;
}

```
Client Publish Script

```Javascript

var mqtt = require('mqtt')
var clients=[];
var publishers=[];
var parallel = require('fastparallel')({released: publishCompleted,results: true})

//Configurations
var host = 'mqtt://192.168.0.161:1883';
var numOfClients=15000; //max count of clients
var connectionIntervals=10 //interval of connecting to the broker in milliseconds 
var numOfConn=0; //start number

//Publish Counter
var counter = 0
var Totalcnt = 0
var interval = 1000
function count() {
    if(counter){
        Totalcnt+=counter;
        console.log('Sent Total='+Totalcnt+', rate='+ counter / interval * 1000 ,'msg/sec')
        counter = 0
    }
}

var createConnections= setInterval(function(){
    numOfConn++;
    if(numOfConn > numOfClients)
    {
        clearInterval(createConnections)
        startPublish();
    }
    else{
        var options = {
            clientId: "userPub24_" + numOfConn+"_"+UniqueId(10),
        };
        clients[numOfConn] = mqtt.connect(host, options);
        clients[numOfConn].on('connect',function(){
            console.log(new Date(),'connected',options.clientId);
        })

        clients[numOfConn].on('close', function () {
            console.log(new Date(),"disconnected:" + options.clientId);
            clearInterval(createConnections)
        });
    }
},connectionIntervals)

function startPublish(){
    setInterval(function(){
        if(publishers.length > 0)
        {
            parallel(
              {}, // what will be this in the functions 
              parallelPblish, // functions to call 
              publishers, // the first argument of the functions 
              done // the function to be called when the parallel ends 
            )
        }
    
    },1000)
    setInterval(count, interval)
}

function done (err, results) {
    //console.log('published, results:', results)
}
function publishCompleted () {
    //console.log('publish completed!')
}
function parallelPblish(clnt, cb) {
    clients[clnt].publish('channel1', 'payload', function(){
        counter++;
        cb();
    })

}

function UniqueId(Size) {
    var text = "";
    var possible = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";

    for (var j = 0; j < Size; j++) {
        text += possible.charAt(Math.floor(Math.random() * possible.length));
    }

    return text;
}

var subClient = mqtt.connect({ port: 1883, host: '192.168.0.161', clean: true, keepalive: 0, clientId: "subForPub_"+UniqueId(5) })
subClient.on('connect', function () {
    count()
    this.subscribe('PubControl')
    this.on('message', function (topic,msg) {
        //console.log(JSON.parse(msg.toString()).noOfPub)
        if(JSON.parse(msg.toString()).noOfPub==='stop')
        {
            publishers = new Array();
        }
        else{
            publishers = new Array();
            for(i =1 ; i<=JSON.parse(msg.toString()).noOfPub; i++ )
            {
                publishers.push(i);
            }
        }
    })
})

```

To publish messages in increasing mode, connect client to aedes server
Publish message {"noOfPub":100} on "PubControl" topic. it will start first 100 client to publishing msg/sec
Publish message {"noOfPub":1000} on "PubControl" topic. it will increase from 100 to 1000 client to publishing msg/sec
Publish message {"noOfPub":"stop"} on "PubControl:" topic. it will stop publishing messages.

**Comment by urmik** [comment]
@behrad did you get a chance to run above code?
I have also tried with my custom mqemitter-rabbitmq where i got rate little more than mqemitter-redis. 
But as I mentioned above, with one aedes instance i can get rate around 13 K msg/s and with two aedes instance i should get rate around 25 K msg/s. Did I miss anything?

**Comment by behrad** [comment]
> I have also tried with my custom mqemitter-rabbitmq where i got rate little more than mqemitter-redis.

I don't think RabbitMQ is faster than Redis pub/sub! 
And bottleneck should be aedes process itself not pub/sub backends.

**Comment by robertsLando** [comment]
@urmik Could you try to replicate test with latest Aedes versions?

**Comment by lizzymendivil** [comment]
@urmik hi, could u share with me your configuration about redis, please?
what else did u do to use this: `mq: require('mqemitter-redis')()` ?

**Comment by Misiu** [comment]
@urmik any updates on this?
I'd like to run a couple of instances of aedes, but I'm new to it and can't find anything about clustering and any example config.
