### ISSUE TITLE
Forcing empty topic in `onAuthorize()`

### ISSUE THREAD

**Issue by drasko** [moscajs/aedes#199]
@mcollina forcing `packet.topic = ''` in `onAuthorize()` seems to be preventing any publish, but no error is printed.

I was expecting that the check in `handlePublish()` will get this (https://github.com/mcollina/aedes/blob/master/lib/handlers/publish.js#L22), however it is not the case.

We are trying to find the best way to send a message to other service without publishing it to local MQTT clients, so this forcing `packet.topic` to empty string in `onAuthorize()` seems to be doing the trick.

At this point I would like to understand:
- What is happening when we force `packet.topic = ''` in `onAuthorize()`
- Can it have any consequences to Aedes functioning
- Is there some better way to achieve desired effect (on client publish take a message from Aedes and forward it to other service, but prevent Aedes to publish to local clients),

**Comment by drasko** [comment]
Actually, I can see here that `autorizePublish()` is called after these check of topic length: https://github.com/mcollina/aedes/blob/master/lib/handlers/publish.js#L36. So this can probably explain why there are no errors when `packet.topic` is forced to empty string in `onAuthorize()`.

However, I am failing to see what happens after, and why there are no errors reported...

**Comment by mcollina** [comment]
It's definitely not safe to do, and it should error (but currently it doesn't). I do not think we are revalidating the topic after it has been altered.

I do not think this feature is achievable (publish remotely but not locally) without some change to aedes. However it'd be a nice addition. This is typically called bridge protocol (see https://github.com/mqtt/mqtt.github.io/wiki/bridge_protocol and other links on Google) for more details.
A PR supporting this would be highly welcomed.

**Comment by drasko** [comment]
@mcollina our idea was not to send messages to another MQTT broker, but to some other (arbitrary service) and use Aedes purely for device connectivity over MQTT.

Then after some processing, messages will be sent back to Aedes, and only then sent to all Aedes clients.

You can see our implementation here: https://github.com/mainflux/mainflux/blob/master/mqtt/mqtt.js

How something like this can be achieved?
