### ISSUE TITLE
Two-way TLS authentication

### ISSUE THREAD

**Issue by benjamin658** [moscajs/aedes#225]
I'm trying to implement the authentication method on the serve,
according to the document,  it only shows  that how I can authenticate a 
client by its username and password.

`instance.authenticate(client, username, password, done(err, successful))`

Is it possible to authenticate client with two-way TLS authentication?

**Comment by mcollina** [comment]
You have to do that at TLS layer: https://nodejs.org/api/tls.html.
It would be good to have a good guide on that topic to link to.
