### ISSUE TITLE
Feature about server side availablilty 

### ISSUE THREAD

**Issue by xushunke** [moscajs/aedes#226]
I am looking 4 a way 2 implement this feature,but nothing elegant found.I know its part of MQTT5 spec.
Considering the server side,without this feature,i have 2 make A(only one) new service 2 transfer the msg 2 the MQ which dispatch the msg 2 each server(consumer).However,as u can see ,the new service will be A weakness of availablilty obviously
can u give me a direction? pls

![](https://user-images.githubusercontent.com/8627326/50649190-3343ef00-0fb8-11e9-9fac-92caa435b3ee.png)

**Comment by robertsLando** [comment]
@xushunke Could you explain your problem better please?

**Comment by robertsLando** [comment]
Closing until response
