### ISSUE TITLE
Http cookies over websocket

### ISSUE THREAD

**Issue by MikyWoW** [moscajs/aedes#230]
Is there build in access to cookies in aedes.authenticate when is websockets used? I didnt found it.

I have plan to use mqtt in website without javascript have to touch session ID (http only).

My solution for PHPSESSID:
```
const aedes = require('aedes')();
const ws = require('websocket-stream');
const cookie = require('cookie')

const httpServer = require('http').createServer();

const wsPort = 3000;
const srv = ws.createServer({server: httpServer}, aedes.handle);

srv.on("connection",(soc,req)=>{
    soc.cookie = cookie.parse(req.headers.cookie);
})

httpServer.listen(wsPort, () => {
    console.log('Running on WS: %s', wsPort);
});

aedes.authenticate = async function (client, username, password, callback)
{
    const sessionID = client.conn.socket.cookie.PHPSESSID;
    ....
}
```

**Comment by CyanoFresh** [comment]
need this too

**Comment by CyanoFresh** [comment]
https://github.com/mcollina/aedes/commit/18aeb22c7303478dbae2721c76c877aa05176541 needs to be added to release

**Comment by CyanoFresh** [comment]
@mcollina please make a release

**Comment by Uttam-EWW** [comment]
Any update on this?

**Comment by robertsLando** [comment]
@Uttam-EWW this can be accessed from `client.req`

**Comment by Uttam-EWW** [comment]
> @Uttam-EWW this can be accessed from `client.req`

Okay, thank you.
