### ISSUE TITLE
Reuse existing websocket server: which path?

### ISSUE THREAD

**Issue by namgk** [moscajs/aedes#236]
Hi there,

It seems _websocket-stream_ doesn't have the notion of path? I was using vanilla ws module from nodejs and I can create a websocket at a specific path, says 

    /webserver_socket

Now I want to incorporate mqtt over websocket to the same server, so I want it to be on another path, says 

    /mqtt_socket

How do I work this out?

For the original mosca project, I can do things like:

    moscaMqtt.attachHttpServer(httpServer, path)

**Comment by nightwolfz** [comment]
Something like
```js
  ws.createServer({
    server: httpServer,
    path,
  }, aedes.handle)
```
?
