### ISSUE TITLE
My aedes test problem

### ISSUE THREAD

**Issue by weiliudong** [moscajs/aedes#248]
terminal.js

var aedes = require('aedes')();
var myAuth = require('./myAuth');
var port = 1883;

var server = require('net').createServer(aedes.handle);
myAuth.loginAuth(aedes);
myAuth.publishAuth(aedes);
myAuth.subscribeAuth(aedes);

server.listen(port, function () {
    console.log('server listen:', port);
});

aedes.on('client', function (client) {
    // do something...
});

aedes.on('clientDisconnect', function (client) {
    // do something...
});

aedes.on('clientError', function (client, err) {
    // do something...
});

aedes.on('connectionError', function (client, err) {
    // do something...
});

aedes.on('keepaliveTimeout', function (client) {
    // do something...
});

aedes.on('ack', function (packet, client) {
    // do something...
});

aedes.on('subscribe', function (packet, client) {
    // do something...
});

aedes.on('publish', function (packet, client) {
    // do something...
});

aedes.on('unsubscribe', function (packet, client) {
    // do something...
});

module.exports = aedes;

myAuth.js

var crypto = require('crypto');

//login
exports.loginAuth = function (aedes) {
    aedes.authenticate = function (client, username, password, callback) {
        if (username && password && client) {
            var passWord = password.toString();
            var pwd = String(crypto.createHash('md5').update(username).digest('hex'));
            if (passWord === pwd) {
                client.user = username;
                callback(null, true);
            } else {
                callback(null, false);
            }
        } else {
            callback(null, false);
        }
    };
};

//pub
exports.publishAuth = function (aedes) {
    aedes.authorizePublish = function (client, pyload, callback) {
        var user = client.user,
            topic = pyload.topic;
        if (topic.indexOf('/') !== -1) {
            var arr = topic.split('/');
            var username = arr[1];
            if (user === username) {
                callback(null)
            }
        }
    };
};

//sub
exports.subscribeAuth = function (aedes) {
    aedes.authorizeSubscribe = function (client, sub, callback) {
        var user = client.user,
            topic = sub.topic;
        if (topic.indexOf('/') !== -1) {
            if (topic.indexOf('/') !== -1) {
                var arr = topic.split('/');
                var username = arr[1];
                if (user === username) {
                    callback(null, sub);
                }
            }
        }
    };
};

test.js

var crypto = require('crypto');
var mqtt = require('mqtt');
var serverIp = '127.0.0.1';
var username = "test";
var clientId = 'test_1';
var password = String(crypto.createHash('md5').update("test").digest('hex'));
var topic = "$IOT/" + username;
var options = {
    clientId: clientId,
    password: password,
    username: username
};
var client = mqtt.connect('mqtt://' + serverIp + ':1883', options);

client.on('connect', function () {
    client.subscribe(topic);
    var msg = "I am a tester.";
    client.publish(topic, msg, {qos: 0});
});

client.on('message', function (topic, message) {
    console.log(message.toString());
});

client.on('error', function (err) {
    console.log(err)
});

I started 40,000 test clients on the server and the memory overflow was very serious.
![image](https://user-images.githubusercontent.com/24930918/60871964-6b2d3700-a266-11e9-9045-5fbdf81e4348.png)

At the beginning, it was about 600M of memory. As the memory usage became larger and larger over time, I was surprised.
My programs are written in accordance with the api. Where is my problem? Who can help me?

**Comment by weiliudong** [comment]
In addition, the process cpu occupancy rate is as high as 40%.

**Comment by mcollina** [comment]
Running some quick math, with 40,000 clients and a 2GB memory usage we have that each client is occupying 50 bytes of memory. I think it’s a good number, and there is nothing wrong.
The 40% CPU usage might be due to PING packets. You can disable these in the client.

**Comment by weiliudong** [comment]
thank you very much!
