### ISSUE TITLE
Why client.publish directly calls deliver0 or deliverQoS

### ISSUE THREAD

**Issue by gnought** [moscajs/aedes#285]
client.subscribe or client.unsubscribe call `handleSubscribe` https://github.com/mcollina/aedes/blob/master/lib/client.js#L204

Why client.publish https://github.com/mcollina/aedes/blob/master/lib/client.js#L175  directly calls `deliver0` or `deliverQoS` instead of `handlePublish` ?

by-design or other concerns?

**Comment by mcollina** [comment]
In subscribe, I had to emulate receiving a SUBSCRIBE packet. in publish, I need to send a PUBLISH packet to the client and handlePublish is to receive one.

**Comment by gnought** [comment]
client.subscribe -> client SUBSCRIBE to broker
I think the same logic is
client.publish -> client PUBLISH to broker, in this way, it should use `handlePublish`
if sending a PUBLISH packet to client, i think the function should be `Aedes.prototype.publish` which will use `deliver0` or `deliverQoS`

**Comment by mcollina** [comment]
The _current_ implementation of `client.publish` is to *send* a PUBLISH packet to a client (and handle QoS). That is actually a much needed feature of a lot of applications, and I don't think it's worth changing the name.

`Aedes.prototype.publish` (https://github.com/mcollina/aedes/blob/da8ba5ade870c4b608858549da62b5dced12a72c/aedes.js#L226)  publishes a packet to _all_ clients. It's a different use case. 

I do not understand the use case of "faking" the reception of PUBLISH packet from a client. What about QoS handling? Is the "fake" PUBLISH (through `handlePublish`) going to send PUBREL to the client?

**Comment by gnought** [comment]
Thanks the clarification. 

Logically, We call `client.publish`, in a first glance the point of view is from _client_ and _client_ publishes something, while we call `broker.publish`, the point of view is from _broker_ and _broker_ publishes something.
If we states `client.publish` to be 
> send a PUBLISH packet to a client

I know it is _current_ implementation, but it makes a bit confusion, and other developers feel quite frustrated.

I also notice that `client.publish` is like a loopback feature. It publishes something back to _client_ by ignoring what it subscribed. The following test demonstrates it. 

```
test.only('publish & subscriber (emulate) - client.publish', function (t) {
  var broker = aedes()

  broker.on('client', function (client) {
    client.subscribe({
      topic: 'hello',
      qos: 0
    }, function (err) {
      t.error(err, 'no error')
      client.publish({
        topic: 'foo',
        payload: Buffer.from('bar'),
        qos: 0
      })
    })
  })

  var s = connect(setup(broker))
  s.outStream.on('data', function (packet) {
    console.log(packet)
  })
  broker.on('closed', t.end.bind(t))
})
```

`Aedes.prototype.publish` could be publish a packet to one client if we specify the client parameter, like the following:

```
test.only('publish & subscriber (emulate) - broker.publish', function (t) {
  var broker = aedes()

  broker.on('client', function (client) {
    client.subscribe({
      topic: 'hello',
      qos: 0
    }, function (err) {
      t.error(err, 'no error')
      broker.publish({
        topic: 'hello',
        payload: Buffer.from('world'),
        qos: 0
      }, client)
    })
  })

  var s = connect(setup(broker))
  s.outStream.on('data', function (packet) {
    console.log(packet)
  })
  broker.on('closed', t.end.bind(t))
})```

**Comment by mcollina** [comment]
> so why we have client parameter in the function?

I _think_ it's due to QoS.

**Comment by robertsLando** [comment]
> I think it's due to QoS

Isn't QoS from the `packet`?

The `client` prop is only used in `callPublished` method. 

```js
function callPublished (_, done) {
  this.broker.published(this.packet, this.client, done)
  this.broker.emit('publish', this.packet, this.client)
}
```

From what I have understand `client` parameter is needed in `Aedes.prototype.publish` to get the client that published that packet (that is null when is from broker)
