### ISSUE TITLE
Aedes.published function vs publish event

### ISSUE THREAD

**Issue by gnought** [moscajs/aedes#289]
What's the difference between `Aedes.published` function (https://github.com/mcollina/aedes/blob/master/aedes.js#L211)  and `publish` event (https://github.com/mcollina/aedes/blob/master/aedes.js#L212)?

I think that we should not expose `Aedes.published` function as it is a redundant. Event is good enough.
And it seems `Aedes.published` function will cause https://github.com/mcollina/aedes/issues/193

**Comment by mcollina** [comment]
.published enables backpressure to happen.
