### ISSUE TITLE
How can I use Aedes as MQTT Borker?

### ISSUE THREAD

**Issue by mohsenyaghoobi** [moscajs/aedes#328]
Hello,

how can I use aedes as MQTT broker? 
I installed aedes on Ubuntu, but I dont know how  and where can I create a Broker an how can I Use it? could you please help me and explain more how can I do it! 

Best Regards
Mohsen

**Comment by weiliudong** [comment]
Aedes api has demo.you can try it.
https://github.com/mcollina/aedes

**Comment by kamrankamrani** [comment]
you can run aedes as your broker in node js simply with npm and then you can build some clients with any kind of mqtt client libs such as npm mqtt

**Comment by sombriks** [comment]
@mohsenyaghoobi take a look at this sample project: https://github.com/sombriks/sample-mqtt
