### ISSUE TITLE
[feat] Bridge

### ISSUE THREAD

**Issue by Andreyooo** [moscajs/aedes#329]
Is it possible to bridge an aedes broker to a mosquitto broker?

**Comment by mcollina** [comment]
The bridge protocol is currently not implemented, but it would be awesome to have!

**Comment by qwertangel** [comment]
+1 , not just mosquitto but any mqtt broker.

**Comment by robertsLando** [comment]
@qwertangel It is on our todos, in the while you could check https://github.com/robertsLando/Mqtt2Mqtt

**Comment by oldrich-s** [comment]
I have a working prototype to connect Aedes as a bridge to Mosquitto using Mqtt.js library. Would there be interest in including it in Aedes library or is it out of scope for Aedes?

**Comment by robertsLando** [comment]
> I have a working prototype to connect Aedes as a bridge to Mosquitto using Mqtt.js library. Would there be interest in including it in Aedes library or is it out of scope for Aedes?

Absoluitely! Would you mind to add it to examples? Also rememver to add a link to it in readme
