### ISSUE TITLE
Wrong clients status

### ISSUE THREAD

**Issue by robertsLando** [moscajs/aedes#331]
Hi, I'm using Aedes broker on my project https://github.com/robertsLando/Mqtt2Mqtt

Some mqtt devices that I use doesn't support will message so I have set up a rule on the broker that once a client disconnects/connect sends a message in a specific topic with the clientID with true/false based on client connection status. 

The problem is that sometimes it happens that I receive a disconnect from a client but the client is still connected as he sends/receives packets correctly. Is this a known issue? 

Client connect: https://github.com/robertsLando/Mqtt2Mqtt/blob/master/lib/broker.js#L38
Client disconnect: https://github.com/robertsLando/Mqtt2Mqtt/blob/master/lib/broker.js#L52

**Comment by robertsLando** [comment]
@mcollina I'm still expecting some strange behaviour with client connection management, could you check this issue more in deep? 

I will try to simulate it someway but I can't reproduce it successfully for now.

**Comment by mcollina** [comment]
Unfortunately I have no time to check this. I'm happy to review a PR, if you happen to fix it.

**Comment by robertsLando** [comment]
@gnought Could you help with this? I'm creating a test to replicate the problem.

**Comment by robertsLando** [comment]
@mcollina Here the example code I have created: 


```js
var mqtt = require('mqtt')
var aedes = require('aedes')()
var server = require('net').createServer(aedes.handle)
var Promise = require('bluebird')
var port = 1883

var URL = 'mqtt://localhost';
var CLIENTS = {}

var totalClients = 100;
var totalConnections = 50;
var totalPublish = 30;

// fired when a client connects
aedes.on('client', function (client) {
    var cId = client ? client.id : null;
    console.log('Client Connected: \x1b[33m' + cId + '\x1b[0m')

    if (CLIENTS.hasOwnProperty(cId)) {
        CLIENTS[cId].cCount++
    }
})

// fired when a client disconnects
aedes.on('clientDisconnect', function (client) {
    var cId = client ? client.id : null;
    console.log('Client Disconnected: \x1b[33m' + cId + '\x1b[0m')

    if (CLIENTS.hasOwnProperty(cId)) {
        CLIENTS[cId].dCount++
    }
})

// aedes.on('subscribe', function (subscriptions, client) {
//     console.log('MQTT client \x1b[32m' + (client ? client.id : client) +
//         '\x1b[0m subscribed to topics: ' + subscriptions.map(s => s.topic).join('\n'))
// })

// aedes.on('unsubscribe', function (subscriptions, client) {
//     console.log('MQTT client \x1b[32m' + (client ? client.id : client) +
//         '\x1b[0m unsubscribed to topics: ' + subscriptions.join('\n'))
// })

// aedes.on('publish', async function (packet, client) {
//     console.log('Client \x1b[31m' + (client ? client.id : 'BROKER_' + aedes.id) + '\x1b[0m has published', packet.payload.toString(), 'on', packet.topic)
// })


const wait = (time) => new Promise((resolve) => setTimeout(() => resolve(), time))

const rand = (min, max) => {
    return Math.round(Math.random() * (max - min) + min)
}

const end = (c, force) => new Promise((resolve, reject) => c.end(force, null, (err) => err ? reject(err) : resolve()))

const startClient = (ID) => {
    return new Promise((resolve) => {
        var client = mqtt.connect(URL, { clientId: ID })

        client.on('connect', function () {
            resolve(client)
        })
    })
}

const doStuff = async (ID) => {
    for (let index = 0; index < totalConnections; index++) {
        var client = await startClient(ID)
        for (let k = 0; k < totalPublish; k++) {
            var topic = 'test' + k
            client.subscribe(topic)
            client.publish(topic, 'Test ' + k + ' done', { qos: 1 })
        }

        await wait(rand(0, 100))
        await end(client, !!rand(0, 1))
    }
}

const startClients = async () => {

    for (let index = 0; index < totalClients; index++) {
        CLIENTS['client_' + index] = { cCount: 0, dCount: 0 }
    }

    await Promise.map(Object.keys(CLIENTS), (cId) => doStuff(cId))

    console.log("##### DONE #####");

    var count = 0

    for (const k in CLIENTS) {
        if (CLIENTS[k].cCount !== CLIENTS[k].dCount) {
            count++;
            console.log("### INCONSISTENCE DETECTED:", k, CLIENTS[k]);
        }
    }

    if (count) {
        console.log("Total Inconsistences:", count);
        process.exit(0)
    } else {
        startClients()
    }
}

server.listen(port, function () {
    console.log('Aedes listening on port', port)
    //setTimeout(startClients, 5000)
    startClients()
})
```

It runs until it found inconsistences, please check it

**Comment by robertsLando** [comment]
@mcollina Could this be fixed by #326 ?

**Comment by mcollina** [comment]
possibly

**Comment by robertsLando** [comment]
Why don’t accept the pr so and create an issue for the missing test? At least a bug could be fixed 

Daniel

**Comment by mcollina** [comment]
Please send a test with the PR and the code that is already in there.. I've
already gone into that path that you describe, and it does not end well.

Il giorno ven 6 dic 2019 alle ore 18:16 Daniel Lando <
notifications@github.com> ha scritto:

**Comment by robertsLando** [comment]
I have no idea about how to make a test for that, I will try to create a PR on Monday. I understand what you mean, if you accept that PR no one will ever make that test for something that is working :) 

Daniel

**Comment by robertsLando** [comment]
@mcollina Any suggestion about the approch I could use to test the duplicated done call? 

I'm tring everything but nothing works

**Comment by robertsLando** [comment]
What I have tried is: 

```js
test('supports pingreq/pingresp', function (t) {
  t.plan(2)

  var s = noError(connect(setup()), t)

  s.outStream.on('data', function (packet) {
    t.equal(packet.cmd, 'pingresp', 'the response is a pingresp')
    setTimeout(() => {
      t.pass('no duplicates')
    }, 500)
  })

  s.inStream.write({
    cmd: 'pingreq'
  })
})
```

Because when `handlePing` is called the double `done` should invoke `client._nextBatch` twice but I don't get 2 event here

**Comment by mcollina** [comment]
I'm sorry I do not have any suggestion right now. I've been on the road all of last week and I'll be all of next week, and then I'll be on vacation until the 6th of January.

**Comment by robertsLando** [comment]
@mcollina Don't worry Matteo, will try to investigate my own :) Buone vacanze!

**Comment by robertsLando** [comment]
@mcollina Still expecting this issue, I'm still not able to identify what is causing this but even with other projects using aedes this happens. 

I also see that aedes sends the will message like the client is disconnected even if it is still connected

**Comment by robertsLando** [comment]
@mcollina Maybe I have found something... Why [here](https://github.com/mcollina/aedes/blob/master/lib/handlers/index.js#L54) you are closing client connection in that way? Shouldn't you call `client.close()` instead? The same [here](https://github.com/mcollina/aedes/blob/master/lib/handlers/index.js#L57)

**Comment by robertsLando** [comment]
I have also find the problem with will messages. [here](https://github.com/mcollina/aedes/blob/master/aedes.js#L92) If the broker closes for some reason, once the broker restarts, after `3 * heartbeatInterval` seconds, all old will messages are sent, this is not correct as I would receive a will message from a client that may be connected right now.

**Comment by robertsLando** [comment]
The fix that I have created for now is to use an *hybridPersistence* :

```js
function hybridPersistence() {
  return new Promise((resolve, reject) => {
    var inMemory = require('aedes-persistence')()
    var onDisk = require('aedes-persistence-mongodb')({
      db: mongoose.connection.useDb(configDB.mqttDb).db
    })

    // Store just retained messages
    inMemory.storeRetained = onDisk.storeRetained
    inMemory.createRetainedStream = onDisk.createRetainedStream
    inMemory.createRetainedStreamCombi = onDisk.createRetainedStreamCombi

    onDisk.once('ready', resolve.bind(this, inMemory))
    onDisk.once('error', reject)
  })
}
```

**Comment by mcollina** [comment]
I think a better approach is to check if there is a lingering will message when a client connects and in case send it before "connecting" it.

Note that a broker crashing is really problematic case as _we are not able to send will messages for connected clients_ because there is no broker running.

**Comment by robertsLando** [comment]
Why not make this check when broker starts? I mean when broker inits it check for will messages in store and sends all them ?

**Comment by robertsLando** [comment]
Also I'm thinking about the possiblity to create an `hybridPersistence`, a persistence where you can choose what to keep in memory and what to keep on-disk. I my example I'm using mondogb but the only thing I'm interested to make persistent is `retained` messages. Is this possible someway?

**Comment by mcollina** [comment]
> Why not make this check when broker starts? I mean when broker inits it check for will messages in store and sends all them ?

Aedes is designed to work in a high availability scenario. Ideally there is another broker running at the same time, and when one broker becomes unresponsive the will messages have to be delivered.

**Comment by robertsLando** [comment]
Ok so the sultion is

> check if there is a lingering will message when a client connects and in case send it before "connecting" it

?

**Comment by mcollina** [comment]
Yes

**Comment by robertsLando** [comment]
Ok I will try to create a PR for that. Could you please tell me something about the `hybridPersistence` idea?

**Comment by mcollina** [comment]
close is triggered automatically when the connection ends gracefully (`.end()`). It's not triggered when `.destroy()` is called.

Hybrid persistences will likely be not spec compliant

**Comment by robertsLando** [comment]
@mcollina PR done for that

**Comment by robertsLando** [comment]
@mcollina Is there any possibility that a client goes offline, client disconnect event is not triggered, the client connects (with same client ID) and than the keepalive timeout fires and detects the client offline?
