### ISSUE TITLE
examples clusters error

### ISSUE THREAD

**Issue by qiyongtao** [moscajs/aedes#342]
[Error: UNKNOWN: unknown error, unlink '\F:\mqttServer\shared-mqemitter'] {
errno: -4094,
code: 'UNKNOWN',
syscall: 'unlink',
path: '\\F:\mqttServer\shared-mqemitter'
}

os: win10
nodejs: v12.13.1

**Comment by robertsLando** [comment]
@qiyongtao Did you fixed someway? Seems not something related to the example but maybe an OS/Node problem
