### ISSUE TITLE
Broker publish packet to disconnected client

### ISSUE THREAD

**Issue by Ryuunofire27** [moscajs/aedes#345]
Hi, I use an authenticate function and, although it returns false, the broker tries to send a package to the client and is already disconnected.
At first I thought it was because the function was asynchronous but testing synchronously and only sending false, the problem persists.

// function for test
function authenticate (client, username, password, callback) {
    callback(null, false);
}

// Broker publish event
broker.on('publish', (packet, client) => {
    console.log(client);
    const messageLog = `Publish packet by ${client && client.id}`;
    console.log(messageLog);
})

// Console message
[App: 17/12/2019, 12:19:48] Publish packet by null

**Comment by robertsLando** [comment]
@Ryuunofire27 Try to log the packet, it could be a message published from the broker on `$SYS` topic

**Comment by gnought** [comment]
@Ryuunofire27 could you provide a working code for use to have a check?
