### ISSUE TITLE
[bug] Memory leak on client.js 'connect' event

### ISSUE THREAD

**Issue by srmarjani** [moscajs/aedes#348]
Hi
I am using [mqtt](https://www.npmjs.com/package/mqtt) as mqtt client.
In my use case I need to send about 1000 QOS1 packet every 4 second.
every 4 seconds I open a new client by [mqtt.connect](https://www.npmjs.com/package/mqtt#connect) then I publish 1000 packets by [p-map](https://www.npmjs.com/package/p-map) by concurrency 100 and at the end I end connection 

But I am encountering below warning at aedes side

```
(node:15528) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connected listeners added. Use emitter.setMaxListeners() to increase limit
```
And the stack trace is 
```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connected listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:247:17)
    at Client.addListener (events.js:263:10)
    at Parser.enqueue (***\node_modules\aedes\lib\client.js:313:17)
    at Parser.emit (events.js:189:13)
    at Parser._newPacket (***\node_modules\mqtt-packet\parser.js:631:10)
    at Parser.parse (***\node_modules\mqtt-packet\parser.js:39:41)
    at Socket.nextBatch (***\node_modules\aedes\lib\client.js:68:23)
    at Socket.emit (events.js:189:13)
    at emitReadable_ (_stream_readable.js:535:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
I think the problem is in this function
```javascript
function enqueue (packet) {
  this.client._parsingBatch++
  // already connected or it's the first packet
  if (this.client.connackSent || this.client._parsingBatch === 1) {
    handle(this.client, packet, this.client._nextBatch)
  } else {
    this.client.on('connected', () => {
      handle(this.client, packet, this.client._nextBatch)
    })
  }
}
```
Is there any problem in opening and closing the connection to broker?

Thanks

**Comment by robertsLando** [comment]
@srmarjani Try to set `concurrency` option of aedes to 200

**Comment by robertsLando** [comment]
@srmarjani Did you fixed? Can this be closed?

**Comment by srmarjani** [comment]
Hi 
I will try to reproduce the bug. because I choose another approach.
But I guess increasing the concurrency is not a solution.
Because concurrency is 100 by default but as you see in warning 11 event on `connected` event of client make problem.

**Comment by robertsLando** [comment]
You right! I think in that case we should queue packets and set connect event in client init, when connected event is fired handle all queued packets (if present) 

Daniel
