### ISSUE TITLE
Project development status

### ISSUE THREAD

**Issue by robertsLando** [moscajs/aedes#354]
Hi @mcollina, just to know, what are your future plans for aedes ? I mean is there a Roadmap to a 1.0.0 version? In most posts you say you don't have time for aedes but I would like to know what you plan to do with it as mosca development has ended in 2018

**Comment by mcollina** [comment]
We can essentially call 0.40.0 1.0.0. I'll do a release for that asap - it's as stable as I can make it anyway.

Would you like to help maintaining it? 

What I had in mind when starting this _a long time ago_ is to rewrite Mosca on top of all aedes modules and provide a seamless experience. Would you be interested in working on that?

**Comment by robertsLando** [comment]
@mcollina Yes, volentieri :smile: As I'm activelly using aedes I would be glad to help with it

**Comment by mcollina** [comment]
I've moved all aedes and mosca repos to a new org, moscajs.

**Comment by mcollina** [comment]
@behrad @gnought @GavinDmello I've all invited to this new org.

**Comment by GavinDmello** [comment]
Thanks @mcollina, @robertsLando. I could chip in whenever I get time. :+1:

**Comment by behrad** [comment]
Happy new org @mcollina Very busy these days but observing activities here, thanks @robertsLando

**Comment by robertsLando** [comment]
Happy to be part of this team :smile:

**Comment by robertsLando** [comment]
@mcollina About my main question. In my opinion the main difference that could point peoples to use aedes instead of Mosca is to use a broker that supports clustering. Maybe this could be explained in docs? I also would like to add some more usage examples to examples folder.

Other questions:
- Is there any benchmark 'Aedes vs Mosca'?
- What about to start a project or an issue with a TODO to support MQTT 5 in Aedes (like one I saw that was opened in MQTTjs) ?
- Is there any issue/feature you think it's important to implement?

**Comment by robertsLando** [comment]
@mcollina I also saw your post [here](https://twitter.com/matteocollina/status/1083322337292890112) where you explain why you stopped working at Mosca.

I think you could make some profits with aedes if you enable sponsors on it and also on your github profile. 

Personally I have used many different way that sponsors can use to support my opensource work like:

- Patreon
- Paypal
- Buymeacoffie
- Github sponsors

I have very small projects and I'm getting some supportes and founds so I think If you enable sponsors here you could make interesting profits (and you would be more interested to maintain it).
As you said in that twitter post lot peoples are using your works and I'm sure that you can get lot supporters if you make it in the right way. If you want more info or something else let me know

**Comment by srmarjani** [comment]
Hi
I am using this package in my project.
Now is time to pay price by contributing 
:)

**Comment by mcollina** [comment]
Would you like to be added to the org?

**Comment by robertsLando** [comment]
@mcollina I think that creating a TODO/Roadmap would be the best thing for new contributors.

**Comment by mcollina** [comment]
Would you like to craft one? From my point of view:

[ ] update Mosca so that is based on Aedes and mqemitter (this means a full rewrite of the codebase)
[ ] use github action to test all the persistences / mqemitter on separate processes to avoid limits of the databases
[ ] implement the authorizer.
[ ] closing all issues and PRs that are outstanding

On top of this, we should work on adding MQTTv5 as a long term activity

**Comment by robertsLando** [comment]
> update Mosca so that is based on Aedes and mqemitter (this means a full rewrite of the codebase)

Why this? What about to make mosca unmantained (like it is from 2018) and redirect users to use aedes instead?

> implement the authorizer 

More info about what is this?

**Comment by mcollina** [comment]
> Why this? What about to make mosca unmantained (like it is from 2018) and redirect users to use aedes instead?

Mosca provides an out-of-the-box experiece with all the dependencies. I'm also happy to mark that unmaintained. Moreover, we should also add some integration tests that are currently missing. In my original ideas those would live inside Mosca, but they can also live in another repo.


Here is the authorizer https://github.com/moscajs/mosca/blob/master/lib/authorizer.js and docs are in https://github.com/moscajs/mosca/wiki/Authentication-&-Authorization#using-moscas-standalone-authorizer-with-an-embedded-mosca.

**Comment by robertsLando** [comment]
@mcollina In poor words the authorizer provides clients authorizations based on a json file that is used as db of the users and their passwords and allowed publish/subscribe topics glob. 

Isn't this only used when running mosca as standalone? We should so firstly make aedes be runnable as standalone like mosca? 

> I'm also happy to mark that unmaintained

In my opinion this would be good as will force lot users to use aedes, this means more testers and I think the effort needed to rewrite the mosca codebase is not worth it.

**Comment by robertsLando** [comment]
I have created a Project with related issues/features. https://github.com/moscajs/aedes/projects/1
