### ISSUE TITLE
Use reusify for client enqueue

### ISSUE THREAD

**Issue by robertsLando** [moscajs/aedes#356]
I see that aedes uses `reusify` for `DoEnqueue` function. Could we use reusify also for client [enqueue](https://github.com/moscajs/aedes/blob/master/lib/client.js#L326) method? 
Could it increese performances?

**Comment by mcollina** [comment]
I don't see how, there is very little state involved

**Comment by robertsLando** [comment]
@mcollina Ok, just a thought
