### ISSUE TITLE
[feat] Extend Aedes tests against all mqemitter/persistences

### ISSUE THREAD

**Issue by robertsLando** [moscajs/aedes#357]
Use Github Actions to trigger more extended tests for supported aedes-persistences/mqemitters

**Comment by srmarjani** [comment]
Hi
This is not clear enough.
Did you mean , add tests for all of aedes-persistences/mqemitters like ones for redis and mongo?

**Comment by robertsLando** [comment]
Nope. From what I have understand I think @mcollina means that would like that aedes tests need to run using all difference persistences/mqemitters avbailable using [Github actions](https://github.com/features/actions) instead of redis, they allows to create multiple tasks, I think we could handle this by simply add 2 env vars that specify the mqemitter instance and the persistence and edit aedes current test in this way:

In [test/helper.js](https://github.com/moscajs/aedes/blob/master/test/helper.js) 

```
var persistence = require(process.env.AEDES_PERSISTENCE)
var mqemitter = require(process.env.MQEMITTER)
```

Then [here](https://github.com/moscajs/aedes/blob/master/test/helper.js#L16) add the required persistences to aedes options

**Comment by mcollina** [comment]
I would prefer a very different approach.

Having some tests that use mqtt.js to connect to Aedes and very some of the basic functionality. 
Most of the tests here are unit and they expect things to run single-process.

**Comment by robertsLando** [comment]
Ignore my PR so. WIll wait you to start a different repo for them. I think the actions.yml code can be taken as a base for actions (or not) ?

**Comment by mcollina** [comment]
yes, definitely!

Il giorno gio 23 gen 2020 alle ore 10:30 Daniel Lando <
notifications@github.com> ha scritto:

**Comment by robertsLando** [comment]
@mcollina What about `aedes-test` repo? Would you like me to create it?

I also need to understand which tests you would like to add there

**Comment by mcollina** [comment]
Integration/black box test.

Start an _external_ aedes broker and use MQTT.js to validate it works.

**Comment by robertsLando** [comment]
https://github.com/moscajs/aedes-tests
