### ISSUE TITLE
[feat] Aedes as a standalone service

### ISSUE THREAD

**Issue by robertsLando** [moscajs/aedes#359]
Like Mosca https://github.com/moscajs/mosca/wiki/Mosca-as-a-standalone-service

**Comment by mcollina** [comment]
My view of Mosca is to be “aedes standalone”, with a CLI and everything.

**Comment by robertsLando** [comment]
Ok so in poor words you want to replace Mosca core with Aedes and keep Mosca only as standalone service? Instead of a complete codebase rewrite of Mosca wouldn't be better to just import aedes as dependence in Mosca?

**Comment by mcollina** [comment]
Yes, that's what I was trying to say. Remove all code from Mosca and replace the internals with Aedes, adding a CLI and an Authorizer.

**Comment by srmarjani** [comment]
And what about Name? we call it mosca yet?

**Comment by mcollina** [comment]
I would say so, Mosca is currently dead.

**Comment by robertsLando** [comment]
> I would say so, Mosca is currently dead.

Based on this. I suggest you to add a big title on mosca to redirect users to use aedes and set it as unmantained (block issues/pr)

**Comment by srmarjani** [comment]
I think I have time to do this tasks
I would add cli to base code and then we can decide about authorizer

**Comment by robertsLando** [comment]
@srmarjani based on what @mcollina said, I think you have to work on mosca not aedes, so you don't need to move cli code here but instead move aedes core in mosca

**Comment by srmarjani** [comment]
I think we can have another package like aedes-cli.
Adding cli to aedes code base make it heavy
for example fastify has below 
https://github.com/fastify/fastify-cli

**Comment by robertsLando** [comment]
I Upvote @srmarjani option, I think that Aedes should be keeped as slim as possible

**Comment by srmarjani** [comment]
@mcollina  and @robertsLando  I have three options based on my prefer
1. Add a new package called aedes-cli. That needs another repo so I could fork and work on it.
2. Add cli to current source code of aedes
3. Change the current Implementation of Mosca

**Comment by robertsLando** [comment]
@mcollina Could you start another repo called aedes-cli? I think this is the best option

**Comment by mcollina** [comment]
Can’t you?
Il 23 gen 2020, 14:01 +0100, Daniel Lando <notifications@github.com>, ha scritto:

**Comment by robertsLando** [comment]
DIdn't know I had permissions to create repos to the org. I think also @srmarjani can so.

If you agree @srmarjani could start the new repo `aedes-cli`

**Comment by srmarjani** [comment]
@mcollina @robertsLando I think it would not good everyone have right to add repo

**Comment by robertsLando** [comment]
@srmarjani Not everyone has, just us [maintainers team](https://github.com/orgs/moscajs/teams/maintainers)

**Comment by mcollina** [comment]
Done https://github.com/moscajs/aedes-cli

**Comment by robertsLando** [comment]
@mcollina Also consider this https://github.com/moscajs/mosca/pull/811

**Comment by robertsLando** [comment]
@srmarjani Any news ?
