### ISSUE TITLE
Purpose of running nextBatch() when Client is instantiated

### ISSUE THREAD

**Issue by gnought** [moscajs/aedes#363]
We are listening to `packet` event in mqtt parser in https://github.com/moscajs/aedes/blob/master/lib/client.js#L51, are there any purpose to run nextBatch() once we instantiate the Client object at https://github.com/moscajs/aedes/blob/master/lib/client.js#L86 ?
@mcollina

**Comment by robertsLando** [comment]
@gnought _parsingBatch is inited to 1 on purpose on client I think to trigger first protocolDecode?

**Comment by gnought** [comment]
The nextBatch has been there before the protocolDecode was merged into main branch.

**Comment by robertsLando** [comment]
@mcollina ?

**Comment by mcollina** [comment]
`nextBatch` responsibility is to feed chunks into the parser in a very fast way. We trigger it immediately because the first chunk we receive after opening a socket usually contains the CONNECT packet, so it's triggered immediately.

**Comment by robertsLando** [comment]
@gnought Can we close this so?

**Comment by gnought** [comment]
It is understand that we want to get chunks as fast as we could, but the data may not available in the stream. Don't we listen listen the `readable` event (in https://github.com/moscajs/aedes/blob/master/lib/client.js#L89) for that purpose?

**Comment by mcollina** [comment]
Yes, that should be good as well.

**Comment by robertsLando** [comment]
So that could be removed without losing speed, it is just uneccessary

Daniel
