### ISSUE TITLE
Topic matching: Single-level wildcard does not match empty level

### ISSUE THREAD

**Issue by ffa500** [moscajs/aedes#373]
I'm running aedes@0.40.1. My MQTT.JS v3.1.1 client subscribes to topic "a/+/c" but it doesn't receive publications on topic "a//c". Publishing on "a/b/c" is okay. Same issue with "a/+": matching against "a/" does not work, but "a/b" is fine.

Seems aedes is not supporting single-wildcard matching against empty levels. Mosca does not support it either. Yet, other brokers like mosquitto or HiveMQ support this case.

MQTT Spec v3.1.1 is not excluding this special case in its definition of the + wildcard:

"The single-level wildcard can be used at any level in the Topic Filter, including first and last levels. Where it is used it MUST occupy an entire level of the filter [MQTT-4.7.1-3]. It can be used at more than one level in the Topic Filter and can be used in conjunction with the multilevel wildcard."

It also states that  "Adjacent Topic level separators indicate a zero length topic level", so I assume empty levels are valid and should also match the + wildcard.

Thanks for taking a look at this issue!

**Comment by mcollina** [comment]
would you mind to send a PR to address this? Or at least point us in the right direction.
Il 26 gen 2020, 13:36 +0100, Hubertus Hohl <notifications@github.com>, ha scritto:

**Comment by gnought** [comment]
This relates to Qlobber used in our mqemitter.
Qlobber (https://github.com/davedoesdev/qlobber) states
> {String} wildcard_one The character to use for matching exactly one non-empty word in a topic. Defaults to '*'. MQTT uses '+', for example.

`wildcard_one` only matches non-empty words, there are 2 options.
1. submit a PR to Qlobber
2. or tweak mqemitter to add one match (e.g. a//c and a/)

@mcollina which one is preferred, or any good options?

**Comment by mcollina** [comment]
cc @davedoesdev what do you think?

**Comment by davedoesdev** [comment]
I'm happy to add an option to Qlobber to change the behaviour so `wildcard_one` matches empty word as well. Is that the cleanest solution for aedes?

**Comment by robertsLando** [comment]
@davedoesdev I think that would be good, or maybe simply add an option like `matchEmptyLevels` , to be sure that this doesn't break any existing instance. @mcollina What do you think it's best?

**Comment by mcollina** [comment]
+1 for a new option!
Il 29 gen 2020, 08:08 +0100, Daniel Lando <notifications@github.com>, ha scritto:

**Comment by davedoesdev** [comment]
`match_empty_levels` is available in qlobber 4.1.0. 
Pass it as `true` wherever you pass `wildcard_one`.

**Comment by robertsLando** [comment]
Isn’t qlobber 4+ only nodejs 12+ compatible?

Daniel

**Comment by davedoesdev** [comment]
Yes. What versions does mosca/aedes support?

**Comment by gnought** [comment]
@davedoesdev aedes now supports nodejs >=8, could we have the `match_empty_levels` option in v3.1.0 ?

**Comment by davedoesdev** [comment]
Let me take a look. I may be able to roll back to >= 8 even on qlobber v4.
Might be a few days that, hope that's OK.

**Comment by robertsLando** [comment]
@davedoesdev Yes that would be good.

**Comment by mcollina** [comment]
I’m happy to bump to drop 8.x instead of 10.x.
Il 31 gen 2020, 08:25 +0100, Daniel Lando <notifications@github.com>, ha scritto:

**Comment by gnought** [comment]
qlobber v4 requires at least nodejs>=12.

**Comment by davedoesdev** [comment]
It's OK, I'll try to put node >=8 support back in

**Comment by davedoesdev** [comment]
qlobber 4.2.0 supports Node >= 8. Worker thread and async support is only enabled on Node >= 12 but I don't think you use those features.

**Comment by gnought** [comment]
Thanks @davedoesdev 
@mcollina we need to bump mqemitter version when upgrading to qlobber v4.2.0, fine?

**Comment by mcollina** [comment]
Yes, thanks.
Il 1 feb 2020, 06:11 +0100, Gnought <notifications@github.com>, ha scritto:

**Comment by ffa500** [comment]
Thanks  @mcollina @gnought @davedoesdev @robertsLando for your awesome cooperation!
Cheers Hubertus

**Comment by robertsLando** [comment]
Sorry but it is not fixed yet, still having problems with latest qlobber versions

Daniel

**Comment by davedoesdev** [comment]
Please use qlobber v5.0.0

**Comment by robertsLando** [comment]
@davedoesdev Thanks! It has landed on mqemitter

**Comment by gnought** [comment]
We haven’t enabled the “match empty level” option yet.

**Comment by robertsLando** [comment]
You right! Could you submit that change to mqemitter?

Daniel

**Comment by gnought** [comment]
Yes, I have to. One more commit will be submitted to mqemitter to complete all changes

**Comment by robertsLando** [comment]
Reference to the pull request: https://github.com/mcollina/mqemitter/pull/18
