### ISSUE TITLE
Code Style about declaring anonymous function

### ISSUE THREAD

**Issue by gnought** [moscajs/aedes#382]
Which coding style do you prefer for anonymous functions?

Take an example:
`setTimeout(() => { console.log('times up') }, 1000)`
or
`setTimeout(function () { console.log('times up') }, 1000)`
or
`setTimeout(function log() { console.log('times up') }, 1000)`

**Comment by robertsLando** [comment]
+1 For first one

**Comment by gnought** [comment]
It is best we agree one of those to make it consistent in all our aedes codes.

**Comment by mcollina** [comment]
Two of those are different:

`setTimeout(() => { console.log('times up') }, 1000)` retains a reference of `this`. This might be wanted or not, and it has some memory consideration.

`setTimeout(function () { console.log('times up') }, 1000)` does _not_ retain a reference to `this`.

Given that they are not equal they have different meaning, I tend to use the two to tell the reader what I am doing.

Note that the _fastest_ version is the following:

```js
// this is used inside another function, multiple times
setTimeout(fn, 1000, a, b, c)

// This is top-level
function fn (a, b, c) { 
...
}
```

In tests, use whatever.

I'm pretty lazy in making things "consistent", as I hardly see any benefit of changing code for the sake of changing style.

**Comment by gnought** [comment]
@mcollina thanks for pointing out and your expertise. :)
I have tried
```
setTimeout(() => { console.log(this) }, 1000)
setTimeout(function () { console.log(this) }, 1000)
setTimeout(function log() { console.log(this) }, 1000)
```

only the first `setTimeout(() => { console.log(this) }, 1000)` haven't `this` reference. Does it mess something up?

**Comment by robertsLando** [comment]
> setTimeout(() => { console.log('times up') }, 1000) retains a reference of this. This might be wanted or not, and it has some memory consideration.

Didn't know about this :+1: 

So no generic code style but use the method that best fits the use case
