### ISSUE TITLE
clientError raised in DISCONNECT but not end()

### ISSUE THREAD

**Issue by gnought** [moscajs/aedes#396]
The following test works fine. What I found is, the `DISCONNECT` will be proceed later than the `PUBLISH hello`, so the `clientError` error is triggered.
```js
    subscriber.inStream.write({
        cmd: 'disconnect'
      })
```
If we replace with 
```js
    subscriber.inStream.end()
```
It works differently and plan number should be 4. The `end()` will immediately close subscriber connection and unsubscribe any topics. The subsequent `PUBLISH hello` will not publish to the subscriber. No `clientError` is there.

Test Code
```js
test('clientError raised when subscriber send DISCONNECT', function (t) {
  t.plan(6)

  const broker = aedes()
  t.tearDown(broker.close.bind(broker))

  var subscriber = connect(setup(broker), { clientId: 's1' })
  const expected = {
    cmd: 'publish',
    topic: 'hello',
    payload: Buffer.from('world'),
    qos: 1,
    dup: false,
    length: 14,
    retain: true
  }
  broker.on('clientError', function (client, err) {
    t.equal(client.id, 's1')
    t.equal(err.message, 'connection closed')
  })
  subscribe(t, subscriber, 'hello', 1, function () {
    subscriber.inStream.write({
      cmd: 'disconnect'
    })

    subscriber.outStream.on('data', function (packet) {
      t.fail('should not receive any data')
    })

    const publisher = connect(setup(broker))

    publisher.inStream.write({
      cmd: 'publish',
      topic: 'hello',
      payload: 'world',
      qos: 1,
      messageId: 42,
      retain: true
    })

    publisher.outStream.once('data', function (packet) {
      t.equal(packet.cmd, 'puback')
    })
  })
})
```

**Comment by gnought** [comment]
The `DISCONNECT` will close the underlying connection but it is in mqtt message queue. It calls same `end()`.

**Comment by robertsLando** [comment]
@gnought It should work in the same way as there is the `eos` setup on `client.conn` :confused:

**Comment by robertsLando** [comment]
@mcollina

**Comment by mcollina** [comment]
I don't understand the question

**Comment by gnought** [comment]
I think it relates the event loop.

`disconnect` -> `conn.end()` -> end event trigger and subscriber closes

1. publisher PUBLISH
2. publisher receives PUBACK
3. broker PUBLISH
4. broker mqemitter deliverQoS
5. trigger `connection closed` as subscriber conn end


`end()` > subscriber closes

1. publisher PUBLISH
2. publisher receives PUBACK
3. broker PUBLISH
4. <Here we will miss mqemitter deliverQoS, as the subscription is removed when subscriber closed, then no `connection closed` is raised>
