### ISSUE TITLE
Release script

### ISSUE THREAD

**Issue by robertsLando** [moscajs/aedes#397]
@mcollina Would you like me to setup a release script like the one used in protocol-decoder? (using release-it)

**Comment by mcollina** [comment]
I'd prefer to keep using my current stack for now
Il 4 feb 2020, 14:37 +0100, Daniel Lando <notifications@github.com>, ha scritto:

**Comment by gnought** [comment]
@mcollina would you mind to share what your current stack is?

**Comment by mcollina** [comment]
I do them manually or by using http://npm.im/releasify
