### ISSUE TITLE
About protocol decoder

### ISSUE THREAD

**Issue by gnought** [moscajs/aedes#398]
Sorry a bit late to look into the aedes protocol decoder. It seems that it is doing several things:
- support proxy protocol v1 and v2, and extract the actual payload to aedes
- extract out partial connection details under client object root when it is a websocket / proxy.

IMO, it is not good to create a hook for decoding data. Hooks in aedes mainly are on mqtt flow, but protocol decoder is related on socket.
Also connDetails is a bit ugly, I think we could have a new class say AedesConnection for that purpose.

**Comment by robertsLando** [comment]
Why it is not a good idea to create an hook for data decoding? How could a user do the same thing as protocol decoder does without using it? About connDetails I’m +1 for that.

I don’t understand the solutions you have in mind when you say that it isn’t good 

Daniel

**Comment by robertsLando** [comment]
@gnought

**Comment by gnought** [comment]
What i understand is we need to keep aedes simple.

aedes accepts raw socket that dealing with raw mqtt traffic, we could let developers to parse any wrapped protocol like PROXY before feeding into aedes. The following is an example.

```js
const proxyProtocol = require('proxy-protocol-js')
const mqttPacket = require('mqtt-packet')
const net = require('net')

const aedes = require('aedes')()

const clientIp = '192.168.0.140'
const clientPort = 12345
const packet = {
  cmd: 'connect',
  protocolId: 'MQIsdp',
  protocolVersion: 3,
  clean: true,
  clientId: 'my-client-proxyV2'
}
const protocol = new proxyProtocol.V2ProxyProtocol(
  proxyProtocol.Command.LOCAL,
  proxyProtocol.TransportProtocol.DGRAM,
  new proxyProtocol.IPv4ProxyAddress(
    proxyProtocol.IPv4Address.createFrom(clientIp.split('.')),
    clientPort,
    proxyProtocol.IPv4Address.createFrom([127, 0, 0, 1]),
    4883
  ),
  mqttPacket.generate(packet)
).build()

const port = 1883
const server = net.createServer(aedes.handle)
server.listen(port, function (err) {
  t.error(err, 'no error')
})
const proxy = require('proxyproto').createServer(server);
proxy.on('error', function (err) {
  console.log(err)
})
const client = net.connect({
  port,
  timeout: 0
}, function () {
  client.write(Buffer.from(protocol))
})

aedes.on('clientReady', function (client) {
  console.log(client.conn.remoteAddress)  // matched to clientIp
  console.log(client.conn.remotePort)  // matched to clientPort
})
```

**Comment by robertsLando** [comment]
@gnought This could be an alternative but what I don't understand is how can aedes-protocol-decoder add complexity to aedes? It has been splitted out from it, if someone don't use it aedes is still simple

**Comment by gnought** [comment]
if this is the case, we need to consider decoding HTTP, HTTPS, socks proxy, other tunnelling protocols. 
`connDetails` is a overhead. I prefer they will modify socket properties

**Comment by robertsLando** [comment]
I understand what you mean but in that case someone if interested could develop its own custom plugin starting from protocol decoder to support a different protocol, about the overhead is there any performance gain to use your method instead of aedes-protocol decoder or any other custom protocol decoder in the way it works now?

**Comment by gnought** [comment]
the protocol decoder is not an interface, its current behaviour is parsing websocket / PROXY and injects some connection details in `connDetails`. You wanna let developers to build their plugins on top of that behaviour?

**Comment by robertsLando** [comment]
@gnought Why not?

**Comment by robertsLando** [comment]
This could be closed with the introduction of aedes-server-factory
