### ISSUE TITLE
use ws instead of websocket-stream

### ISSUE THREAD

**Issue by mcollina** [moscajs/aedes#405]
ws now includes a stream wrapper.

**Comment by robertsLando** [comment]
Do you mean this: https://github.com/websockets/ws#use-the-nodejs-streams-api?

**Comment by mcollina** [comment]
yes

Il giorno gio 6 feb 2020 alle ore 11:39 Daniel Lando <
notifications@github.com> ha scritto:

**Comment by robertsLando** [comment]
@mcollina Why? What are the benefits?

**Comment by mcollina** [comment]
websocket-stream is almost unmaintained
Il 6 feb 2020, 14:07 +0100, Daniel Lando <notifications@github.com>, ha scritto:

**Comment by bhirave** [comment]
@robertsLando do you have example on how to use 'ws' package with aedes ?

**Comment by robertsLando** [comment]
@bhirave https://github.com/moscajs/aedes-cli/blob/master/lib/cli.js#L236

**Comment by robertsLando** [comment]
Fixed by introducing aedes-server-factory
