### ISSUE TITLE
[question] Error catch in checkAndPublish

### ISSUE THREAD

**Issue by robertsLando** [moscajs/aedes#422]
Where does this err is catched? https://github.com/moscajs/aedes/blob/master/aedes.js#L114

@gnought

**Comment by robertsLando** [comment]
Seems that it is not possbile to write tests for this lines of code:

https://github.com/moscajs/aedes/blob/master/aedes.js#L114
https://github.com/moscajs/aedes/blob/master/aedes.js#L123

Those lines can never be reached as persistence makes this test in streamWill: https://github.com/moscajs/aedes-persistence-mongodb/blob/master/persistence.js#L629

**Comment by gnought** [comment]
For https://github.com/moscajs/aedes/blob/master/aedes.js#L114,
the `err` comes from `aedes.publish`

**Comment by robertsLando** [comment]
@gnought Yes but where does that error goes? I mean how can you catch it?

**Comment by robertsLando** [comment]
@mcollina

**Comment by mcollina** [comment]
Currently that error will result in an uncaughtexception. It will be emitted by the stream. I recommend to use pump or pipeline and forward that error to the aedes instance.

**Comment by robertsLando** [comment]
@mcollina pump is no more a project, I suggest to use pipeline instead

**Comment by robertsLando** [comment]
@mcollina done
