### ISSUE TITLE
[bug] Catch mqtt-packet parser errors

### ISSUE THREAD

**Issue by robertsLando** [moscajs/aedes#428]
@mcollina Actually we don't catch mqtt-pacekt parser errors. I have tried to create a test sending wrong cmd to the inStream and mqtt-packet throws an error `Unknown command` that is not catched even if I add [here](https://github.com/moscajs/aedes/blob/master/lib/client.js#L55)

```js
  this._parser.on('error', onError)
```

on client.js.

**Comment by mcollina** [comment]
That’s ok and it should destroy the connection
Il 12 feb 2020, 11:37 +0100, Daniel Lando <notifications@github.com>, ha scritto:

**Comment by robertsLando** [comment]
@mcollina It's not ok, it doesn't catch the error

**Comment by mcollina** [comment]
So the error is not emitted? Can you upload a test to reproduce?

**Comment by robertsLando** [comment]
@mcollina 

```js
test('catch error mqtt-packet parse error', function (t) {
  t.plan(1)

  const s = noError(connect(setup()), t)
  t.tearDown(s.broker.close.bind(s.broker))

  s.broker.on('clientError', function () {
    t.pass('error thrown')
  })

  s.broker.on('clientReady', function (c) {
    s.inStream.write({ cmd: 'pippo' })
  })
})
```

**Comment by robertsLando** [comment]
Here: https://github.com/moscajs/aedes/runs/440829422#step:6:384

**Comment by mcollina** [comment]
That error is thrown by the test harness when it generates a packet and not by Aedes.
