### ISSUE TITLE
[feat] Option to allow longer client IDs for v3.1.0

### ISSUE THREAD

**Issue by jdiamond** [moscajs/aedes#434]
**Is your feature request related to a problem? Please describe.**

Starting in 0.40.0, Aedes is now strictly following the MQTT v3.1.0 spec which limits client IDs to 23 characters. Unfortunately, my company has thousands of devices connecting to our Aedes-based broker using MQTT v3.1.0 with client IDs longer than 23 characters. Aedes previously didn't enforce that and neither did libmosquitto so we didn't know we were violating the spec. I started testing our devices against our broker with an upgraded Aedes but it's now responding with the "identifier rejected" error so they can't connect anymore.

**Describe the solution you'd like**

Can I submit a PR for an option that allows this limit to be increased? I think the default for v3.1.0 should still be 23 characters and users should have to go out of their way to enable non-standard behavior.

I found this link showing that HiveMQ has a similar option:

https://www.hivemq.com/blog/supporting-mqtt-client-identifiers-23-characters/

**Describe alternatives you've considered**

I think the best solution would be for us to update libmosquitto on our devices to a version that supports v3.1.1 where the spec says it's OK to have client IDs longer than 23 characters, but that's out of my control here and seems unlikely. 😢

**Comment by mcollina** [comment]
I'm happy to add an option for that!
Il 19 feb 2020, 13:33 -0700, Jason Diamond <notifications@github.com>, ha scritto:

**Comment by gnought** [comment]
i'm +1 for adding the non-standard option.

**Comment by robertsLando** [comment]
+1 

Daniel

**Comment by jdiamond** [comment]
I was planning on working on a PR this weekend but I see you beat me to it. Thanks so much!
