### ISSUE TITLE
[bug]pm2 cluster start，aedes unable to publish message 

### ISSUE THREAD

**Issue by luyufa** [moscajs/aedes#436]
**System Information**
- Aedes: 0.40.1
- NodeJS: 8.11.4
- OS: centos

**Describe the bug**
pm2 cluster start，aedes unable to publish message。
No errors，but  client cannot accept message。

**To Reproduce**
```
  app.publish({ topic,payload,qos: 2}, function (err) {
                            console.log(`send success to ${toTopic}`);
                            err && console.error('err', err);
    });
```

**Comment by gnought** [comment]
@luyufa same result in pm2 fork mode?

**Comment by robertsLando** [comment]
@luyufa Could you provide the entire script or an example to reproduce the problem?

**Comment by luyufa** [comment]
> @luyufa Could you provide the entire script or an example to reproduce the problem?
@robertsLando this is pm2 applicatio json ，thanks
```
{
  "apps": [
    {
      "name": "app.im",
      "script": "app.js",
      "env": {
        "NODE_ENV": "production"
      },
      "out_file": "./logs/out.log",
      "error_file": "./logs/err.log",
      "log_date_format": "YYYY-MM-DD HH:mm:ss",
      "exec_mode": "cluster",
      "instances": "max",
      "merge_logs": true
    }
  ]
}
```

**Comment by luyufa** [comment]
@gnought pm2 fork mode not support `Load balancing` and `Port complex` so... i prefer to cluster mode

**Comment by gnought** [comment]
@luyufa thanks for the input, but it is good to have a test if it works in fork mode.

**Comment by luyufa** [comment]
@gnought  emm...  It only works in cluster mode.

**Comment by gnought** [comment]
@luyufa we wanna bypass if it is pm2 cluster issue, could you make some code adjustment?

**Comment by luyufa** [comment]
@gnought no problem , let me try.  thank you for your reply

**Comment by robertsLando** [comment]
@luyufa In order to use aedes with clusters you shouls use a mqemitter that supports clusters like `mqemitter-redis` and also a persistence that is not in-memory but on disk

**Comment by luyufa** [comment]
@robertsLando  nobody's fault but mine. I didn't use `mqemitter-redis`causing it to not work. 
now , it' works fine. thank you I really appreciate your help.
