### ISSUE TITLE
H5 MQTT client connects aedes

### ISSUE THREAD

**Issue by weiliudong** [moscajs/aedes#438]
I use the web-mqtt-client.js, mqtt.js, mqttws31.min.js and other plugins to create a client to connect to the aedes server on the H5 front end, but it always shows

```
 WebSocket connection to 'ws: //xx.xx.xx.xx" : 3000 / mqtt 'failed: Connection closed before receiving a handshake response 
```

Why is this? Does aedes not support H5 front-end clients? Can anyone help me?

`<script src="js/mqttws31.min.js" type="text/javascript"></script>`

**Comment by robertsLando** [comment]
@weiliudong  I'm using javascript Paho mqtt library for connections over websockets and I never had probelms with aedes. Please provide the script you use to init the connection
