### ISSUE TITLE
[bug]Unsubscribe crush while import mq & persistence at the same time.

### ISSUE THREAD

**Issue by seeLuck** [moscajs/aedes#451]
Client unsubscribe will crush while using mq & persistence at the same time.
Complete sample is below:

server
```
const redisStore = require("mqemitter-redis")
const aedesPersistenceRedis = require("aedes-persistence-redis")
let mqStore = redisStore({
    host: '127.0.0.1'
});
let persistStore = aedesPersistenceRedis({
    host: '127.0.0.1'
});

const aedes = require('aedes')({
    mq: mqStore,
    persistence: persistStore,
});
const server = require('net').createServer(aedes.handle)
const port = 1883

server.listen(port, function () {
    console.log('server started and listening on port ', port)
})
```

client
```
const mqtt = require('mqtt')
let client  = mqtt.connect({
    servers: [{
        host: 'localhost',
        port: 1883,
        protocol: 'tcp'
    }]
});

client.on('connect', function () {
    client.subscribe('presence', function (err) {
        if (!err) {
            client.unsubscribe('presence', (err)=>{
                if(err)
                    console.log(err);
                else
                    console.log('suc');
            })
        }
    })
});
```

**Comment by robertsLando** [comment]
@seeLuck Could you also provide console log output please?

**Comment by seeLuck** [comment]
> @seeLuck Could you also provide console log output please?
> 
> I have run your code and it is working on my machine. Are you sure redis is correctly installed and running on your machine?

I deployed the server code online, you can try it by
```
mqtt.connect({
    servers: [{
        host: '49.234.41.166',
        port: 1883,
        protocol: 'tcp'
    }]
});
```
On server side catch no error. Client side catch unsubscribe error `Error: Connection closed`

And port 1884 works fine with delete this single line `mq: mqStore`

environment:
```
system
centos 7
redis 3.2.12
node 10.16.0

package.json
    "aedes": "0.40.1",
    "aedes-persistence-redis": "6.0.1",
    "mqemitter-redis": "4.0.0",
    "mqtt": "3.0.0",
```

**Comment by robertsLando** [comment]
@seeLuck Maybe it is something related to you redis server settings? Check also redis logs when client connects

**Comment by seeLuck** [comment]
@robertsLando
I tried several redis server and machine, same result :(

@gnought
@mcollina
Is this a real bug or sth I miss in settings?

**Comment by gnought** [comment]
The following is my extended test on top of your sample.
Test cases:
1. Tried to use 1 redis instance => reproducable
2. Tried to use 2 redis instances with different ports => reproducable
3. only use `aedes-persistence-redis`, and left mq be `mqemitter` => fine
4. only use `mqemitter-redis`, and left persistence be `aedes-persistence` => fine

aedes raises `clientError` and the `error` is `1`, very strange to me. Haven't work much on `mqemitter-redis` and `aedes-persistence-redis`, we need some times to do an investigation.

@robertsLando woud you mind to check if any errors using the following test in your side? I create the redis instances by `redis-server` and `redis-server --port 6380`

```js
const mqtt = require('mqtt')
const redisStore = require('mqemitter-redis')
const aedesPersistenceRedis = require('aedes-persistence-redis')

const mqStore = redisStore({
  host: '127.0.0.1',
  port: 6379
})
const persistStore = aedesPersistenceRedis({
  host: '127.0.0.1',
  port: 6380
})

const aedes = require('aedes')({
  mq: mqStore,
  persistence: persistStore
})
aedes.on('clientError', function (client, error) {
  console.log(error)
})

const server = require('net').createServer(aedes.handle)
const port = 1883

server.listen(port, function () {
  console.log('server started and listening on port ', port)

  const client = mqtt.connect({
    servers: [{
      host: 'localhost',
      port: 1883,
      protocol: 'tcp'
    }]
  })

  client.on('error', function (error) {
    console.log('mqtt client error')
  })
  client.on('connect', function () {
    client.subscribe('presence', function (err) {
      if (!err) {
        client.unsubscribe('presence', (err) => {
          if (err) { console.log(err) } else { console.log('suc') }
        })
      }
    })
  })
})
```

**Comment by robertsLando** [comment]
I'm working on aedes-persistence-redis and I see that it is not compatible with lates mqemitter-redis. Just use mqemitter-redis version 3.0.0 for now. I'm getting that error too and seems that it comes from mqemitter-redis after broker publish in aedes-cached-persistence: https://github.com/moscajs/aedes-cached-persistence/blob/master/index.js#L103

And that is strange because mqemitter shouldn't return nothing

**Comment by mcollina** [comment]
I think this project needs some integration tests to move at the speed we are now pushing it.
Il 26 feb 2020, 08:11 +0100, Daniel Lando <notifications@github.com>, ha scritto:

**Comment by robertsLando** [comment]
@mcollina we need to release new version of aedes-persistence to npm in order to fix some things. Can I do it? Major or minor? We have dropped nodejs 8

**Comment by mcollina** [comment]
major
Il 26 feb 2020, 09:19 +0100, Daniel Lando <notifications@github.com>, ha scritto:

**Comment by robertsLando** [comment]
Ok I do it now

**Comment by gnought** [comment]
For this issue, 
the client is in clean session, when do a subscribe, we won't save the subscription in persistence, but in we call remove subscription in persistence while in unsubscribe. https://github.com/moscajs/aedes/blob/209efd018ab8645f061aed50c0dacf279bb51e6b/lib/handlers/unsubscribe.js#L24-L34

**Comment by gnought** [comment]
the error is trigger by L27

**Comment by robertsLando** [comment]
@gnought Good catch! Are you working on a fix? I think adding `&& !client.clean`  to the if should be enought

**Comment by gnought** [comment]
@robertsLando i will.

**Comment by gnought** [comment]
@robertsLando where do you see I submit a PR, you will see there may be more upcoming changes. I try to split a PR into as small as possible.

**Comment by robertsLando** [comment]
@seeLuck Try to use latest version of mqemitter-redis and `aedes-persistence-redis` to check if this is working now
