### ISSUE TITLE
[bug] Duplicated subscriptions in persistence

### ISSUE THREAD

**Issue by qbcbyb** [moscajs/aedes#458]
In my code, when I set QoS to 1 when subscribing to multiple topics at one time, multiple redundant records will be generated in the `Persistence`. By looking at the source code, I think it's the problem here [addSubscriptions(client, packet.subscriptions, ...](https://github.com/moscajs/aedes/blob/76cdd8e10493946b33a286d127154416fd2dd59e/lib/handlers/subscribe.js#L106). I think `packet.subscription` should be replaced by `[sub]`.  Please help to confirm.

**Comment by robertsLando** [comment]
@qbcbyb Could you proivide a code to replicate this?

**Comment by gnought** [comment]
@qbcbyb which persistence are you using?

**Comment by gnought** [comment]
@qbcbyb I do a quick test using `aedes-persistence`, but I cannot reproduce the issue you mentioned.

```js
test('subscribe QoS 1 multipe topics [clean=false]', function (t) {
  t.plan(5)

  const s = connect(setup(), { clean: false })
  t.tearDown(s.broker.close.bind(s.broker))

  const expected = {
    cmd: 'publish',
    topic: 'hello',
    payload: Buffer.from('world'),
    dup: false,
    length: 12,
    qos: 0,
    retain: false
  }
  const subs = [{ topic: 'hello', qos: 1 }, { topic: 'world', qos: 1 }]

  subscribeMultiple(t, s, subs, [1, 1], function () {
    s.outStream.on('data', function (packet) {
      t.deepEqual(packet, expected, 'packet matches')
    })

    s.broker.persistence.subscriptionsByClient(s.client, function (_, saveSubs) {
      t.deepEqual(saveSubs, subs)
    })

    s.broker.publish({
      cmd: 'publish',
      topic: 'hello',
      payload: 'world'
    })
  })
})
```

**Comment by robertsLando** [comment]
I think he is doing something wrong @gnought, not really a bug. Also I asked him for more info 13 days ago and still no response. I close this for now, will reopen when and if he will ping
