### ISSUE TITLE
[question] use exposed aedes-packet from persistence

### ISSUE THREAD

**Issue by gnought** [moscajs/aedes#459]
@robertsLando I have checked the source, we import aedes-packet from serveral places in the core.
1. lib/client.js
2. lib/qos-packet.js
3. lib/handlers/subscribe.js
4. aedes.js

It is easy to use Packet from persistence in point 4, but to keep consistency, i think we're better to use aedes-packet directly to adapt point 1 to 3.

**Comment by robertsLando** [comment]
>  but to keep consistency

What you mean? I think that there could be less consistency in doing this than use the one from persistence. If you use aedes-packet somewhere and aedes-persistence.packet elsewhere there could be much less consistency IMHO

**Comment by gnought** [comment]
Sorry for my unclear wordings.

How I could refer `Packet` from aedes-persistence in these 3 lines then?

https://github.com/moscajs/aedes/blob/f68cd771222aa974969039b750b04954b6968cea/lib/client.js#L8
https://github.com/moscajs/aedes/blob/f68cd771222aa974969039b750b04954b6968cea/lib/handlers/subscribe.js#L4
https://github.com/moscajs/aedes/blob/f68cd771222aa974969039b750b04954b6968cea/lib/qos-packet.js#L3

**Comment by robertsLando** [comment]
```js
const { Packet } = require('aedes-persistence') 
```

**Comment by gnought** [comment]
Yes, that’s my point, it looks weird. Those 3 files does not directly relate to persistence object, it makes confusion.

**Comment by robertsLando** [comment]
@gnought Alternative to this? I think that use aedes-packet somewhere and use aedes-persistence packet elsewhere is for sure more weird then this. We could add 

```js
module.export.Packet = Packet
```

In aedes.js and then import packet elsewhere like

```js
const { Packet } = require('../aedes.js')
```

**Comment by gnought** [comment]
Exporting `Packet` from `aedes-persistence` and `aedes-cached-persistence` does make sense, as either is a base class of other persistence libraries, like `aedes-persistence-redis`. Any persistence based on that should use the exported Packet rather than explicitly import `aedes-packet`.

However, I'm better not to export `aedes-packet` from aedes core, it is useless and just for one purpose to refer it across files. 
We seldom change `aedes-packet` unless we support mqtt 5. IMO keeping `aedes-packet` sounds like a better idea unless there's a better way to refer Packet across files.

**Comment by robertsLando** [comment]
@gnought Ok, so keep it as dep in aedes, no problem for me
