### ISSUE TITLE
[question]How to turnoff the Broker in Node-Red

### ISSUE THREAD

**Issue by VoLinhTruc** [moscajs/aedes#465]
I've already delete the Aedes Node but the broker still run and the MQTT in and out node still connecting to the broker.
![image](https://user-images.githubusercontent.com/26188668/78467004-700a1300-7732-11ea-87f2-9a9bf8d434ba.png)

How to turnoff/disable the Aedes broker ???

**Comment by robertsLando** [comment]
Aedes node uses an aedes client that is a configuration node that is not shown in editor. Open the menu by click in the top right corner, select configuration nodes and find the aedes broker configuration node, then press on it and delete it. 

Alternatively you can add a new aedes node and in the broker select option you can access the broker configuration and delete it.

To fix this you should open a PR on aedes node not there. He needs to keep track of nodes using its broker and if no one don’t init it. 

Daniel
