### ISSUE TITLE
[bug]subscribe Event will triggered while topic is negated.

### ISSUE THREAD

**Issue by seeLuck** [moscajs/aedes#467]
**System Information**
- Aedes: 0.41.0
- NodeJS: 10.15.3
- OS: Centos 7

**Describe the bug**
Subscribe Event will triggered while topic is negated.

**To Reproduce**
```
//server.js
const aedes = require('aedes')();

aedes.authorizeSubscribe = function (client, sub, callback) {
    if (sub.topic === 'presence') {
        sub = null
    }
    callback(null, sub)
}

aedes.on("subscribe", (subs, client)=>{
    console.log(`subscribe event`, subs) // triggered
})


const server = require('net').createServer(aedes.handle)
const port = 1883

server.listen(port, function () {
    console.log('server started and listening on port ', port)
})
```

```
//client.js
const mqtt = require('mqtt')
let client  = mqtt.connect({
    servers: [{
        host: 'localhost',
        port: 1883,
        protocol: 'tcp'
    }]
});

client.on('connect', function () {
    client.subscribe('presence', function (err, granted) {
        if (!err) {
            console.log(granted) //[ { topic: 'presence', qos: 128 } ]
        }else
            console.log(err)
    })
});
```

**Comment by robertsLando** [comment]
It's not a bug, the callback should return an error: 

```js
aedes.authorizeSubscribe = function (client, sub, callback) {
   var err = null
    if (sub.topic === 'presence') {
        sub = null
        err = Error('Not authorized')
    }
    callback(err, sub)
}
```

**Comment by seeLuck** [comment]
According to the part of doc: [authorizesubscribe](https://github.com/moscajs/aedes/blob/master/docs/Aedes.md#handler-authorizesubscribe-client-subscription-callback), negate a subscription should be: ```To negate a subscription, set the subscription to null```
```
aedes.authorizeSubscribe = function (client, sub, callback) {
  // prohibited to subscribe 'aaaa' and suppress error
  callback(null, sub.topic === 'aaaa' ? null : sub)
}
```

However, if the callback return an error, the mqtt connection would be closed directly. I thought this case isn't reasonable to just negate a subscription.

@robertsLando 
@gnought

**Comment by robertsLando** [comment]
@seeLuck You right there is somethng wrong here. The code seems ok, need to dig into this

**Comment by gnought** [comment]
When negate a subscription, based on mqtt spec we have set the qos=128 in suback, and ignored by aedes.
In our current implementation, we still emit original user subscription in `subscribe` event, what do you want to be:
1. emit `subscribe` event **not** include qos!=128 subscriptions?
2. emit `subscribe` event include  all user subscriptions but change those negated qos to 128?

or other suggestions?
@seeLuck

**Comment by robertsLando** [comment]
IMHO I think that a user in broker 'subscribe' event expects the result of a subscribe not the subscribe request, or we should provide both original request and result

**Comment by seeLuck** [comment]
Yes, in my first idea, `subscribe` event should be the `succeed` subscribe result of clients' request. 

In current implementation, the result includes all succeed and negated subs, I think it is reasonable as well.

But in this case, a way like `change those negated qos to 128` is essential to distinguish between succeed and negated subs in broker `subscribe` event.
