### ISSUE TITLE
subscribe/unsubscribe processed out of order when persistence is used

### ISSUE THREAD

**Issue by aquark** [moscajs/aedes#469]
When a client subscribes and unsubscribes repeatedly to the same topic in quick succession, sometimes these are processed out of order, resulting in the client believing it has subscribed but it is actually not subscribed.

It looks like the root cause is that the subscribe handler may [complete synchronously](https://github.com/moscajs/aedes/blob/295538898deaa57edcd6f62c469a55dd02a3a58c/lib/handlers/subscribe.js#L104) but the unsubscribe handler always [completes asynchronously](https://github.com/moscajs/aedes/blob/295538898deaa57edcd6f62c469a55dd02a3a58c/lib/handlers/unsubscribe.js#L30), so it's possible for the unsubscription to complete after the subscription.

As a workaround, I have implemented a modified persistence which synchronously completes the unsubscribe call when the client is "clean".

**Comment by robertsLando** [comment]
Are you using mongodb as persistence? 

——————

Daniel - Software Engineer

Support me at:
    Github sponsors

**Comment by aquark** [comment]
No, leveldb. It shouldn't matter which persistence is used, as long as it's asynchronous, because the persistence isn't even called when subscribing.

**Comment by robertsLando** [comment]
@mcollina @gnought

**Comment by mcollina** [comment]
I have a feeling this is specific to leveldb. Could you replicate this with Redis or Mongodb?

Overall this highlight a problem in Aedes, which is that we are not pausing the processing of messages while we handle subscribes and unsubscribes.

I'm not sure we want to, I'm just noting that this would be the only way to prevent that.

**Comment by aquark** [comment]
I don't have redis or mongodb set up to replicate this. Could you look at the code links I provided pointing to the aedes source? The problem seems to be pretty straightforward, and doesn't depend on the persistence layer: aedes processes unsubscriptions asynchronously and subscriptions synchronously, therefore a subscribe received immediately after an unsubscribe will always be lost.

It is easy to reproduce this issue with a client that subscribes to a topic, waits for the suback, publishes on a topic, waits to receive the value, and then unsubscribes, in a loop. In my tests, it will end up missing the published value consistently after only a few iterations. Unfortunately sharing my test code would be pointless because it's using a proprietary mqtt client.

I initially thought it was a problem with leveldb reordering writes. However I wrote a wrapper around aedes-persistence-level which queues  subscription changes so it doesn't persist the unsubscribe until the subscribe is complete. However that didn't fix the issue, and that's when I discovered that the persistence isn't even called when aedes is processing the subscribe. 

I don't see why aedes needs to pause processing messages. At a minimum, it just needs to ensure that either both subscriptions and unsubscriptions are committed after they are persisted, or before, but not a mix of before and after. Ideally, aedes would also queue subscribes and unsubscribes from the same client to ensure that the persistence layer processes them in order, but this is unnecessary for persistence implementations that already guarantee [monotonic writes](http://jepsen.io/consistency/models/monotonic-writes) (unclear if any of aedes's do this).

**Comment by robertsLando** [comment]
> it just needs to ensure that either both subscriptions and unsubscriptions are committed after they are persisted

It already works like that

> but this is unnecessary for persistence implementations that already guarantee monotonic writes

Both redis and mongo provides this (depends if you are using clusters it becomes a little bit more complicated) that's why we asked if you could replicate this with those persistences

**Comment by aquark** [comment]
Look at this function: https://github.com/moscajs/aedes/blob/295538898deaa57edcd6f62c469a55dd02a3a58c/lib/handlers/unsubscribe.js#L17

Note that it calls the persistence even when clean is true. However the subscribe does not call the persistence when clean is true. This creates an asymmetry where an unsubscribe which happens before a subscribe can be applied after it.

**Comment by aquark** [comment]
This refusal to spend 1 minute to look at your own source code is really undermining my confidence in this project. :(

**Comment by robertsLando** [comment]
@aquark Sorry but I'm working on this project on my free time and this is the same for others, we are looking for contributors and the author of the project @mcollina can only review PRs

Actually I don't think there are other MQTT brokers for nodejs as Mosca has been archived in favor of this one

Looking at what you have pointed out, what solution do you suggest? Are you able to work on a PR to fix this? A monkey path of this could be to always store subscriptions so also that will be async, even if this doesn't respect MQTT specs, pausing messages while doing subscribe I think would kill performances

**Comment by aquark** [comment]
The workaround I implemented was to make unsubscribe behave similarly to subscribe: it skips the call to persistence when the session is "clean".

https://github.com/moscajs/aedes/pull/486

From my cursory reading of the spec and code, this seems safe, since a clean session should not have any persisted subscriptions anyways. However I'm not deeply familiar with mqtt or aedes to be confident that there isn't some edge case where the persistence needs to know the client unsubscribed to a topic even for a "clean" session.
