### ISSUE TITLE
Subscribing to all topics [bug]

### ISSUE THREAD

**Issue by craigharman** [moscajs/aedes#475]
**System Information**
- Aedes: 0.40.1
- NodeJS: 12.16.1
- OS: OS X 10.5.4
- Arch: x86_64

**Describe the bug**
Trying to subscribe to all topics via

```
mqtt.subscribe('#', function(err) {
        if (!err) {
          console.log('subscribe');
        }
      });
```

However I don't get any subsequent data from the broker. If I change '#' to "+/#' it works. Changing to another broker (eg. mqtt://test.mosquitto.org) allows subscription via #

**To Reproduce**
1. Create an AEDES broker:
const aedes = require('aedes')()

2. Connect (I am using mqtt.js) and subscribe to #
3. Publish something to a topic eg. /test
4. Nothing comes through to the client
5. Change topic to +/#
6. Publish something to /test
7. Client receives data

**Expected behavior**
Should be able to subscribe to all topics via # and receive any data posted to the broker.

**Comment by robertsLando** [comment]
@craigharman I'm not able to reproduce your bug. Please could you send a working code that replicate it?

**Comment by robertsLando** [comment]
If you are using redis I have just found and fix this bug: https://github.com/mcollina/mqemitter-redis/pull/27

**Comment by craigharman** [comment]
Thank you, that fixed the issue!
