### ISSUE TITLE
[question] - Persistence

### ISSUE THREAD

**Issue by Rafamedeiros0** [moscajs/aedes#480]
Hello!!
I'm sorry, I'm a beginner. I'm studying aedes and mosca !!
I managed to make aedes work, but I still don't understand the issue of persistence. It seems that it is specific broker for nodejs.

Could someone explain to me or indicate where I can find more information? I don't know if this is the best place, but I did a lot of research in the last week, but I couldn't answer my questions.

**Comment by robertsLando** [comment]
What you mean with "the issue of the persistence"?

If you mean why the persistence is needed: It is used to store subscriptions and QoS > 1 packets.

**Comment by Rafamedeiros0** [comment]
Sorry for the delay. I understood my question and now it doesn't make much sense. 

Thank for your time. I will study little more before the next questions. =D
