### ISSUE TITLE
how to implement offline messages with out using any database? 

### ISSUE THREAD

**Issue by VarshneyNaupada** [moscajs/aedes#491]
I would like to know the client,broker and publisher mechanism to implement offline messages. If Publisher sends messages and client is not connected still old messages on that particular topic should be also processed from client side with out using any database to store offline messages. ?

**Comment by robertsLando** [comment]
@VarshneyNaupada by default all messages are stored in memory, this means that there is not an on disk database and if the process stops all messages are lost
