### ISSUE TITLE
[question] Understanding authorizePublish

### ISSUE THREAD

**Issue by matteodisabatino** [moscajs/aedes#494]
I've created an Aedes server with this configuration:

```javascript
const aedes = Aedes(aedesOptions)
aedes.authorizePublish = (client, packet, callback) => {
  const deviceId = client.id
  const { nodeId, projectId } = client.authenticationData
  if (packet.topic !== `/project/${projectId}/device/${deviceId}/uplink`) {
    return callback(new Error('Cannot publish to this topic'))
  }

  callback(null)
}
```

I'm trying to testing this function with a client configured like so:

```javascript
const client = await new Promise((resolve, reject) => {
  const client = MQTT.connect('mqtt://127.0.0.1:1338', {
    clientId: OKNodeId,
    username: OKNodeId,
    password: OKProjectId
  })

  client.on('connect', () => resolve(client))
  client.on('error', reject)
})

await new Promise((resolve, reject) => {
  client.publish(`/project/${OKProjectId}/device/${wrongDeviceId}/uplink`, 'test message', { qos: 1 }, error => {
    if (error) {
      return reject(error)
    }

    resolve()
  })
})
```

And I've got these problems:

1. If I don't explicitly set qos=1 on publish, the server never calls the function authorizePublish. Is this the correct behavior?
2. With qos=1 the server calls the function but I get a strange behavior: the client tries to publish a wrong topic and the server rejects it (that's correct) but the publish callback of the client is never called and the client tries indefinitely to re-publish the message. Why this behavior?
3. Using async-mqtt as client library I get a similar behavior as described in point 2, but with the function subscribe. Instead, using the library mqtt (as I'm actually doing), subscribe works perfectly.

**Comment by robertsLando** [comment]
@matteodisabatino 

`/project/${projectId}/device/${deviceId}/uplink`

Could it be possible you wrongly added a leading `/` ? It's not recommended to use topics that start with `/`

> If  don't explicitly set qos=1 on publish, the server never calls the function authorizePublish. Is this the correct behavior

The server should call that on very publish, not only for qos > 1. Remember that if you call publish using broker.publish that will bypass that

About 2-3, could you provide a code [here](https://repl.it/languages/nodejs) that replicates the issue?

**Comment by matteodisabatino** [comment]
Hi @robertsLando, [here](https://repl.it/@disa1989/StrongRealMemory) my test code reproduces what explained in points 1 and 2.

About the point 1 I have to do a clarification because previously I made a wrong analysis: authorizePublish will trigger and the code will enter into the if (that's correct and that's what you expected) but the promise will not be rejected. Why that? Entering into the if means "authorization denied", so why the promise will not be rejected?

About the point 3 there's another clarification: I made a PR in which I updated all dependencies. After that all the problems (except the one explained in point 2) have resolved themselves.

**Comment by robertsLando** [comment]
Athourize publish is called [here](https://github.com/moscajs/aedes/blob/master/lib/handlers/publish.js#L34) from the publish handler that will call `client._nextBatch` that will emit a client `error` [here](https://github.com/moscajs/aedes/blob/master/lib/client.js#L63) that will result in a client disconnect. 

By default the client will try to re-connect but if the publish is made with QoS 1 it will try to send that packet again automatically (it respect the QoS), this doesn't happen with QoS 0 (once he send that packet it doesn't wait for ack)

The only problem here is that the publish should reject with an error, now I will do some tests and I will come back to you

**Comment by matteodisabatino** [comment]
@robertsLando very well. I'll wait for your answer.

**Comment by robertsLando** [comment]
@mcollina I have made some tests and seems that the error is not emitted to the client when the authorizePublish fails, we disconnect the client, is this the correct behaviour? Shouldn't we also return the error back to the client someway?

**Comment by robertsLando** [comment]
Based on mqtt specs: http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#MQTT-3.3.5-2

> If a Server implementation does not authorize a PUBLISH to be performed by a Client; it has no way of informing that Client. It MUST either make a positive acknowledgement, according to the normal QoS rules, or close the Network Connection.

So nothin wrong here @matteodisabatino

**Comment by matteodisabatino** [comment]
@robertsLando understood. Thanks for the clarification.

**Comment by deluxeroot** [comment]
In my code when authorizePublish is negated, the broker disconnects the client. How can I make client to stay still connected even if authorizePublish is negated? In my project on some topics only special clients can publish but I need the client to stay connected even if it is not allowed to publish to a certain topic.

**Comment by robertsLando** [comment]
That's by protocol design, going against this would be a protocol violation
