### ISSUE TITLE
[question] highWaterMark

### ISSUE THREAD

**Issue by robertsLando** [moscajs/aedes#495]
In a stream based application like aedes, should `highWaterMark` be a configurable option? Could it become a bottle neck with high traffic loads and increese the throughout? @mcollina 

> Once the total size of the internal read buffer reaches the threshold specified by highWaterMark, the stream will temporarily stop reading data from the underlying resource until the data currently buffered can be consumed (that is, the stream will stop calling the internal readable._read() method that is used to fill the read buffer).

https://nodejs.org/api/stream.html#stream_buffering

**Comment by mcollina** [comment]
It's not possible to change it as our sockets come from the node servers.

**Comment by robertsLando** [comment]
Even for Transorms inside aedes? Could it increese the throughout at least? We could add some docs about that if so

**Comment by robertsLando** [comment]
Mine is just a thought but if for example we make [this](https://github.com/moscajs/aedes/blob/master/lib/utils.js#L31) function a broker function where `highWatermark` is a broker option, could this have better perfromances?

**Comment by mcollina** [comment]
> Mine is just a thought but if for example we make this function a broker function where highWatermark is a broker option, could this have better perfromances?

Unlikely that having a global broker option would improve perf with that.

**Comment by robertsLando** [comment]
Ok thanks for the clarification Matteo
