### ISSUE TITLE
Live probeness Check 

### ISSUE THREAD

**Issue by bhirave** [moscajs/aedes#506]
Hello Team,
what approach would you suggest to check live probeness of `aedes-mqtt-broker` using kubernetes ?

i was thinking following two approaches:

1) at certain frequency, attempt to connect/subscribe/disconnect a new client
OR
2) at certain frequency, just check `aedes` server status

Thank you.

**Comment by robertsLando** [comment]
@bhirave You could just listen for aedes heartbeats `$SYS/<aedes.id>/heartbeat`
