### ISSUE TITLE
Is there an easy way to list all connected clients, when using multiple instances of Aedes?

### ISSUE THREAD

**Issue by Jaarson** [moscajs/aedes#510]
I'm using Docker Swarm and have couple of replicas of Aedes running. I can easily get IP addresses of all of them, then implement a logic to ask them for client list one by one (aedes.clients) .
But, is there an easier way? Since Aedes won't allow to connect two clients with the same ID, even if they try to connect to different instances - there is already a logic which keeps a list of all clients on all instances somewhere :) I'm using mqemitter-redis and aedes-persistence-mongodb.

PS. I'm super excited using Aedes, right now building IoT platform 🤞

**Comment by robertsLando** [comment]
@Jaarson Aedes to ensure unique clients ids in a cluster env subscribes to `$SYS/+/new/clients` and checks if he has an existing client with that id, if so it will close the connection.

So to answer your question, a solution would be to create a client that subscribes to `$SYS/+/new/clients` and `$SYS/+/disconnect/clients` to keep an update clients list.

Another solution could be to listen to `client` and `clientDisconnect` and store clients in a db
