### ISSUE TITLE
[question] How to prevent abuser subscribing to topic?

### ISSUE THREAD

**Issue by ilomon10** [moscajs/aedes#513]
hello, I just know mqtt

how to set [access control](https://mosquitto.org/man/mosquitto-conf-5.html) on a particular topic / client to prevent other clients from receiving sensitive messages, they can subscribe to wildcards to get all topic messages.

Maybe it's like socket.io which can create room and make clients join to certain rooms with unique keys so that other clients cannot easily listen.

Any best practice.

**Comment by robertsLando** [comment]
https://www.hivemq.com/blog/mqtt-essentials-part-5-mqtt-topics-best-practices/

Start from there. On aedes side there are authenticate and authorize functions that could help in this. Best practice in general from what you are looking for is to embed an id to topics and use aedes aithorize functions to enable some clients to subscribe/publish to certain topics

---

Daniel

**Comment by ilomon10** [comment]
@robertsLando thank you for fast respond. It can be done with [authorize function](https://github.com/moscajs/aedes/blob/master/docs/Aedes.md#handler-authenticate-client-username-password-callback), with compare stored authenticated client and i can [revoke](https://github.com/moscajs/aedes/blob/master/docs/Aedes.md#handler-authorizesubscribe-client-subscription-callback) client who trying to subscribe to specific topic. 
Now my problem solved. Thanks.
