### ISSUE TITLE
[bug] password is a Buffer in AuthenticateCallback

### ISSUE THREAD

**Issue by demian85** [moscajs/aedes#515]
Based on latest typings: 
```ts
  export type AuthenticateCallback = (
    client: Client,
    username: string,
    password: string,
    done: (err: AuthenticateError | null, success: boolean | null) => void
  ) => void
``` 

I'm getting a Buffer instead of a string for argument `password` in the actual callback, but I'm not sure which is the expected type. Either the type declaration or the actual implementation is wrong. 
It doesn't seem right to me that the password is a Buffer. 
Can someone please check this behavior? I can fix the type if you want.

Thanks.

**Comment by robertsLando** [comment]
@demian85 I think the type is wrong in types declaration bacause AFAIK it is correct that password is a Buffer for security reason. But to be sure I have to ask to @mcollina

**Comment by mcollina** [comment]
Yes, the types are wrong, password is a buffer as the MQTT protocol does not specify its encoding.

**Comment by robertsLando** [comment]
@demian85 Fell free to submit a pr to fix the types so

**Comment by demian85** [comment]
it's been fixed and I never knew it, npm did not upgrade the lib automatically :/
