### ISSUE TITLE
[bug] Connection closed

### ISSUE THREAD

**Issue by demian85** [moscajs/aedes#516]
**System Information**
- Aedes: 0.42
- NodeJS: 12.16
- OS: Amazon Linux AMI

Hello,

I started to get the following errors:

```
Error: connection closed
at write (/var/app/current/node_modules/aedes/lib/write.js:18:13)
at writeQoS (/var/app/current/node_modules/aedes/lib/client.js:179:5)
at Immediate.<anonymous> (/var/app/current/node_modules/aedes/lib/client.js:136:11)
at processImmediate (internal/timers.js:456:21)
at process.topLevelDomainCallback (domain.js:137:15)

Emitted 'error' event on Transform instance at:
at Transform.onerror (/var/app/current/node_modules/readable-stream/lib/_stream_readable.js:640:52)
at Transform.emit (events.js:311:20)
at Transform.EventEmitter.emit (domain.js:482:12)
at errorOrDestroy (/var/app/current/node_modules/aedes/node_modules/readable-stream/lib/internal/streams/destroy.js:98:101)
at onwriteError (/var/app/current/node_modules/aedes/node_modules/readable-stream/lib/_stream_writable.js:430:5)
at onwrite (/var/app/current/node_modules/aedes/node_modules/readable-stream/lib/_stream_writable.js:450:11)
at WritableState.onwrite (/var/app/current/node_modules/aedes/node_modules/readable-stream/lib/_stream_writable.js:160:5)
at Transform.afterTransform (/var/app/current/node_modules/aedes/node_modules/readable-stream/lib/_stream_transform.js:89:3)
at processImmediate (internal/timers.js:458:21)
at process.topLevelDomainCallback (domain.js:137:15)
```

The broker is rejecting almost every connection and it is running almost in production. I don't understand how this started to happen because I haven't made changes to the code for the past 3 days and the broker has been running just fine.

Does anyone have a clue what's going on? What kind of details can I give you? I'll paste some code if necessary.

Thanks!

**Comment by demian85** [comment]
So it appears that it broke after upgrading from v0.40 to v0.42, rolled back and it is working as expected. Please review the latest release because there is some nasty bug hidden.

**Comment by robertsLando** [comment]
@demian85 Are you using version 0.42 or 0.42.4? 

Can you add some console.log in aedes events ? Like `publish` `connect` etc..

Once the error occurs we can understand what is causing it. I'm using aedes in production too but I never faced this error

**Comment by demian85** [comment]
I'm using the latest version 0.42.4
I'm also listening to all possible events and logging to Cloudwatch, but there is no useful information to debug this issue.

I'm pasting the most important part of the code, leaving the most important stuff:

index.ts
```ts
import tls from 'ts'
import https from 'https'
import ws from 'websocket-stream'
import { broker } from './lib/broker'

const PORT = 8883
const WS_PORT = 8881

const KEY_PATH = path.join(__dirname, process.env.KEY_FILE || '')
const CERT_PATH = path.join(__dirname, process.env.CERT_FILE || '')
const CA_PATH = path.join(__dirname, process.env.CA_FILE || '')

// SSL setup options
const SSLoptions = {
  key: readFileSync(KEY_PATH),
  cert: readFileSync(CERT_PATH),
}

// TLS setup options
const TLSoptions = {
  key: readFileSync(KEY_PATH),
  cert: readFileSync(CERT_PATH),
  ca: readFileSync(CA_PATH),
}
const mqttServer = tls.createServer(TLSoptions, broker.handle)
const httpServer = https.createServer(SSLoptions)

// @ts-ignore
ws.createServer({ server: httpServer }, broker.handle)

// Start Websocket server
httpServer.listen(WS_PORT)

// Start main server
mqttServer.listen(PORT)

```

broker.ts
```ts
export const broker = Server({
  authenticate, // custom authentication using a REST API
  persistence:
    redisPersistence({
      port: process.env.REDIS_PORT,
      host: process.env.REDIS_HOST,
      maxSessionDelivery: 100,
      connectTimeout: 10000,
    }),
})

broker.on('client', (client) => {
  logger.info({ clientId: client.id }, `Client connected`)
})

broker.on('clientDisconnect', (client) => {
  logger.info({ clientId: client.id }, `Client disconnected`)
})

broker.on('publish', (packet, client) => {
  if (client) {
    logger.debug(
      { clientId: client.id, packet },
      `Client published packet on topic '${packet.topic}'`
    )

    // Parse MQTT packet and process message...
  }
})

broker.on('ack', (packet: MqttPacket, client) => {
  logger.debug(
    {
      clientId: client.id,
      packet,
    },
    `Client PUBACK`
  )
})

broker.on('subscribe', (subscriptions, client) => {
  const subs = subscriptions as ISubscription[]
  logger.info(
    { clientId: client.id, topic: subs[0].topic, qos: subs[0].qos },
    `Client subscribed to topic`
  )
})

broker.on('clientError', (client, err) => {
  logger.warn({ clientId: client.id, err }, `Client error`)
})

broker.on('connectionError', (client, err) => {
  logger.error({ clientId: client.id, err }, `Connection error`)
})
```

Thanks for your help.

**Comment by robertsLando** [comment]
The error occurs after a wos publish, I would like to see the entire log output to try to understand what is going on there... 

Also a working a working code (https://repl.it/languages/nodejs) that reproduces the problem would be the best

**Comment by robertsLando** [comment]
> Also, I'm expecting at least 2k concurrent devices online. Is there any optimization I can do?

Use clusters could be one

**Comment by demian85** [comment]
I think it would be easier to review which commits were added between version 0.40 and the latest one.
The stack trace I posted in my first message is the only thing I have.
I'm not using QoS 2, which appears to be the cause of an open issue.

**Comment by robertsLando** [comment]
> I think it would be easier to review which commits were added between version 0.40 and the latest one.

There are lot things that has changed in latest commits, there was many leaks fixed, the roout cause could be https://github.com/moscajs/aedes/commit/b8543838453731836d9cb9cac13720c247f3c358 , if so downgrading to version 0.42.2 should solve the problem. 

Anyway I don't have many info to help you with the code/logs you provided

**Comment by demian85** [comment]
I cannot find a way to test the rollback to v0.42.2. This is already in production and I would have to simulate thousands of devices for testing purposes. v0.40 is up and running with no problems.
As I said, that stack trace is the only thing I can share.

**Comment by robertsLando** [comment]
@demian85 https://github.com/moscajs/aedes/pull/517 could be a possbile fix to this errors

**Comment by robertsLando** [comment]
@demian85 Try with Aedes@0.42.5
