### ISSUE TITLE
[bug] sending multiple publish will only send a few

### ISSUE THREAD

**Issue by gailingmic** [moscajs/aedes#521]
**System Information**
- Aedes: 0.42.4
- NodeJS: 12.5.0
- OS: Windows 10, Mac OSX, Arch
- Arch: x86_64

**Describe the bug**
If you publish a bunch of messages in rapid succession not all of the messages will be send.

**To Reproduce**
```
const aedes = require('aedes')();
const httpServer = require('http').createServer();
const ws = require('websocket-stream');
const port = 8888;

ws.createServer({ server: httpServer }, aedes.handle)

const sleep = (time) => new Promise(resolve => {
    setTimeout(() => {resolve();}, time);
});

httpServer.listen(port, async function () {
    console.log('websocket server listening on port ', port)

    await sleep(10000);

    for (let i = 0; i < 10; i++)
    {
        aedes.publish({
            qos: 2,
            topic: 'test-topic',
            payload: `some test ${i}`,
            retain: false
        });
    }
})
```

**Comment by robertsLando** [comment]
@gailingmic why are you using `await` in aedes.publishj? It's not async, also I don't understad why you set the cmd and dup parameters

**Comment by gailingmic** [comment]
@robertsLando sorry the await was a copy paste error from my real codebase (i wrapped the function in a promise)
And i set cmd and dup because of the docs here: https://github.com/mqttjs/mqtt-packet#publish but removing those 2 changes nothing. the issue is still there! 

also i edited the code example to be correct

**Comment by robertsLando** [comment]
@gailingmic It is working: https://repl.it/@robertsLando/aedes521

**Comment by gailingmic** [comment]
@robertsLando could you please try it on your local machine and connect to it with a websocket mqtt client? because the event is firing for me locally aswell but it isnt getting send to any client (i tried multiple)

**Comment by robertsLando** [comment]
Could you setup an example using mqttjs?

**Comment by gailingmic** [comment]
oh my god! thank you so much... it was a bug in an old mqttjs version... 😅
