### ISSUE TITLE
[bug] Subscribe not working for retained messages

### ISSUE THREAD

**Issue by franzon** [moscajs/aedes#522]
**System Information**
- Aedes: 0.42.5
- NodeJS: 12.18.2
- OS: Ubuntu 20.04
- Arch: x86_64

**Describe the bug**
If a message with the retained flag is published, and at a later point in time the server subscribes to the topic of the message, the message is not received.

**To Reproduce**
1. Run aedes broker
2. Use `setTimeout` to simulate a future event which subscribes to topic `foo`
3. Before `setTimeout` callback gets called, publish a message with retained flag to topic `foo`
4. The message will not be received when subscribing to `foo`.

**Expected behavior**
Because of the retained flag, the message should be received when subscribing to it's topic.

**Additional context**
The message is received when testing with `mosquitto_sub` command.

**Comment by robertsLando** [comment]
Could you create a working example with code that reproduce the issue? Also, what persistence/emitter are you using?

**Comment by franzon** [comment]
I'm using `aedes-persistence-mongodb`. Here is an example:

```
const aedes = require('aedes');
const net = require('net');
const aedesPersistenceMongoDB = require('aedes-persistence-mongodb');

const broker = aedes({
    persistence: aedesPersistenceMongoDB({
        url: 'mongodb://localhost:27017/aedes',
    }),
});

const server = net.createServer(broker.handle);

server.listen(1883, () => {
    broker.publish({
        topic: 'foo',
        retain: true,
        payload: Buffer.from('bar')
    })

    setTimeout(() => {
        broker.subscribe('foo', (packet, callback) => {
            // Shouldn't this line be executed?
            console.log(packet.payload.toString())
        })
    }, 1000)
});
```

**Comment by robertsLando** [comment]
broker subscribe function isn’t like client subscribe, it doesn’t fetch retained. Try to do the same example using mqttjs and you will see it works

---

Daniel

**Comment by franzon** [comment]
Yes, it works. Thanks!
