### ISSUE TITLE
[question] Better examples

### ISSUE THREAD

**Issue by basickarl** [moscajs/aedes#524]
https://github.com/moscajs/aedes/blob/master/docs/Examples.md

While it is nice to have a file with code examples, I feel that they lack quite a lot of things... 

Graceful shutdown of the server for example (including kicking of client sockets manually) is one thing I'd like to see.

**Comment by robertsLando** [comment]
@basickarl What you are speaking about is something related to the http module, it is the server that handles sockets. There are lot online examples about how to keep track of sockets and gracefully close them (I think there are also some modules for this).

For example: https://github.com/tellnes/http-close
