### ISSUE TITLE
[question] How to get the client IP

### ISSUE THREAD

**Issue by vinayk7** [moscajs/aedes#527]
Is it possible to get IP address of the client in any event or method?
```
const fs = require('fs')
const port = 8883
const aedes = require('aedes')()
const server = require('tls').createServer({}, aedes.handle)
server.listen(port, function () {
    console.log('server started and listening on port ', port)
});
```

**METHOD**
`aedes.authenticate = function (client, username, password, callback) {
 //can I get client's ip here?
}`

**EVENT**
`aedes.on('client', (client)=>{
 //or here?
})
`

**Comment by robertsLando** [comment]
You should be able to get it from  `client.req`
