### ISSUE TITLE
[question] Can I mutate client.id in authenticate handler?

### ISSUE THREAD

**Issue by demian85** [moscajs/aedes#529]
Hello guys, I'm trying to normalize the client.id based on the username/password and I'm not sure where could be the right place to do that.
I need to identify the client by the actual user id in our database, but I cannot rely on the client putting the correct client.id when connecting, that can be any value...
So, when authenticating, I can actually extract the userId from my JWT and set it as the client.id and reuse it in further calls and use it, for example, to identify who sent a specific message to a topic.

Thanks.

**Comment by robertsLando** [comment]
I suggest to use another client property, like `client.user` where you add all user informations added on client connect event. You will be able to access to them even on other events as the client object will be the same
