### ISSUE TITLE
[bug]messages are not being delivered in multi-container environment

### ISSUE THREAD

**Issue by bhirave** [moscajs/aedes#531]
**System Information**
- Aedes: 0.42.5
- NodeJS: 12.13.1
- OS: Ubuntu 18.04
- Arch: x86_64
- redis (single instance)

**Describe the bug**
in cloud, we have 1 cluster, 4 nodes, 4 container setup, so there are 4 instances of mqtt broker. We have HaProxy load-balancer to balance TCP/WS connections. With this setup, published messages (with QoS1) are not being delivered to subscribers. I am not setting up aedes brokerID, so its auto-generated for now.

I looked into redis "retained" key, and each topic/message has a "brokerId". What could be reason that messages wont be delivered to subscribers in above setup environment ? Do i need redis-cluster in above setup ? if yes, how would i configure aedis to use redis-cluster

**Expected behavior**
I expect that with QoS1, messages get delivered to subscribers.

**Additional context**
With single container setup, messages are reliably being delivered. We were using Mosca in above setup, and it was working fine.

**Comment by robertsLando** [comment]
Are you using redis for mqitter and persistence too?

**Comment by bhirave** [comment]
I am just using aedes-redis-persistance package. Not using mqEmitter.

Thanks,
Bapu Hirave

Sent from my Android phone, please embrace the typos

________________________________

**Comment by bhirave** [comment]
I am just using aedes-redis-persistance library, not using emitter.

**Comment by bhirave** [comment]
Additional comments: we were using Mosca in above setup, and it was working fine.

**Comment by robertsLando** [comment]
You MUST  use mqemitter-redis or mqemitter mongo in a cluster environment. That’s the reason why it’s not working :) 

---

Daniel

**Comment by robertsLando** [comment]
@bhirave it's impossibile Mosca was working, it doesn't support clusters 😅

**Comment by bhirave** [comment]
@robertsLando let me setup mqemitter-redis. 

here is my redisOptions looks like, do i need to change anything to support redis-cluster configuration ? somewhere i read that i should pass an array of all redis instances connection info ?

```
const ioRedisOptions = {
  port: config.database.port,
  host: host,
  password: config.database.password,
  db: 0,
  maxRetriesPerRequest: 1000 * 60 * 60,
  enableReadyCheck: true,
  family: 4,           // 4 (IPv4) or 6 (IPv6)
  maxSessionDelivery: 1000, // maximum offline messages deliverable on client CONNECT, default is 1000
  showFriendlyErrorStack: true,
  packetTTL: function (packet) { // offline message TTL, default is disabled
    return config.cacheSettings.cacheTtl //seconds
  },
  retryStrategy: function (attempt) {
    if (attempt < config.cacheSettings.connectionRetryAttemptCount) {
      // reconnect after
      return Math.min(attempt * 10000, 30000); //how long (in ms)
    }
    logger.error(`Redis (retryStrategy): Attempt (${attempt}) time greater than configured attempt count (${config.cacheSettings.connectionRetryAttemptCount})`);
  }
}

const aedesPersistenceRedis = require('aedes-persistence-redis');

    let redisPersistence = aedesPersistenceRedis(ioRedisOptions);
    redisPersistence.waitForReady = true;

    let aedesOpts = {
        persistence: redisPersistence,
        authenticate: mqttAuth.authenticate,
        authorizeSubscribe: mqttAuthorization.authorizeSubscribe,
        authorizePublish: mqttAuthorization.authorizePublish,
    }

    const broker = aedes(aedesOpts);
```

**Comment by robertsLando** [comment]
@bhirave Please read the docs, everything it's documented
