### ISSUE TITLE
[question] Best way to store messages into DB.

### ISSUE THREAD

**Issue by Misiu** [moscajs/aedes#532]
I'm new to Aedes, I'd like to point that out at first, so please be gentle :)
I'm trying to create a solution that will allow me to store readings from sensors into DB.
I've based my solution on https://medium.com/better-programming/how-to-design-a-complete-iot-solution-using-node-js-674787409e57
This involves creating a couple of services:
-broker with Aedes (it is also responsible for authentication and authorization)
-storage service that subscribes to specific topics and stores the values in the database
-InfluxDB that stores the values

everything works fine when I publish a couple of messages from around 10 clients, but when I try to increase the number of messages and clients everything crashes.

` mqtt-benchmark --broker tcp://localhost:1883 --count 100 --clients 1000 --qos 0 --username brokerusername --password brokerpassword --topic house/bedroom/temperature  --payload {\"temperature\":20,\"timeStamp\":1597314150}`
(I have a pending PR that allows specifying payload: https://github.com/krylovsk/mqtt-benchmark/pull/12)

Now I'm trying to find the bottlenecks.

I'd like to ask the community what would be the best way to store messages from specific topics into DB. What are the best practices?
Before choosing Aedes I've looked at HiveMQ, it has a concept of extensions, so you could write the message storing part as part of the broker.
I'm not sure is I should go the same road with Aedes - add message storing to my broker service? or should I write a separate service (as I have now) to connect via MQTT to my broker and store the messages?

I'm aware that Aedes can be clustered, but can it be done with docker-compose or docker swarm or Kubernetes?
If I add message storing to broker then it will be easier for me to cluster broker (as each broker will only store messages it got).
If I write a separate service to store values then I won't be able to cluster it.
Please correct me on that if I'm wrong.

I'd like to target 1k clients and reading around once per second, but I also want to know what is the maximum number of clients my solution can handle, so I'd like to test 10k clients. Any advice on how to best test that?

Any advice is more than welcome!

**Comment by robertsLando** [comment]
> I'd like to ask the community what would be the best way to store messages from specific topics into DB. What are the best practices?

It depends, but you could see how telegraf does it: https://www.influxdata.com/integration/mqtt-monitoring/

> I'm aware that Aedes can be clustered, but can it be done with docker-compose or docker swarm or Kubernetes?

Sure

**Comment by Misiu** [comment]
@robertsLando thanks for the reply.
I've seen that integration, but unfortunately, I can't change the message format (the integration expects Telegraf Input Data Format).

The thing that I must decide now is how to store the messages:
1: create a separate service
2: add message storing to broker service

1 will be easier to create but will be harder to cluster. 2 will be easier to cluster (as each broker will store only the messages it receives).

Did anyone create a large system with aedes? 1k connections aren't much, but I need something to start with :)
I'm searching for best-practics, tutorials, or blogs.

**Comment by robertsLando** [comment]
I would store messages by using the process that is running aedes and get published messages by subscribing to aedes `published` event

**Comment by Uttam-EWW** [comment]
> I would store messages by using the process that is running aedes and get published messages by subscribing to aedes `published` event

@robertsLando 
is it okay if I(Aedes Broker) subscribe to topic and then process that data?

`
mqttBroker.subscribe('device/leave', (packet, cb) => {
    console.log('Device is disconnected...');
    printPacketDetails(packet);
    DevicesController.deviceDisconnected(packet.payload.toString());
});
`

**Comment by robertsLando** [comment]
> is it okay if I(Aedes Broker) subscribe to topic and then process that data?

Yes, just remember to call the callback

**Comment by robertsLando** [comment]
BTW I prefer to listen for client connected/ disconnected event instead

**Comment by Uttam-EWW** [comment]
> > is it okay if I(Aedes Broker) subscribe to topic and then process that data?
> 
> Yes, just remember to call the callback

Yes, i'm doing so.

**Comment by Uttam-EWW** [comment]
> BTW I prefer to listen for client connected/ disconnected event instead

Totally agree with you, but this topic(device/leave) is last will topic with little bit more info about device which used for further process.
