### ISSUE TITLE
[feat] Could it support client subscribe/unsubscribe notification to other client?

### ISSUE THREAD

**Issue by bobbydog** [moscajs/aedes#540]
I used mosca.js before, which provide the topic "$SYS/+/new/subscribes"  "$SYS/+/new/unsubscribes"   to let my service client knows that the app client had subscribed the particular topic, but in aedes  it did not publish this message with similar topic.

**Comment by robertsLando** [comment]
Yes it could. Feel free to open a PR or just wait some days until I find some time to sort this out :)
