### ISSUE TITLE
TLS two way authentication with unique identity per connection

### ISSUE THREAD

**Issue by ahmedwahdan** [moscajs/aedes#542]
Hello,

I would like to have TLS layer with unique certificate, keys for each device like AWS IOT.
Where to start?

Regards,

**Comment by robertsLando** [comment]
Could you better explain what you are looking for in details?

**Comment by ahmedwahdan** [comment]
> Could you better explain what you are looking for in details?

I can see how to use TLS but how to create unique identity for each device so each device will be authenticated with unique keys and certificate. is it clear now?

**Comment by ahmedwahdan** [comment]
I got the idea how to do this.
The point is we just verify the client certificate using the CA certificate. 
My question is how to revoke a client certificate?

**Comment by robertsLando** [comment]
You could use aedes `preConnect` https://github.com/moscajs/aedes/blob/master/docs/Aedes.md#handler-preconnect-client-callback or handle this in tls server manually by listening for `connection` event and manually close the socket when you don't want to allow that client to connect https://nodejs.org/api/tls.html#tls_event_connection
