### ISSUE TITLE
Client disconnected after 3-4 min if app won't be in use. 

### ISSUE THREAD

**Issue by vipin-kiwi** [moscajs/aedes#544]
When we did not use app then after 3-4 min client disconnected. if i am opening the app from the last position. then unable to post the message. i have checked the server. 'keepaliveTimeout' event trigger with in 4 min.

**Comment by robertsLando** [comment]
This is not a bug with aedes, if keepaliveTimeout is triggered it means youir client isn't sending any ping to broker. Try to increese the keepAlive in client (it's a connect parameter) or dig into your client code to understand why it's not sending a ping to broker.

http://www.steves-internet-guide.com/mqtt-keep-alive-by-example/
