### ISSUE TITLE
[question] Conflict with Passenger and Node Cluster module

### ISSUE THREAD

**Issue by mer30boy** [moscajs/aedes#565]
Aedes uses shortid 
But shortid required the Node Cluster module, which is incompatible with Passenger, a non-functional shim was returned and your app may still work. 
However, please remove or [replace](https://github.com/ai/nanoid/) the related package as soon as possible.

**Comment by robertsLando** [comment]
@mer30boy PR?

**Comment by mer30boy** [comment]
I am a novice and I do not have the ability to do this

**Comment by robertsLando** [comment]
@mer30boy shortid is only used for clients ids on connect. If your clients specify a client id it will never be used.

@mcollina Do you think we should replace `shortid` module?

**Comment by mcollina** [comment]
I wrote https://www.npmjs.com/package/hyperid a long time ago.

**Comment by robertsLando** [comment]
@mer30boy PR submitted
