### ISSUE TITLE
[question] Consulting help for setting up and fixing bugs in Aedes redis clustering?

### ISSUE THREAD

**Issue by gerad** [moscajs/aedes#569]
We're interested in setting up Aedes redis clustering, but are running into many issues with it.

- adding new subscriptions cause a really high CPU load (we're seeing 200-300% CPU load) when having ~300 clients connect and subscribe to ~30 topics each – we don't see this problem without clustering enabled
- subscribe acks don't come back if a client attempts to subscribe to more than a single topic in a subscribe payload
- messages of over 1 mb appear to be dropped

is there any chance of (paid) consulting help to look into some of these bugs (or misconfigurations on our end)? we can also try and contribute fixes back, but the code is unfamiliar and the learning curve is steep (e.g. https://github.com/moscajs/aedes-tests/issues/23)

**Comment by mcollina** [comment]
My team at [NearForm](https://www.nearform.com/) works on solving performance issues (and more). Feel free to reach out at matteo.collina@nearform.com.

**Comment by gerad** [comment]
Will do.
