### ISSUE TITLE
[question]how to bridge direct mqtt and mqtt over websocket

### ISSUE THREAD

**Issue by shenhome** [moscajs/aedes#570]
I want to use browser to control my device through 4G mqtt.
1) 4G mqtt use direct mqtt
2) browser use mqtt over websocket

The broker ether be configured as direct mqtt broker or websocket broker
how to make it works to connect both?

**Comment by robertsLando** [comment]
You should create a tcp server and a websocket server, I suggest you to use [aedes-server-factory](https://github.com/moscajs/aedes-server-factory#examples) or check examples here in aedes

**Comment by shenhome** [comment]
create 2 servers? how to make web socket server information automatically publish to tcp server?

**Comment by robertsLando** [comment]
> how to make web socket server information automatically publish to tcp server?

that is handled by the broker.

 You can also create just one server and use it both for ws and tcp connections.
