### ISSUE TITLE
Aedes stops exactly after 100 messages

### ISSUE THREAD

**Issue by panbak** [moscajs/aedes#572]
Hello, I didn't open a bug issue because it's probably something wrong with my code.
I have two clients connected to aedes, one to publish and one to receive the messages, but after 100 messages aedes stops receiving. 
Below my aedes server code:

```
const aedes = require('aedes')()
const server = require('net').createServer(aedes.handle)
const port = 1883

const initAedes = () => {

    server.listen(port, function () {
        console.log('Mqtt server started and listening on port ', port)
    })

    aedes.subscribe('consumption', function (packet, cb) {
        console.log('Received: ', packet.payload.toString());
    });

}
```

My publisher:

```
client.on('connect', function () {
        client.subscribe('consumption');

        let ctr = 0;
        setInterval(() => {
            ctr++;
            console.log('publishing: ' + ctr);
            client.publish('consumption', ctr.toString());
        }, 100);

    })

```

My receiver:
 
```
client.subscribe('consumption');
    client.on('message', function (topic, message) {
        console.log('Received: ' + message.toString())
    })
```

Sorry if I misunderstood something, I'm a newbie.

**Comment by robertsLando** [comment]
@panbak Add an error handler to aedes publish to see if there are errors

**Comment by panbak** [comment]
I added these


```
    aedes.on('clientError', function (client, err) {
        console.log('client error', client.id, err.message, err.stack)
    })

    aedes.on('connectionError', function (client, err) {
        console.log('client error', client, err.message, err.stack)
    })
```
but I don't get any error.

**Comment by mcollina** [comment]
You are not calling the callback inside the function you pass to subscribe.

**Comment by robertsLando** [comment]
https://github.com/moscajs/aedes/blob/master/docs/Aedes.md#aedessubscribe-topic-deliverfunc-callback

**Comment by panbak** [comment]
Thank you guys. Is there any practical example I can see? I'm struggling with the documentation.

**Comment by panbak** [comment]
Ok I figured it out.

**Comment by chenmocoder** [comment]
> 

can you show thath how you resolve this problem？
i have same question in my code。
