### ISSUE TITLE
[bug] clientDisconnect

### ISSUE THREAD

**Issue by luan-nvg** [moscajs/aedes#574]
I copied the whole file, and removed the mongodb because I don't need it, however, after disconnecting the user, he is not entering this clientDisconnect function

```js
// fired when a client disconnects
aedes.on('clientDisconnect', function(client) {
    console.log('Client Disconnected: \x1b[31m' + (client ? client.id : client) + '\x1b[0m', 'to broker', aedes.id)
})
```

https://github.com/moscajs/aedes/blob/master/examples/clusters/index.js

**Comment by robertsLando** [comment]
@luan-nvg You must use mongodb persistence or redis in order to use clusters

**Comment by luan-nvg** [comment]
> @ luan-nvg Você deve usar mongodb persistence ou redis para usar clusters

Hi, how are you? i don't need to use clusters, is there any other way for me to use clientDisconnect? (after I opened this ticket, sometimes it enters the clientDisconnect "randomly", but if I remove the device from the internet cable, it does not enter the client Disconnect)

**Comment by robertsLando** [comment]
You are using the wrong example. Try an example without clusters please. There are a lot
