### ISSUE TITLE
[bug] issue with docker compose in win10

### ISSUE THREAD

**Issue by EnricoBeltramo** [moscajs/aedes#575]
**System Information**
- Aedes: 0.40.1
- NodeJS: 12.13.1
- OS: win10 - docker desktop
- Arch: x86_64

**Describe the bug**
Error running aedes with docker compose example

**To Reproduce**
1. Checkout repository,
2. go in docker folde
3. docker-compose up --build
4. error:
aedes    |
aedes    |  ______   ________  _______   ________   ______
aedes    | /      \ |        \|       \ |        \ /      \
aedes    | |  $$$$$$\| $$$$$$$$| $$$$$$$\| $$$$$$$$|  $$$$$$\
aedes    | | $$__| $$| $$__    | $$  | $$| $$__    | $$___\$$
aedes    | | $$    $$| $$  \   | $$  | $$| $$  \    \$$    \
aedes    | | $$$$$$$$| $$$$$   | $$  | $$| $$$$$    _\$$$$$$\
aedes    | | $$  | $$| $$_____ | $$__/ $$| $$_____ |  \__| $$
aedes    | | $$  | $$| $$     \| $$    $$| $$     \ \$$    $$
aedes    | \$$   \$$ \$$$$$$$$ \$$$$$$$  \$$$$$$$$  \$$$$$$
aedes    |
aedes    | Cannot find module '/data/dockerConfig.js'
aedes    | Require stack:
aedes    | - /usr/src/app/lib/cli.js
aedes    | - /usr/src/app/bin/aedes

**Expected behavior**
Start docker without issue

**Additional context**

**Comment by robertsLando** [comment]
@EnricoBeltramo I think this is a sure error, could you show me your dockerfile? where did you specify the `/data/dockerConfig.js`?

**Comment by EnricoBeltramo** [comment]
The files are same of the repository, I didn't any change. May be the issue is related to win10 and user access / volume mapping? I clear any docker and volumes and added follow line in docker-compose file:
user: root:root
 because it look similar to an previous issue that I had with another docker (https://github.com/node-red/node-red-docker/issues/69). With that change, not it works correctly.

**Comment by robertsLando** [comment]
> May be the issue is related to win10 and user access / volume mapping

Yes I think it is, seems that it's not able to find the dockerConfig.js file for some reason
