### ISSUE TITLE
[bug] multiple messages service 

### ISSUE THREAD

**Issue by luan-nvg** [moscajs/aedes#577]
after a user sends several messages there comes a time when the service does not receive the messages sent, does anyone have any idea what it is? (and this ends up affecting other users, as their messages also stop arriving, but the service remains online and customers are connected normally)

**Comment by robertsLando** [comment]
@luan-nvg Could you provide us a script to replicate this?

**Comment by luan-nvg** [comment]
> @ luan-nvg Você poderia nos fornecer um script para replicar isso?


PROJECT SERVER: 

`require('dotenv').config();
const socket_io = require('socket.io-client');
const mongoose = require('mongoose');
const queryString = require('query-string');
const ClientIo = require('./client-io');
const boardSendRouter = require('./routes/board_send');
const boardRouter = require('./routes/board');
const appSendRouter = require('./routes/app_send');
const appRouter = new appSendRouter();
const url = require('url');
const aedes = require('aedes')();
const mqtt = require('mqtt');
const server = require('net').createServer(aedes.handle);
//
const port = 1883;
//
//
mongoose.connect(process.env.DATABASE_URL, {
    useUnifiedTopology: true,
    useNewUrlParser: true,
    useFindAndModify: false,
});
server.listen(port, function() {
    console.log('Aedes listening on port:', port)
    aedes.publish({
        topic: 'aedes/hello',
        payload: "I'm broker " + aedes.id
    })
})
aedes.on('subscribe', function(subscriptions, client) {
    // console.log('MQTT client \x1b[32m' + (client ? client.id : client) + '\x1b[0m subscribed to topics: ' + subscriptions.map(s => s.topic).join('\n'), 'from broker', aedes.id)
})
aedes.on('unsubscribe', function(subscriptions, client) {
    // console.log('MQTT client \x1b[32m' + (client ? client.id : client) + '\x1b[0m unsubscribed to topics: ' + subscriptions.join('\n'), 'from broker', aedes.id)
})
// fired when a client connects
aedes.on('client', function(client) {
    console.log('Client Connected: \x1b[33m' + (client ? client.id : client) + '\x1b[0m', 'to broker', aedes.id)
})
// fired when a client disconnects
aedes.on('clientDisconnect', function(client) {
    console.log('Client Disconnected: \x1b[31m' + (client ? client.id : client) + '\x1b[0m', 'to broker', aedes.id)
})
// fired when a message is published
aedes.on('publish', async function(packet, client) {
    // console.log('Client \x1b[31m' + (client ? client.id : 'BROKER_' + aedes.id) + '\x1b[0m has published', packet.payload.toString(), 'on', packet.topic, 'to broker', aedes.id)
})
aedes.subscribe('board/drive', async (packet, cb) => {
    // var client = mqtt.connect('https://redgtech.com/mqtt');
    var params = JSON.parse(packet.payload.toString());
    var arduinoRouter = new boardSendRouter();
    var getLastMessageBoard = await arduinoRouter.getLastMessageBoard(params);

    if (getLastMessageBoard['success']) {
        var merge = Object.assign(getLastMessageBoard['data'], params);
        var new_info = noSaveJson(merge);
        var info_prepare = {
            'id_board': params['id_board'],
            'message': JSON.stringify(new_info)
        }
        var respoArduino = await arduinoRouter.post(info_prepare).then((eeee) => {
            return eeee;
        });
    } else {
        console.error('não foi possivel processar a informaçao')
    }
});

// //Ação utilizada para enviar para a placa algum item
aedes.subscribe('board/submit_action', function(packet, cb) {
    console.log("board/submit_action");
    try {
        var element = JSON.parse(packet.payload.toString());
        var topic = "board_" + element['id_board'];
        aedes.publish({
            topic: topic,
            payload: packet.payload.toString()
        })
    } catch (e) {
        // declarações para manipular quaisquer exceções
        console.log(e); // passa o objeto de exceção para o manipulador de erro
    }
});
//Ação utilizada para enviar para a placa algum item
aedes.subscribe('arduino/status', function(packet, cb) {
    console.log("arduino/status: ");
    try {
        var element = packet.payload.toString();
        console.log(element);
    } catch (e) {
        // declarações para manipular quaisquer exceções
        console.log(e); // passa o objeto de exceção para o manipulador de erro
    }
});

function noSaveJson(format_json) {
    var newJson = {};
    //'AC4', 'AC5', 'AC6', 'AC7', 'AC8'
    const noSave = new Set(['id_board', 'id_confirm', 'padrao']);
    for (const key in format_json) {
        if (!noSave.has(key)) {
            newJson[key] = format_json[key]
        }
    }
    return newJson;
}`

PROJECT2 API CLIENT


`
const mqtt = require('mqtt');

router.get('/', async (req, res, next) => {
    var result = {};
    var result = {
        success: false,
        message: "Invalido"
    };
    // var object = req.body;
    var object = req.query
    if (mongoose.Types.ObjectId.isValid(object.id_board)) {
        if (object.cod != '' && object.cod != '?' && object.cod != undefined) {
            const app_send = new AppSend({
                id_board: object.id_board,
                message: object.cod,
            });
            var save = await app_send.save();
            topic = "board/submit_action";
            var client = mqtt.connect('https://redgtech.com/mqtt');
            client.on('connect', () => {
                console.log('conectou mqtt');
                client.publish(topic, JSON.stringify(save));
                // client.publish("arduino/status", "testekkk");
                // client.end();
            });
            client.on('disconnect', () => {
                console.log('disconnect eita');
            });
            client.on('offline', () => {
                console.log('offline eita');
            });
            // client.end();
            // console.log("chegou na acao");
            result['success'] = true;
            result['message'] = "Ação enviada!";
            res.json(result);
            return;
        }
        var promise = await BoardSend.findOne({
            id_board: object.id_board
        }).sort({
            _id: -1
        }).limit(1);
        result = promise ? JSON.parse(promise.message) : {};
        res.json(result);
        return;
    } else {
        res.send(404);
        return;
        // var json = require('./teste-offline.json'); //with path
    }
});
`

**Comment by luan-nvg** [comment]
> @luan-nvg Could you provide us a script to replicate this?

Forgive me for the lack of practice when placing the code, I'm a beginner. if there is another better way tell me that i will correct it.

Basically I have a Project in nodeJS that is running mqtt, and another project aimed at API express where the user sends a request and the express project is imported into the mqtt client to connect to the SERVER mqtt project,

if I send 50 requests, 50 new clients are connected (since each request I generate a new client), however after exceeding 50 requests, it still connects to SERVER1 (so much so that the client is still being created), but the message of the other does not arrive side (NO SERVER1)




SERVER1 MQTT:

> 
> require('dotenv').config();
> const mongoose = require('mongoose');
> const queryString = require('query-string');
> const ClientIo = require('./client-io');
> const boardSendRouter = require('./routes/board_send');
> const boardRouter = require('./routes/board');
> const appSendRouter = require('./routes/app_send');
> const appRouter = new appSendRouter();
> const url = require('url');
> const aedes = require('aedes')();
> const mqtt = require('mqtt');
> const server = require('net').createServer(aedes.handle);
> const port = 1883;



> mongoose.connect(process.env.DATABASE_URL, {
>     useUnifiedTopology: true,
>     useNewUrlParser: true,
>     useFindAndModify: false,
> });
> server.listen(port, function() {
>     console.log('Aedes listening on port:', port)
>     aedes.publish({
>         topic: 'aedes/hello',
>         payload: "I'm broker " + aedes.id
>     })
> })

> aedes.subscribe('board/drive', async (packet, cb) => {
>     var params = JSON.parse(packet.payload.toString());
>     var arduinoRouter = new boardSendRouter();
>     var getLastMessageBoard = await arduinoRouter.getLastMessageBoard(params);
>     console.log("board/drive");
>     console.log(params);
>     if (getLastMessageBoard['success']) {
>         var merge = Object.assign(getLastMessageBoard['data'], params);
>         var new_info = noSaveJson(merge);
>         var info_prepare = {
>             'id_board': params['id_board'],
>             'message': JSON.stringify(new_info)
>         }
>         var respoArduino = await arduinoRouter.post(info_prepare).then((eeee) => {
>             return eeee;
>         });
>     } else {
>         console.error('não foi possivel processar a informaçao')
>     }
> });



CLIENT API GET :



> var express = require('express');
> var router = express.Router();
> const mongoose = require('mongoose');
> const BoardSend = require('../models/board_send');
> const AppSend = require('../models/app_send');
> const mqtt = require('mqtt');




> router.get('/', async (req, res, next) => {
>     var result = {};
>     var result = {
>         success: false,
>         message: "Invalido"
>     };
>     // var object = req.body;
>     var object = req.query
>     if (mongoose.Types.ObjectId.isValid(object.id_board)) {
>         if (object.cod != '' && object.cod != '?' && object.cod != undefined) {
>             const app_send = new AppSend({
>                 id_board: object.id_board,
>                 message: object.cod,
>             });
>             var save = await app_send.save();
>             topic = "board/submit_action";
>             var client = mqtt.connect('https://SERVER1/mqtt');
>             client.on('connect', () => {
>                 console.log('conectou mqtt');
>                 client.publish(topic, JSON.stringify(save));
>                 // client.publish("arduino/status", "testekkk");
>                 // client.end();
>             });
>             client.on('disconnect', () => {
>                 console.log('disconnect eita');
>             });
>             client.on('offline', () => {
>                 console.log('offline eita');
>             });
>             // client.end();
>             // console.log("chegou na acao");
>             result['success'] = true;
>             result['message'] = "Ação enviada!";
>             res.json(result);
>             return;
>         }
>         var promise = await BoardSend.findOne({
>             id_board: object.id_board
>         }).sort({
>             _id: -1
>         }).limit(1);
>         result = promise ? JSON.parse(promise.message) : {};
>         res.json(result);
>         return;
>     } else {
>         res.send(404);
>         return;
>     }
> });

**Comment by robertsLando** [comment]
@luan-nvg You are missing to call `cb` in aedes subscribe

**Comment by chaunnt** [comment]
@robertsLando r
I have same issue but it is from other mqtt client. 
I use nodejs mqtt library for 1 client and reactjs mqtt for another web client
`
/* Copyright (c) 2021-2023 Reminano */
require('dotenv').config();
const Logger = require('../../utils/logging');
const mqtt = require('mqtt');
const moment = require('moment');

if (process.env.MQTT_BROKER_ENABLE * 1 === 1) {
  return;
}

////MQTT Client
Logger.info(`MQTT Connect` + `mqtt://${process.env.MQTT_BROKER_HOST}:${process.env.MQTT_BROKER_PORT}`);
let _agentList = [];

let client = getClient();

function addClient() {
  let _client = mqtt.connect(`mqtt://${process.env.MQTT_BROKER_HOST}:${process.env.MQTT_BROKER_PORT}`, {
    clientId: `OKEDA_GAME${new Date()}`,
    clean: true,
    keepalive: 600,
  });
  _agentList.push(_client);
}

function getClient() {
  return _agentList[0];
}

async function _initializeClient() {
  let _client = getClient();
  if (_client) {
    _client = _agentList.pop();
    if (_client.connected) {
      await _client.endAsync(true);
      _client.removeAllListeners();
      _client.removeOutgoingMessage();
      delete _client;
    }
  }

  addClient();
  client = getClient();

  client.on('connect', function () {
    Logger.info('MQTT Client connected');
    client.subscribe('SERVER_TIME', function (err) {
      Logger.info('MQTT Client Subcribed success');
    });
    client.subscribe('OKEDA_CLIENT', function (err) {
      Logger.info('MQTT Client Subcribed success');
    });
  });

  client.on('message', function (topic, message) {
    Logger.info(`message on ${topic}`);
  });
  client.on('reconnect', function () {
    Logger.info(`MQTT Client reconnect at ${new Date()}`);
  });
  client.on('close', function () {
    Logger.info(`MQTT Client close at ${new Date()}`);
  });
  client.on('disconnect', function () {
    // initializeClient();
    Logger.info(`MQTT Client disconnect at ${new Date()}`);
  });
  client.on('offline', function () {
    Logger.info(`MQTT Client offline at ${new Date()}`);
  });
  // client.on('packetreceive', function (package) {
  //   Logger.info(`MQTT Client packetreceive at ${new Date()}`);
  // });
  client.on('packetsend', function (package) {
    Logger.info(`MQTT Client packetsend at ${new Date()}`);
  });
  client.on('error', function (error) {
    Logger.info(`MQTT Client error at ${new Date()}`);
    Logger.error(error);
  });
}

_initializeClient();

setInterval(() => {
  _initializeClient();
}, 17000);

////WS Client
// var client  = mqtt.connect('ws://vtss-station-server.makefamousapp.com:10777', {
//   wsOptions: {
//     host: "vtss-station-server.makefamousapp.com",
//     port: 10777
//   }
// })

//WSS Client
// var client  = mqtt.connect('wss://vtss-station-server.makefamousapp.com:10666', {
//   rejectUnauthorized: false
// })

setInterval(() => {
  publishMessageToClient('OKEDA_CLIENT', 'OKEDA_CLIENT');
}, 5000);

function publishMessageToClient(topic, message) {
  try {
    let _client = getClient();
    if (_client && _client.connected) {
      _client.publish(topic, message, {
        qos: 0,
        retain: false,
      });
      _client.removeOutgoingMessage();
    }
  } catch (error) {
    Logger.error(error);
    Logger.error(`publishJSONToClient ${topic}`);
  }
}

function publishJSONToClient(topic, data) {
  Logger.info(`publishJSONToClient ${topic}`);
  try {
    let _client = getClient();
    if (_client && _client.connected) {
      _client.publish(topic, JSON.stringify(data), {
        qos: 0,
        retain: false,
      });
      _client.removeOutgoingMessage();
    }
  } catch (error) {
    Logger.error(error);
    Logger.error(`publishJSONToClient ${topic}`);
  }
}
module.exports = {
  publishMessageToClient,
  publishJSONToClient,
};

`

**Comment by chaunnt** [comment]
I have to re-init the client to work-around this problem but it can not fix the problem properly

**Comment by chaunnt** [comment]
my broker 
```
/* Copyright (c) 2021-2023 Reminano */

require('dotenv').config();

const MQTT_ADMIN_USERNAME = process.env.MQTT_ADMIN_USERNAME || 'mqttadmin';
const MQTT_ADMIN_PASSWORD = process.env.MQTT_ADMIN_PASSWORD || 'mqttadminpass';

const MQTT_PORT = parseInt(process.env.MQTT_PORT || 5555);
const WEBSOCKET_SSL_PORT = parseInt(process.env.WEBSOCKET_SSL_PORT || 6666);
const WEBSOCKET_PORT = parseInt(process.env.WEBSOCKET_PORT || 7777);
const Logger = require('../../utils/logging');

const ws = require('websocket-stream');
const fs = require('fs');
const aedes = require('aedes')({
  queueLimit: 20000,
  concurrency: 5000,
});
// const aedes = require('aedes')({
//   authenticate: (client, username, password, callback) => {

//   },
//   authorizePublish: (client, packet, callback) => {

//   },

//   authorizeSubscribe: (client, packet, callback) => {

//   }
// });

//MQTT Broker
const mqttBroker = require('net').createServer(aedes.handle);
mqttBroker.listen(MQTT_PORT, function () {
  Logger.info('mqtt broker started and listening on port ', MQTT_PORT);
});

//Websocket 'WS'
const httpServer = require('http').createServer();
ws.createServer({ server: httpServer }, aedes.handle);
httpServer.listen(WEBSOCKET_PORT, function () {
  Logger.info('Aedes MQTT-WS listening on port: ' + WEBSOCKET_PORT);
});

//Websocket SSL 'WSS'
const httpsServer = require('https').createServer({
  key: fs.readFileSync(`${process.env.KEY_PATH}openssl/privkey.pem`),
  cert: fs.readFileSync(`${process.env.KEY_PATH}openssl/fullchain.pem`),
});
ws.createServer({ server: httpsServer }, aedes.handle);

httpsServer.listen(WEBSOCKET_SSL_PORT, function () {
  Logger.info('Aedes MQTT-WSS listening on port: ' + WEBSOCKET_SSL_PORT);
});

let _CCUCounter = 0;
aedes.on('clientReady', function (client) {
  Logger.info('[MQTT] client connected ' + client.id);
  _CCUCounter++;
});
aedes.on('clientDisconnect', function (client) {
  Logger.info('[MQTT] client disconnected ' + client.id);
  _CCUCounter--;
});
aedes.on('keepaliveTimeout', function (client) {
  Logger.info('[MQTT] client keepaliveTimeout ' + client.id);
});
aedes.on('subscribe', function (subscriptions, client) {
  Logger.info('[MQTT] client subscribe ' + client.id);
  Logger.info('[MQTT] client subscribe ' + JSON.stringify(subscriptions));
});
aedes.on('clientError', function (client, error) {
  Logger.info('[MQTT] client clientError ' + client.id);
  Logger.info(error);
});
aedes.on('connectionError', function (client, error) {
  Logger.info('[MQTT] client connectionError ' + client.id);
  Logger.info(error);
});
// fired when a message is received
// aedes.on('published', function (packet, client) {
//   Logger.info(`[MQTT] published ${JSON.stringify(packet)}`);
// });

// server.on('ready', () => {
//   Logger.info('✓'.green + ' Mqtt server is running on port: '.cyan + `${MQTT_PORT}`.green);
//   Logger.info('✓'.green + ' Mqtt over websocket is on port: '.cyan + `${MQTT_WS_PORT}`.green);

//   server.authenticate = (client, username, password, callback) => {
//     Logger.info(username, password);
//     var authorized = username === MQTT_ADMIN_USERNAME && password.toString() === MQTT_ADMIN_PASSWORD;
//     if (authorized) client.user = username;
//     callback(null, authorized);
//   };

//   const message = {
//     topic: 'SERVER',
//     payload: `Mqtt Server over websocket started at ${new Date()}`,
//     qos: 2,
//     retain: true,
//   };
//   publish(message);
// });

// const _publish = message =>
//   new Promise((resolve, reject) => {
//     message = Object.assign({ qos: 0, retain: false }, message);
//     // Logger.info(JSON.stringify(message));
//     aedes.publish(message, (obj, packet) => {
//       return resolve(message.topic);
//     });
//   });

function _publish(message) {
  aedes.publish(message, error => {
    if (error) {
      Logger.error(`aedes.publish error`);
      Logger.error(error);
      Logger.error(message);
    }
  });
}

function publishJson(topic, json) {
  Logger.info(`publishJson ${topic}`);
  const payload = Object.assign({ _id: new Date().toISOString() }, json);
  const message = {
    topic,
    payload: JSON.stringify(payload),
    qos: 0,
    retain: false,
  };
  return _publish(message);
}

function publishMessage(topic, message) {
  const packetData = {
    topic,
    payload: message,
    qos: 0,
    retain: false,
  };
  return _publish(packetData);
}

const moment = require('moment');
setInterval(() => {
  Logger.info(moment().format(`YYYYMMDDHHmmss _CCUCounter: ${_CCUCounter}`));
  publishMessage('SERVER_TIME', moment().add(-1, 'second').format('YYYYMMDDHHmmss'));
}, 1000);

module.exports = {
  publishMessage,
  publishJson,
};

```
