### ISSUE TITLE
[question]Pre publish hook

### ISSUE THREAD

**Issue by friesendrywall** [moscajs/aedes#578]
Perhaps this already exists, but what would it take implement some type of pre publish hook so that custom handling could be implemented down the line of AWS device shadow get, update, delta, etc ?  Essentially, this would require the ability to modify or prevent packet publishing, or perhaps only replying to the requesting client.

I've been looking at this code for a bit, but it isn't clear to me where this should happen.

**Comment by getlarge** [comment]
You could try with [authorizePublish](https://github.com/moscajs/aedes/blob/master/docs/Aedes.md#handler-authorizepublish-client-packet-callback).
You would pass an error in the callback if you want to reject the packet, and eventually you can modify packet.payload to your wish.

**Comment by friesendrywall** [comment]
Passing an error immediately closes the connection, which isn’t really what I am trying to achieve. The only way I see to stop packet propagation is to set qos to something like -1, which seems a bit like a hack.

**Comment by robertsLando** [comment]
I think we could provide a way to allow to don't authorize a publish without disconnect the client? It may go against mqtt spec btw. @mcollina thoughts?

**Comment by friesendrywall** [comment]
In my way of thinking, the puback still has to happen, but I just don’t want some topics rebroadcast until they are validated and perhaps persisted. A more universal middleware might accomplish this more cleanly.

**Comment by friesendrywall** [comment]
I am closing this, because I think mqtt-connection is more correct platform for what I am trying to do.
