### ISSUE TITLE
[bug] QOS 2 

### ISSUE THREAD

**Issue by luan-nvg** [moscajs/aedes#580]
QOS 2 

Hello, I'm going through a somewhat embarrassing situation, I disconnect the Client from the server, send new messages to the topic, but after the client connects, he does not receive the messages. is this normal in QOS 2? I read a very interesting topic: [mqtt-essentials-part-6-mqtt-quality-of-service-levels](https://www.hivemq.com/blog/mqtt-essentials-part-6-mqtt-quality-of-service-levels/)  -  I'm testing QOS 2

SERVER:

```

require('dotenv').config();
const mongoose = require('mongoose');
const queryString = require('query-string');
const ClientIo = require('./client-io');
const boardSendRouter = require('./routes/board_send');
const boardRouter = require('./routes/board');
const appSendRouter = require('./routes/app_send');
const appRouter = new appSendRouter();
const url = require('url');
const aedes = require('aedes')();
const mqtt = require('mqtt');
const server = require('net').createServer(aedes.handle);
const port = 1883;


mongoose.connect(process.env.DATABASE_URL, {
    useUnifiedTopology: true,
    useNewUrlParser: true,
    useFindAndModify: false,
});
server.listen(port, function() {
    console.log('Aedes listening on port:', port)
})

aedes.subscribe('board/submit_action', function(packet, cb) {
    try {
        var element = JSON.parse(packet.payload.toString());
        var topic = "board_" + element['id_board'];
        aedes.publish({
            topic: topic,
            payload: packet.payload.toString()
        })
        cb();
    } catch (e) {
        // declarações para manipular quaisquer exceções
        console.log(e); // passa o objeto de exceção para o manipulador de erro
    }
});



```

CLIENT ARDUINO:
```
    byte willQoS = 2;
    const char* willTopic = "arduino/status";
    const char* willMessage = "OFF_LINE";
    boolean willRetain = true;
    const char* username = "Placa_1";
    const char* password = "legal";
    boolean cleanSession = false; 

    if (clientMqtt.connect(id_board, username, password, willTopic, willQoS, willRetain, willMessage, cleanSession) { 
      clientMqtt.subscribe("board_5ffcf3e5c18f457afa091c19");
    }
```

API:

```

router.get('/', async (req, res, next) => {
    var result = {};
    var result = {
        success: false,
        message: "Invalido"
    };
    // var object = req.body;
    var object = req.query
    if (mongoose.Types.ObjectId.isValid(object.id_board)) {
        if (object.cod != '' && object.cod != '?' && object.cod != undefined) {
            const app_send = new AppSend({
                id_board: object.id_board,
                message: object.cod,
            });
            var save = await app_send.save();
            topic = "board/submit_action";
            var client = mqtt.connect('MYSERVER/mqtt', {
                username: 'Placa_1',
                password: 'legal',
                clientId: 'client_api',
            });
            client.on('connect', () => {
                client.publish(topic, JSON.stringify(save));
                // client.publish("arduino/status", "testekkk");
                client.end();
            });
            client.on('disconnect', () => {
                console.log('disconnect eita');
            });
            client.on('offline', () => {
                console.log('offline eita');
            });
            // client.end();
            // console.log("chegou na acao");
            result['success'] = true;
            result['message'] = "Ação enviada!";
            res.json(result);
            return;
        }
        var promise = await BoardSend.findOne({
            id_board: object.id_board
        }).sort({
            _id: -1
        }).limit(1);
        result = promise ? JSON.parse(promise.message) : {};
        res.json(result);
        return;
    } else {
        res.send(404);
        return;
        // var json = require('./teste-offline.json'); //with path
    }
});



```

**Comment by robertsLando** [comment]
@luan-nvg Could you firstly try an example fully in nodejs or by using another mqtt client? If that is working it means it's something wrong on the arduino code

**Comment by luan-nvg** [comment]
> @luan-nvg Could you firstly try an example fully in nodejs or by using another mqtt client? If that is working it means it's something wrong on the arduino code

I will do the tests and give feedback #

**Comment by luan-nvg** [comment]
> @luan-nvg Could you firstly try an example fully in nodejs or by using another mqtt client? If that is working it means it's something wrong on the arduino code

Hello, how are you? thank you for the patience.

I used a nodejs client to do it, but unfortunately it didn't work either


```
var mqtt = require('mqtt')
var client = mqtt.connect('MYSERVER/mqtt', {
    username: 'Placa_1',
    password: 'legal',
    clientId: '5ffcf3e5c18f457afa091c19',
});


// console.log(client);
client.on('connect', function () {
  console.log("oii conect");
  client.subscribe("board_5ffcf3e5c18f457afa091c19", 2);
  client.subscribe("arduino/status");
  client.subscribe("board/status");
})

client.on('message',function(topic, message, packet){
	console.log("message is "+ message);
	console.log("topic is "+ topic);
});

client.on('closed', function () {
    console.log('mqtt.event.closed');
});

client.on('error', function (msg) {
    console.log('mqtt.event.error', msg);
});


```

Step by step:


1 - I turned on the server
2- I called the client
3 - I sent a message via API to MQTT
4 - Server received and sent to Client MQTT on nodeJS
5- clientMqtt received message
6- Disconnected the MQTT client
7 - I sent a message via API to MQTT
8 - I called the mqtt client again
9 - did not receive the message

**Comment by luan-nvg** [comment]
I solved the problem by putting it as follows
in the server, missing       {  qos: 2}

```
aedes.subscribe('board/submit_action', function(packet, cb) {
    try {
        var element = JSON.parse(packet.payload.toString());
        var topic = "board_" + element['id_board'];
        aedes.publish({
            topic: topic,
            payload: packet.payload.toString()
        })
        cb();
    } catch (e) {
        // declarações para manipular quaisquer exceções
        console.log(e); // passa o objeto de exceção para o manipulador de erro
    }
});

```
to 


```
aedes.subscribe('board/submit_action', function(packet, cb) {
    try {
        var element = JSON.parse(packet.payload.toString());
        var topic = "board_" + element['id_board'];
        console.log("Alguem esta tentando utilizar  board/submit_action : " + topic);
        aedes.publish({
            topic: topic,
            payload: packet.payload.toString(),
            qos: 2
        })
        cb();
    } catch (e) {
        // declarações para manipular quaisquer exceções
        console.log(e); // passa o objeto de exceção para o manipulador de erro
    }
});
```



so in addition to saying that the client receives qos: 2 messages, the server must also be informed that the publication he will make for this client is necessary to inform that it is qos: 2 as well.

confirm?

**Comment by luan-nvg** [comment]
> > @luan-nvg Could you firstly try an example fully in nodejs or by using another mqtt client? If that is working it means it's something wrong on the arduino code
> 
> Hello, how are you? thank you for the patience.
> 
> I used a nodejs client to do it, but unfortunately it didn't work either
> 
> ```
> var mqtt = require('mqtt')
> var client = mqtt.connect('MYSERVER/mqtt', {
>     username: 'Placa_1',
>     password: 'legal',
>     clientId: '5ffcf3e5c18f457afa091c19',
> });
> 
> 
> // console.log(client);
> client.on('connect', function () {
>   console.log("oii conect");
>   client.subscribe("board_5ffcf3e5c18f457afa091c19", 2);
>   client.subscribe("arduino/status");
>   client.subscribe("board/status");
> })
> 
> client.on('message',function(topic, message, packet){
> 	console.log("message is "+ message);
> 	console.log("topic is "+ topic);
> });
> 
> client.on('closed', function () {
>     console.log('mqtt.event.closed');
> });
> 
> client.on('error', function (msg) {
>     console.log('mqtt.event.error', msg);
> });
> ```
> 
> Step by step:
> 
> 1 - I turned on the server
> 2- I turned on the client
> 3 - I sent a message via API to MQTT
> 4 - Server received and sent to Client MQTT on nodeJS
> 5- clientMqtt received message
> 6- Disconnected the MQTT client
> 7 - I sent a message via API to MQTT, 
> 8 - wait 40 seconds, I called the mqtt client again
> 9 - did not receive the message

**Comment by robertsLando** [comment]
Your subscribe is not correct: https://github.com/mqttjs/MQTT.js#subscribe

**Comment by luan-nvg** [comment]
> Your subscribe is not correct: https://github.com/mqttjs/MQTT.js#subscribe

unsuccessfully nodejs:

   client.subscribe({
        'board_listener_5ffcf3e5c18f457afa091c19': { qos: 2 },
        'arduino/status': { qos: 2 },
        'board/status': { qos: 2 },
    })

**Comment by luan-nvg** [comment]
@robertsLando  

when multiple requests are sent via Client nodeJs

has a message that is not coming
  client.publish(topic, JSON.stringify(params), {
                qos: 2
            });

**Comment by robertsLando** [comment]
What you are looking for is the retain flag or the clean flag set on connect. I suggest you to avoid using the clean flag as in most cases retain flag is enough. So ret the option retain true to the messages you send and when the client connects it will receive the last ones message of each topic

---

Daniel
