### ISSUE TITLE
mq redis connect is false[question]

### ISSUE THREAD

**Issue by chenzhidongweb** [moscajs/aedes#581]
2 hours later mq redis can 't emit message,

client can receive servers subscribe, but can't receive servers mq emit,

but servers mq emit false

**Comment by robertsLando** [comment]
Example script to reproduce the error

**Comment by chenzhidongweb** [comment]
> Example script to reproduce the error

I solved，
Sorry, Is my code problem，
mqemitter does not call cb() when using on,
messagqueue is not clear
