### ISSUE TITLE
Raspberry Pi not showing Aedes node?

### ISSUE THREAD

**Issue by adamelli** [moscajs/aedes#586]
When searched on Node-Red Palette, no aedes or "node-red-contrib-aedes" shows up. I tried downloading it via the command prompt of my Raspberry Pi Zero:

```
pi@raspberrypi:~ $ npm install node-red-contrib-aedes
npm WARN saveError ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.

+ node-red-contrib-aedes@0.5.0
updated 1 package and audited 129 packages in 40.469s

6 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

Anything obvious that should be fixed/done?

**Comment by getlarge** [comment]
For info, you are in the wrong repository, you're looking for [node-red-contrib-aedes](https://github.com/martin-doyle/node-red-contrib-aedes).
The error says that you miss the `package.json` in your current directory so you need to create it, with `npm init` for example.
