### ISSUE TITLE
[question] Aedes interoperability with ExpressJs

### ISSUE THREAD

**Issue by mcgouganp** [moscajs/aedes#588]
Is it possible to attach an Aedes broker using a websocket transport to an ExpressJs router?

An example of how this could be achieved would be very helpful.

What I have is an expressjs web server that is already serving pages using various routes.
I would like to add in a new route that will connect to my aedes broker.

As a test I had tried this:
```
const express           = require('express');
const websocketStream	= require('websocket-stream/stream');
const mqtt              = require('../broker');

const router = express.Router();

router.ws('/route0', function(ws, req) {
	console.log('Triggered WS route');
	const stream = websocketStream(ws);
	mqtt.handle(stream);
});
```

In this example ../broker exports my already working broker instance.
In broker.js I have configured an aedes broker accepting mqtt connections, and this is already working correctly.
However I want also allow connections into the broker via a wss URL.

Edited to add extra clarification

**Comment by mcgouganp** [comment]
By way of a further example, as a very simplified test I also tried this.

Test Client - client.js
`
const mqtt = require('mqtt');
const client  = mqtt.connect('ws://localhost:9999/');

client.on('connect', function () {
    console.log('Connect success');
    client.subscribe('device/#', function (err) {
        if(err) {
            console.log('Error subscribing: ' + err);
        } else {
            console.log('Subscribe success');
        }
    });
})

client.on('message', function (topic, message) {
  // message is Buffer
  console.log(message.toString())
  client.end()
})
`

and test server - server.js
`
const express = require('express');
const app = express();
const expressWs = require('express-ws');
const websocketStream = require('websocket-stream/stream');
const aedes = require('aedes')();

expressWs(app, null, {
    perMessageDeflate: false
});

app.use(function (req, res, next) {
  console.log('middleware');
  req.testing = 'testing';
  return next();
});

app.get('/', function(req, res, next){
  console.log('get route', req.testing);
  res.end();
});

let client;

app.ws('/', function(ws, req) {
  const stream = websocketStream(ws, { binary: true  } );
  console.log('socketA', req.testing);
  client = aedes.handler(stream);
  console.log('socketB', req.testing);
});

aedes.on('client', function(client) {
    console.log('Aedes client connected');
});

app.listen(9999);
`

In this example when I try to connect with the client I get the "socketA" message but not the "socketB" message on the server, and no output on the client.

**Comment by robertsLando** [comment]
Give a look at this: https://github.com/moscajs/aedes-server-factory/blob/main/index.js it may help

**Comment by mcgouganp** [comment]
> Give a look at this: https://github.com/moscajs/aedes-server-factory/blob/main/index.js it may help

Thanks. Looking at this showed me a slight change, plus an error, plus helped me understand my original expressjs integration error.

In case it helps others, working solutions below.

A working test server:

```
const express = require('express');
const app = express();
const expressWs = require('express-ws');
const WebSocket = require('ws');
const aedes = require('aedes')();

expressWs(app, null, {
    perMessageDeflate: false
});

app.use(function (req, res, next) {
  console.log('middleware');
  req.testing = 'testing';
  return next();
});

app.get('/', function(req, res, next){
  console.log('get route', req.testing);
  res.end();
});

let client;

app.ws('/', function(ws, req) {
  const stream = WebSocket.createWebSocketStream(ws);
  console.log('socketA', req.testing);
  client = aedes.handle(stream, req);
  console.log('socketB', req.testing);
});

aedes.on('client', function(client) {
    console.log('Aedes client connected');
});

app.listen(9999);
```

And also for reference, my original issue with integration with my main expressjs project was due to using the standard setup that expressjs sets up, which has a standalone http server which the expressjs app is registered with like:
`const server = http.createServer(app);`
If you are using a setup like this you have to change the instantiation of the express-ws module to reference the http server like:
```
expressWs(app, server, {
  perMessageDeflate: false,
});
```

I hope this helps others.
