### ISSUE TITLE
[question]Does aedes support the use of X.509, For example, verify

### ISSUE THREAD

**Issue by weiliudong** [moscajs/aedes#591]
I want to authorize the device certificate, and the device logs into the aedes system through the certificate, just like AWS. Is there any examples or solutions for reference?

**Comment by robertsLando** [comment]
I think this is something that could be handled using aedes `preConnect` but there are no existing example AFAIK. @getlarge any suggestions?

**Comment by getlarge** [comment]
Indeed `preConnect` could be useful to check the client certificate, but first client and server connections needs the be initialized with keys, certificates and other specific options.
@weiliudong you could have a look at this [project](https://github.com/julie-ng/nodejs-certificate-auth) to get you started.

**Comment by weiliudong** [comment]
> Indeed `preConnect` could be useful to check the client certificate, but first client and server connections needs the be initialized with keys, certificates and other specific options.
> @weiliudong you could have a look at this [project](https://github.com/julie-ng/nodejs-certificate-auth) to get you started.

This is the certificate I made with reference to the preConnect project to help see if it meets the requirements of aedes.

Prepare public and private keys for the server and client
Generate the server-side private key:
openssl genrsa -out server.key 1024
Generate server-side public key:
openssl rsa -in server.key -pubout -out server.pem
Generate client private key:
openssl genrsa -out client.key 1024
Generate the client public key:
openssl rsa -in client.key -pubout -out client.pem

Generate CA certificate
Generate CA private key:
openssl genrsa -out ca.key 1024
Generate request file:
openssl req -new -key ca.key -out ca.csr
CN
myca
myca
myca
myca
localhost

123456
myca

Generate CA certificate:
openssl x509 -req -in ca.csr -signkey ca.key -out ca.crt

Generate server-side certificate and client-side certificate

The server side needs to apply for a signature certificate from the CA, and it still creates its own CSR file before applying for a signature certificate:
openssl req -new -key server.key -out server.csr
CN
myserver
myserver
myserver
myserver
localhost

123456
myserver

To apply for a certificate from your own CA organization, the signing process requires the participation of the CA's certificate and private key, and finally a certificate with the CA's signature is issued:
openssl x509 -req -CA ca.crt -CAkey ca.key -CAcreateserial -in server.csr -out server.crt

Generate client-side csr:
openssl req -new -key client.key -out client.csr
CN
myclient
myclient
myclient
myclient
localhost

123456
myclient

The client side gets the CA signature to generate the client side certificate:
openssl x509 -req -CA ca.crt -CAkey ca.key -CAcreateserial -in client.csr -out client.crt

**Comment by getlarge** [comment]
> This is the certificate I made with reference to the preConnect project to help see if it meets the requirements of aedes.

Just to make it clear, Aedes is not directly involved in certificates handling, instead it's the server that you attach to Aedes which should have the proper configuration, see the server [example](https://github.com/julie-ng/nodejs-certificate-auth/blob/master/server/server.js).
Then what is happening in the `app.get('/authenticate')` block could be reproduced in the `preConnect` hook that you register in Aedes [config](https://github.com/moscajs/aedes/blob/master/docs/Aedes.md#handler-preconnect-client-packet-callback).

On the client side, you could get started with that MQTT client [example](https://github.com/mqttjs/MQTT.js/blob/master/examples/tls%20client/mqttclient.js) to see how to load your certificate and key.

**Comment by weiliudong** [comment]
Thank you very much for your support.

**Comment by getlarge** [comment]
You're welcome

**Comment by gnought** [comment]
I'm back, hope all you well.

@weiliudong Aedes is a mqtt server following MQTT protocol 3.1/3.11 up to now. It supports password authentication in CONNECT packet and goes into [authenticate](https://github.com/moscajs/aedes/blob/master/docs/Aedes.md#handler-authenticate-client-username-password-callback) handler. The purpose of inventing [preConnect](https://github.com/moscajs/aedes/blob/master/docs/Aedes.md#handler-preconnect-client-packet-callback) is to open more possibilities before aedes starts to proceed the connected session, at the same time to make sure it is a valid mqtt traffic. 
If an authentication is required before establishing a mqtt session like socket tls, preConnect is not the option. We could go further to extend aedes, but it is advised to add a layer on top of aedes in terms of stability and scalability.

**Comment by robertsLando** [comment]
Happy to see you back @gnought! 

BTW you right, I suggested the "easier" solution but the best one is to make this happen before it comes to aedes, like what we are doing in protocol decoder
