### ISSUE TITLE
[question] How to set sessionPresent TTL?

### ISSUE THREAD

**Issue by seeLuck** [moscajs/aedes#599]
If client set `clean` to false, how long will server keep client's session?

Is there any way to config it?

**Comment by robertsLando** [comment]
Session expiry interval is something introduced in MQTT v5 that aedes doesn't support. Sessions doens't have a TTL in aedes

**Comment by seeLuck** [comment]
@robertsLando
So how dose Aedes implement the session check on server side? Will the session exist forever if the client don't clean it? It seems a mem-leaking here.

**Comment by robertsLando** [comment]
https://stackoverflow.com/questions/36034433/mqtt-clean-session

**Comment by seeLuck** [comment]
@robertsLando
Thanks you, I got it.
This step is quite unfriendly for client, but seems the only way to clean the session.

I just thinking, if the session works for aedes-server cluster, it must be stored in a persistence(redis). So I could set the session key expired by customized.

Is that thought right?

**Comment by robertsLando** [comment]
@seeLuck You could set a ttl if you are usiong persistence redis or mongo, the ttl should be set both on packets and in subscriptions
