### ISSUE TITLE
Dom[question]

### ISSUE THREAD

**Issue by oendnsk675** [moscajs/aedes#617]
How to implementation to my html DOM, or how to integrated this lib with websocket

**Comment by robertsLando** [comment]
Your question has no sense. If you are looking for an mqtt client library you can check mqttjs, this is an mqtt broker

**Comment by oendnsk675** [comment]
> Your question has no sense. If you are looking for an mqtt client library you can check mqttjs, this is an mqtt broker

i'm sorry sir, but how i use the aedes with websocket

**Comment by robertsLando** [comment]
https://github.com/moscajs/aedes/blob/main/docs/Examples.md

**Comment by oendnsk675** [comment]
> https://github.com/moscajs/aedes/blob/main/docs/Examples.md
can I use socket.io for the websocket???

**Comment by robertsLando** [comment]
You can use https://github.com/mqttjs/MQTT.js as client. To enable websocket on the broker follow the example in the link

**Comment by oendnsk675** [comment]
> https://github.com/moscajs/aedes/blob/main/docs/Examples.md

sir can i ask in this you answer, i'm using MQTT server over WebSocket, but how make my mc esp8266 connect to my broker, because I can't connect to my broker, in essence I want to mqtt msg from esp8266 to the broker, then display it on the web with a websocket, basically that's what I want to do

**Comment by robertsLando** [comment]
Sorry but this is something that is not strictly related to Aedes. I cannot help you there
