### ISSUE TITLE
[question] Is it possible to recognize nameserver?

### ISSUE THREAD

**Issue by expandboard** [moscajs/aedes#621]
if set nameserver in /etc/hosts file with this config;
127.0.0.1       test.mqtt.nip
and host address in mqtt client set to test.mqtt.nip:1883
when client connected, the value of client.conn.remoteAddress will be ::ffff:127.0.0.1

Is it possible to know on client preconnect event what nameserver set in client host?
if client uses test.mqtt.nip in host, Can we be able to know host name on preconnect or connected event?

**Comment by robertsLando** [comment]
I think you are looking for [dns.reverse](https://nodejs.org/api/dns.html#dns_dns_reverse_ip_callback)
