### ISSUE TITLE
MQTT Bridge Support between aedes

### ISSUE THREAD

**Issue by jsponz** [moscajs/aedes#623]
On the features list, it says: "MQTT Bridge Support between aedes".

Is there any configuration example? I want to bridge two aedes brokers. 

Thanks!

**Comment by robertsLando** [comment]
>  I want to bridge two aedes brokers.

You can do this if they share the same mqemitter

**Comment by jsponz** [comment]
Thanks for the quick answer. 

Let me explain you more the scenario. 

I have a local AEDES based broker in my house.  I have another one (also AEDES based) in the cloud. I want to bridge them, so I can interact with the devices in my home from outside.

**Comment by robertsLando** [comment]
that kind of bridge is not implemented yet. What you can do in this case is to use mqemitter mongodb/redis and make both aedes share the same db for the mqemitter
