### ISSUE TITLE
[question] Default Docker Image - Override just Auth? 

### ISSUE THREAD

**Issue by dejonghe** [moscajs/aedes#631]
First, super thankful for the project. 

I've been using the default docker container and the config.js to fill basic MQTT needs. I really like this concise config / setup, but need to add in the authentication and authorization. Do I need to setup my own node project, build out the mq and persistence, or is there a simple way to extend the default for just what I need? 

My confusion spawns from the Docker docs linking to aedes-cli, and the Docker entrypoint of that running aedes but I cant tell if it's from that repo or this one. It seems like it should run the cli... but I've got a server running so I'm trying to understand how this is put together. I'd like to just copy a package.json, a js file, make a few modifications, and keep my config.js file as it is, or have a simple way to just override the couple call backs I need. 

Seems like I shouild just build out a full project but I thought i'd ask first.

**Comment by robertsLando** [comment]
aedes-cli should be used as it is out of the box. I suggest to start a new project, you could need something else in future and end up with this anyway

**Comment by dejonghe** [comment]
Understood. Thank you for the quick feedback.
