### ISSUE TITLE
Retain flag in published messages after subscription

### ISSUE THREAD

**Issue by Rick-GO** [moscajs/aedes#633]
Hi Everybody,

Recently I switched from Mosquitto broker to Aedes broker. (Node in Node-RED)

I see a small difference in the way the broker publishes retained messages directly after subscription by a client.  The Mosquitto broker didn't add the retain flag to the header of the published message. The Aedes broker does add this flag.

I have some devices in the field which are capable of retrieving data from published messages (by the broker) with this retain flag in the message header. If I publish a message manually to te broker with the retain flag to true, the subscribed clients do receive this message because in these messages the retain flag is not set.

I have tried to set the retain flag to false in the Aedes broker code to prevent this retain flag from being set whet publishing retained messages to clients which are subscribing but it seems I'm also preventing incoming messages from being stored in db. Does anyone know if I can set the retain flag to false (somewhere in code) when publishing these messages to clients?

The clients are located all over the country so a solution on broker side is preferred above updating client software.

Thanks for you reaction.

Test environment:
Aedes broker in Node-RED
MQTT publisher and subscriber in Node-RED

**Comment by robertsLando** [comment]
This are the [specs](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc385349265)

> When sending a PUBLISH Packet to a Client the Server MUST set the RETAIN flag to 1 if a message is sent as a result of a new subscription being made by a Client [MQTT-3.3.1-8]. It MUST set the RETAIN flag to 0 when a PUBLISH Packet is sent to a Client because it matches an established subscription regardless of how the flag was set in the message it received [MQTT-3.3.1-9].

So if you receive a retained message with flag set to 1 after a subscription this is correct. 

It is not correct if the flag is set when receiving a message with the flag set when you are subscribed to a topic and a client publish a retain message, in that case the broker before forwarding the message to you should set the flag to 0. 

This is to allow client to distinguish retained packets (stored in retain db and sent after a subscription) from forwarded packets

**Comment by Rick-GO** [comment]
Thank you @robertsLando for clarification.

The broker work as it should be. I think in the past, the Mosquitto broker didn't stick up exactly to this protocol. Therefore my clients don't expect a retain flag in the messages they receive (protocol not implemented as you described). So the retained published messages are ignored.

Is it possible (in code) to prevent the broker from building messages with retain flag? My clients doesn't need to distinguish retained published messages and normal published messages. I know I'm cheating the protocol but changing the software of al clients in the field..

**Comment by robertsLando** [comment]
Based on the persistence you are using you could try to patch the `storeRetained` method to set the retain flag to false. https://github.com/moscajs/aedes-persistence/blob/master/persistence.js#L32

**Comment by Rick-GO** [comment]
I think that this wil prevent an incoming retained message from being stored. In that case, the broker will not publish this message when a client subscribes. So in my use case I want the ability to publish retained messages to the broker. The only thing I'd like to do is prevent the broker from setting the retain flag in publishing retained messages. 

I can find and edit publish messages but these are only the 'regular' publish messages. I'm searching for the publish method used to publish retained messages. For persistence I'm using MongoDB.

**Comment by robertsLando** [comment]
That is done here: https://github.com/moscajs/aedes/blob/main/lib/handlers/subscribe.js#L224

**Comment by Rick-GO** [comment]
Thank you @robertsLando. That did the trick!

**Comment by robertsLando** [comment]
You welcome :)
