### ISSUE TITLE
[question] Sorry i'm so newbie for this mqtt, how we know the clientId is send message

### ISSUE THREAD

**Issue by oendnsk675** [moscajs/aedes#638]
because I will make a broker with many clients later

**Comment by robertsLando** [comment]
https://github.com/moscajs/aedes/blob/main/docs/Aedes.md#event-publish

**Comment by oendnsk675** [comment]
> https://github.com/moscajs/aedes/blob/main/docs/Aedes.md#event-publish

I want to ask, when I listen to the broker with a certain subscribe topic, how do I know the client ID that sent the message

**Comment by robertsLando** [comment]
If you read the doc you will see that the second argument is the client. So using `client.id` will do the trick
