### ISSUE TITLE
[bug] Broker does not terminate when closing

### ISSUE THREAD

**Issue by kiesel** [moscajs/aedes#640]
**System Information**
- Aedes: 0.46.0
- NodeJS: v12.22.1
- OS: ArchLinux 
- Arch: x86_64

**Describe the bug**
Opening a broker, listening to connections, then closing the broker leaves the node process running. The process should terminate, though.

I have found no examples for this, and no contrary documentation, so I am a bit lost.

**To Reproduce**
This is a small reproducing testcase:

```js
const aedes = require('aedes')();
const { createServer } = require('aedes-server-factory');
const server = createServer(aedes);

server.on('close', () => console.log('Closing'));
server.on('error', (err) => console.log('Error', err));
server.listen(1883, 0, function () {
  console.log('server started');
  server.close((err) => {
    if (err) {
      console.error(err);
    }
  });
});
```

**Expected behavior**
Runs, then quits.

**Comment by robertsLando** [comment]
@kiesel You have closed the server, not the broker. Missing `aedes.close` https://github.com/moscajs/aedes/blob/main/docs/Aedes.md#aedesclose-callback

**Comment by kiesel** [comment]
Thanks a lot, this solves it.
