### ISSUE TITLE
[question]  Migrating from moscajs to aedes: TypeError: aedes.publish is not a function

### ISSUE THREAD

**Issue by Ryukyo** [moscajs/aedes#641]
I inherited an mqtt based project and would like to use aedes (0.46.0) instead of moscajs, but I get the error message "TypeError: aedes.publish is not a function" after passing the login screen of my app. 2 Files are relevant I think:

mqttServer.js (I get the log output of this file, so the server creation works)
```
const aedes = require('aedes')();
const mqttController = require('../controllers/mqttController');
const mqttServer = require('net').createServer(aedes.handle)
const port = 1883;

mqttServer.listen(port, function () {
    console.log('MQTT server started and listening on port ', port)
  })
mqttServer.on('clientConnected',mqttController.connectHandler);
mqttServer.on('published', mqttController.publishHandler);

module.exports = {
     mqttServer,
     aedes
};
```

index.js
```
const clients = require('../shared');
// const mqttServer = require('../loaders/mqqtServer'); was used before switching to aedes
const aedes = require('../loaders/mqqtServer');

function publishToClients(clientId, topic, subCallback=null, payload = null){
    const packet = {
        cmd: 'publish',
        topic: topic,
        payload: payload === null ? clientId : clientId+'/'+payload,
        qos: 2,
        retain: false,
    };
    **aedes.publish(packet, clientId, subCallback!==null ? function() { } : ()=>{return;} );**
}
```

The error message originates from the bold line. Originally I used mqttServer.publish before switching to aedes, which worked fine. Could anybody help me about why publish wouldn't be available at this point? It seems to be used with different parameters than with moscajs, but I definitely could find the method in aedes' documentation

**Comment by robertsLando** [comment]
`const {aedes} = require('../loaders/mqqtServer');`

Missing `{}`
