### ISSUE TITLE
[bug] limit at the time of subscribing the message

### ISSUE THREAD

**Issue by oendnsk675** [moscajs/aedes#642]
**System Information**
- Aedes: 0.40.1
- NodeJS: 12.13.1
- OS: windows 8.1
- Arch: x64

**Describe the bug**
i get some kind of bug, when i send message from my nodeMcu when to 100 times the broker i created with aedes can't catch the message anymore, but when i refresh the broker it can catch again

**Comment by robertsLando** [comment]
You should add some code here to understand where the problem is... BTW 100 is the default max concurrency, check [docs](https://github.com/moscajs/aedes/blob/main/docs/Aedes.md#new-aedesoptions--new-aedesserveroptions) so you may be doing something wrong
