### ISSUE TITLE
[question] what is the most correct example for setting aedes broker, here I use 1 million concurency, is that wrong or is there a better way, because when I set 10 concurencies, only 10 messages are captured

### ISSUE THREAD

**Issue by oendnsk675** [moscajs/aedes#643]

**Comment by robertsLando** [comment]
Like I said in the other issue, you need to show me the code you use to bootstrap aedes

**Comment by oendnsk675** [comment]
like this is my code at the broker bro

var aedes = require('aedes')({concurrency:10, queueLimit : 100, heartbeatInterval : 5000})
// console.log(aedes);
var server = require('net').createServer(aedes.handle)
var port = 1234


server.listen(port, function () {
	console.log('server listening on port', port)
})
server.on('error', (err) => console.log('Error', err));
aedes.subscribe('kenaikan_air', function(packet, cb) {
  console.log("counter :",aedes.counter, "\n");
  console.log("queueLimit :",aedes.queueLimit);
  console.log("concurrency :",aedes.mq.concurrency);
  console.log('Published', packet.payload.toString());
  console.log("current mq :",aedes.mq.current);

});

**Comment by oendnsk675** [comment]
is there a best way sir?

**Comment by robertsLando** [comment]
You are missing to call `cb()` in your subscribe function. Adding that will fix the problem
