### ISSUE TITLE
Where can I find the list of all supported $SYS-topics?

### ISSUE THREAD

**Issue by YevYar** [moscajs/aedes#645]
Hello! Thank you for this awesome module.
Perhaps I haven't read the documentation carefully, but I did not find a list of all supported $SYS-topics.
Could you say me where can I find the list of all supported $SYS-topics, please?

**Comment by robertsLando** [comment]
I don't think we have a complete list but all them should be documented [here](https://github.com/moscajs/aedes/blob/main/docs/Aedes.md)

Basically the prefix is `$SYS/<aedes.id>` for all of them
