### ISSUE TITLE
Is there any plan to support MQTT 5.x?

### ISSUE THREAD

**Issue by nttd-zhaolongri** [moscajs/aedes#656]
Is there any plan to support MQTT 5.x?

**Comment by robertsLando** [comment]
Without any help, nope

**Comment by robertsLando** [comment]
@YoDaMa here some more details: https://github.com/moscajs/aedes/issues/194  all steps are described here: https://github.com/moscajs/aedes/issues/194#issuecomment-585120746

**Comment by YoDaMa** [comment]
thanks for the link. I'll move discussion there.

**Comment by robertsLando** [comment]
@YoDaMa Let me know if you need help for somewthing
