### ISSUE TITLE
[question] How to disconnect an existed client connect (not in its`own event or authrize/authen...)?

### ISSUE THREAD

**Issue by waytoviva** [moscajs/aedes#662]
The Scene：
  User-A: use a its` account(username&pwd) to connect the [aedes]broker successfully as usual ，and then ,he do the same thing  again at a new device. And the broker need terminate his old connection at the device (as descr above).

Problem:  I can`t find the api to disconnect the connnection in another new connnection  ?

**Comment by waytoviva** [comment]
If i close the client`s connection, the client will reconnect again, so broker should send a message to tell the client not to reconnect.But in this aspect[of the authenticate], there is not api to send messages to the client

**Comment by robertsLando** [comment]
You should get the client instance from `aedes.clients` and call client method `close`
