### ISSUE TITLE
[question] Is there a way to list all topics any client is subscribed to?

### ISSUE THREAD

**Issue by tukusejssirs** [moscajs/aedes#668]
I’d like to know I the broker can get a list of all topics at least one client is subscribed to.

I need to compute some stuff before publishing the data, therefore I’d like to eliminate unnecessary computation.

Imagine that we have several topics the clients can subscribe to and each of these topics is appended with `/i` where `i` is an integer `1..n` (e.g. `topic_a/1`, `topic_b/50`). If no client is subscribed to `topic_a/2`, there is no reason to compute the data and publish it.

Thanks in advance! :wink:

**Comment by robertsLando** [comment]
Yes, everything you need is stored in aedes persistence module

**Comment by tukusejssirs** [comment]
Thanks, @robertsLando! My bad I didn’t read the docs in depths. :wink:

A subquestion: on the server side, can I unsubscribe a topic of a specific client? Like `delete aedes.clients.mqttjs_fe43c32a.subscriptions['topic/test']`? Should this work as expected?

**Comment by robertsLando** [comment]
It would be better if you directly call unsubscribe method from client instance: https://github.com/moscajs/aedes/blob/main/lib/client.js#L239

**Comment by tukusejssirs** [comment]
I understand that, @robertsLando, but my use case is one similar to MTConnect: on connect, I need to send current status (all values) and them only the changes in those values.

I think then I could make all clients to subscribe to two topics (e.g. `current` and `changes`). To avoid race conditions, I thought about unsubscribing the client from `current` (on the server/broker) after publishing the data.

Can you think of a better solution?

**Comment by robertsLando** [comment]
> I understand that, @robertsLando, but my use case is one similar to MTConnect: on connect, I need to send current status (all values) and them only the changes in those values.

Usually `retained` flag is used for such purposes. Programmatically unsubscribe clients on broker side isn't a good design choice

**Comment by tukusejssirs** [comment]
I see. Although a retained message is nice when the state (e.g. `current` topic data) is available at any moment. Even though I’d like to use the retained messages, but problem lays in that currently I need to compute the data whenever a new client subscribes to a particular topic. I know, it is not very KISS and DRY, but for now it has to suffice.

I need to do the following whenever a client subscribes to a particular topic (e.g. `current`):
1. generate the `current` data;
2. publish the data _only once_;
3. unsubscribe from the particular topic (or otherwise make sure the data won’t be published to the particular client; next time the same data might need to be published to another client when that client subscribes to the topic).

**Comment by robertsLando** [comment]
Cannot you simply subscribe the client to a topic like `example/current/<cleintid>` and publish the current data there? The client id will be unique on every cleint connection so no need to unsubscribe

**Comment by tukusejssirs** [comment]
Well, it does not looks right for what I want. I don’t say I cannot do it so.

Our use case is monitoring of CNC machines. Each machine is assigned an ID (an integer starting from `1`). Each machine has multiple levels of status data (`light_indicator` (which lights are turned on and off), `alarms`, `production`, …).

I’d like to structure the topics like `machine/{id}/{data_level}`, where the `{data_level}` is optional (subscribing to `machine/{id}` would publish all the data). These topics would be used to send the _changes_ from the broker to all subscribed clients. For initial state, I’d like to use `machine/{id}/current` (or `machine/{id}/{data_level}/current`), but I need to make sure it publishes the current data for each subscribed client only once right after they subscribe to the topic (ideally as the very first data the client receives).

As for why I cannot have current data always stored in the memory: the reason is that is consumes to much resources and that currently we need this only for the front-end website (it consumes the data). As a matter of fact, we currently use Socket.io for the data transfer, but on the server I couldn’t get the list of events to which a client is ‘subscribed’. The list of topics helps me to compute the data only for those machines and/or data levels which are currently used.

Also note that this machine monitoring is used in intranet of a relatively small company, therefore the number of clients should not be high, but I’d like to write this as performant and efficient as possible.

In the end, we like to rewrite the whole monitoring ‘app’ (which I inherited) into a Node.js app, but that requires much more time than rewriting the data transfer.

**Comment by robertsLando** [comment]
> but I need to make sure it publishes the current data for each subscribed client only once right after they subscribe to the topic (ideally as the very first data the client receives).

I know I already told you this but that's really what `retained` messages are used for. I suggest you to find a solution using that

**Comment by tukusejssirs** [comment]
> What you could do is to unsubscribe the client once it receives a message that is not retained so you know you have received all retained ones

Yes, I‘ve just thought about this. But I was not able to receive a message when I tried to send it using `aedes.publish()`.

Here’s what I did. Do miss something? I’d like to eliminate a client running on a server-side, as I believe `aedes.publish()` should be able to publish the message to all subscribed clients.

```js
// Start the server
const aedes = require('aedes')()
const {createServer} = require('aedes-server-factory')
const server = createServer(aedes, {ws: true})

server.listen(8080, () => {
  console.info('[INFO] Server started and listening on port 8080.')
})

// Start the client
let mqtt = require('mqtt')
let client = mqtt.connect('ws://localhost:8080')

// Subscribe to to a topic
client.subscribe('machine/1/light_indicator/current', (err, granted) => {
  if (err) {
    console.error('err :', err)
    console.log('granted :', granted)
    return
  }
})

client.on('machine/1/light_indicator/current', (topic, payload) => {
  console.log(topic, ':', payload)
  client.unsubscribe('machine/1/light_indicator/current')
})

// Publish a message
aedes.publish({
  cmd: 'publish',
  qos: 0,
  topic: 'machine/1/light_indicator/current',
  payload: Buffer.from('{"message": "example message text"}'),
  retain: false
}, (err) => {
  if (err) {
    console.log('err :', err)
    return
  }

  console.log('message should be sent')
})
```

**Comment by robertsLando** [comment]
What is the output?

**Comment by tukusejssirs** [comment]
Perfect! That was the issue. I’ve thought that `message` should be replaced by the topic name. Now it works as expected. Thanks! :pray:

**Comment by tukusejssirs** [comment]
Right, therefore there is a different issue in my code. Sorry to bother you. :wink:
