### ISSUE TITLE
[question] After a reboot, I get many "CONNECTION ERROR Error: connect did not arrive in time"

### ISSUE THREAD

**Issue by sponz** [moscajs/aedes#679]
As you see on the image, after a reboot of the server, I get many "CONNECTION ERROR Error: connect did not arrive in time"

![image](https://user-images.githubusercontent.com/1790564/138638936-71f7b3e0-a74e-4c47-a07a-d02a9e320254.png)

Devices are connected and I am receiving messages and I can actuate over the devices. 

Any idea for these messages? 

Thanks in advance.

**Comment by sponz** [comment]
I am still receiving the error messages. I have set the timeout to 60000 and back to 30000, but no difference. 

It was working fine and suddently it started with the error messages. 

@robertsLando what could be the cause? 

Thanks for your help.

**Comment by robertsLando** [comment]
I would need some more info about how devices are connected and the connect parameters

**Comment by sponz** [comment]
@robertsLando thanks for your quick answer

Broker and devices are in the same network. 

Devices use the following MQTT settings: 

- We use this library: https://github.com/marvinroger/async-mqtt-client
- MQTT 3.1.1
- No SSL
- QoS = 0
- MQTT Keep Alive = 300 seconds 
- Retain = Yes 
- Clean Session = No 

Do you need more information? 

Timeout is set to default 30000

**Comment by robertsLando** [comment]
What makes me think there is an error is: 

> Clean Session = No

Is there a reason why you are not using clean sessions? This could cause some memory leak and also based on my experience users use that by error when they only need retain

**Comment by sponz** [comment]
@robertsLando thanks for your reply. 

It is a recommendation: 

// ref. 3.1.2.4 Clean Session, where we are uniquely identified by the client-id:
// - subscriptions that are no longer useful are still there
//   unsub # will be acked, but we were never subbed to # to begin with ...
// - we *will* receive messages that were sent using qos 1 or 2 while we were offline
//   which is only sort-of good, but MQTT broker v3 will never timeout those messages.
//   this would be the main reason for turning ON the clean session
// - connecting with clean session ON will purge existing session *and* also prevent
//   the broker from caching the messages after the current connection ends.
//   there is no middle-ground, where previous session is removed but the current one is preserved
//   so, turning it ON <-> OFF during runtime is not very useful :/

https://github.com/xoseperez/espurna/blob/21a8c2678f7026bcdb00312e137abf38656238aa/code/espurna/mqtt.cpp#L415

Should we try Clean Session = Yes? 

Is this a device issue or a server issue?

**Comment by robertsLando** [comment]
> Should we try Clean Session = Yes?

It dependson the usage, usually there is no reason to use a NOT clean session except when you really need to receive all messages even when it goes offline (like a client that needs to keep the history of messages for some reason). 


> Is this a device issue or a server issue?

This is not an issue, this is described on MQTT specs, BTW if you are using it in the wrong way it could cause issues for sure
