### ISSUE TITLE
[question]Does aedes support opening 1883 and 8084 at the same time

### ISSUE THREAD

**Issue by weiliudong** [moscajs/aedes#680]
It is not clear whether aedes supports the form of multiple ports for one application, that is, the situation where 1883 (mqtt://) and 8084 (mqtts://) ports are opened at the same time.

**Comment by robertsLando** [comment]
Sure!

**Comment by weiliudong** [comment]
Please send
 Example connection, thank you very much.

**Comment by robertsLando** [comment]
Just create a tls and a tcp server and pass the aedes.handle to both
