### ISSUE TITLE
cluster with 3 servers, not splitting the messages between them

### ISSUE THREAD

**Issue by roysG** [moscajs/aedes#686]
**System Information**
- Aedes: 0.40.1
- NodeJS: 16.0
- OS: Ubuntu 20
- Arch: x86_64

I run the cluster example, i connected to it external mongo db server.

I created 3 server and run the same code,
add each server to load balancer (in digital ocean)

Send publish message as interval of 10 mili seconds.
 
**Expected behavior**
The message should splitting between the server each time it sends as randomly or as round robin method

Instead it send in the same server.
Just if i kill the server it go to other server, and then the problem is happen again, the message is stay in the same server

**Comment by roysG** [comment]
I follow this example:
https://github.com/moscajs/aedes/blob/main/examples/clusters/index.js
But i change the localhost of mongo to my server mongo

**Comment by roysG** [comment]
??

**Comment by robertsLando** [comment]
@roysG IWhen I test that example I see clients connected to different servers all receiving their messages without any problem

**Comment by roysG** [comment]
Customer connect to cluster,
the cluster pick one server,
the current connection send many msgs and the cpu start be high.
The better solution was to split these messages to the servers that has no traffic yet.

**Comment by robertsLando** [comment]
> The better solution was to split these messages to the servers that has no traffic yet

This should be handled by the nodejs cluster module and not by aedes

**Comment by roysG** [comment]
Ok,
So in case i want to publish the messages for other server, how should i do it with the nodejs cluster?

**Comment by roysG** [comment]
This is the only thing i left to understand, in case i will pick this library for using it in production

**Comment by robertsLando** [comment]
If a client connects to a specific instance that instance will be the first one to receive the message but if another client connected to another instance is subscribed to a topic that matches the publish it will receive the packet as it is forwarded between instances using mqemitter
