### ISSUE TITLE
[question] Limit of mqemitter?

### ISSUE THREAD

**Issue by seeLuck** [moscajs/aedes#703]
Just a thought, might be wrong.
Since each message of every broker will emit to mqemitter-redis, which will hold all message of the whole cluster, mqemitter-redis‘s QPS grow exponentially through the expansion of cluster, and reach the limit every soon.
Could this to be a trouble? If is, how to solve it? Thx

**Comment by robertsLando** [comment]
@seeLuck using redis clusters
