### ISSUE TITLE
[question] How does lib/write.js works?

### ISSUE THREAD

**Issue by YoDaMa** [moscajs/aedes#709]
On this line: https://github.com/moscajs/aedes/blob/main/lib/write.js#L10

Should it be checking if result is false? Because wouldn't result be false if writeToStream errored?

**Comment by YoDaMa** [comment]
This is confusing because the type of writeToStream has it returning void, which could just be a type issue: https://github.com/mqttjs/mqtt-packet/blob/23774e79e0ca83a718b95d254414964e7a421b1f/types/index.d.ts#L251

**Comment by robertsLando** [comment]
I think it's a type error on mqtt-packet types. `writeToStream` calls this function: https://github.com/mqttjs/mqtt-packet/blob/23774e79e0ca83a718b95d254414964e7a421b1f/writeToStream.js#L16

And that returns a boolean

**Comment by YoDaMa** [comment]
Ok. So on an error scenario we can catch the errors with `conn.on('error', this.emit.bind(this, 'error'))`, which calls the `onError` function. 

```js
function onError (err) {
  if (!err) return

  this.errored = true
  this.conn.removeAllListeners('error')
  this.conn.on('error', noop)
  // hack to clean up the write callbacks in case of error
  const state = this.conn._writableState
  const list = typeof state.getBuffer === 'function' ? state.getBuffer() : state.buffer
  list.forEach(drainRequest)
  this.broker.emit(this.id ? 'clientError' : 'connectionError', this, err)
  this.close()
}
```

How is it assumed that the `write` will complete successfully on a `Connect` though? it seems dependent on the `drain` event, which only fires if the buffer reaches the high water mark, correct? Couldn't the `Connect` packet from `mqtt-packet` not hit the high water mark?

```js
function write (client, packet, done) {
  let error = null
  if (client.connecting || client.connected) {
    try {
      const result = mqtt.writeToStream(packet, client.conn)
      if (!result && !client.errored) {
        client.conn.once('drain', done) // done is only called when the high water mark is hit and then the stream clears the buffer enough to start receiving data again...
        return
      }
    } catch (e) {
      error = new Error('packet received not valid')
    }
  } else {
    error = new Error('connection closed')
  }

  setImmediate(done, error, client)
}
```

In practice maybe this isn't an issue. Maybe it just needs to be documented or noted that the high water mark will always be hit while sending a packet. Or maybe the NodeJS documentation around the `drain` event isn't clear, and it will fire any time the buffer is cleared entirely. And because the ordering of calls, it is only until the _next_ event loop that the `drain` event would be emitted, so it is guaranteed to be called.

**Comment by YoDaMa** [comment]
A small example using `drain` seems to show that if you write under the highwatermark, then `drain` will not be triggered: 

```js
import { createWriteStream } from 'node:fs';

const writableStream = createWriteStream('stream_example.txt');
stream.on('drain', () => console.log('drain'));
writableStream.write('Hello');
// Because the high water mark never was reached, the drain event will never be emitted.
```

so maybe the assumption in the code is that the packet is always going to hit the highwatermark then? I'd just like clarity on the assumptions being made when we're calling `client.conn.once(`drain`, done)`

**Comment by YoDaMa** [comment]
From my best understanding of the `write.js` code:

If `result` is false and `client.errored` is true, then what that's saying is we don't know about `highwatermark` but there was an error on `writeToStream` in `mqtt-packet`. 

If `result` is true and `client.errored` is is true, then we didn't hit the `highwatermark` but an error occurred on `writeToStream` in `mqtt-packet`.

If `result` is false and `client.errored` is false, then we hit the `highwatermark` and there was no error, so we wait for the drain to complete and then have the `done` callback called. 

If `result` is true and `client.errored` is false, then we did not hit `highwatermark` and there was no error on `writeToStream`, so the line `client.conn.once('drain', done)` will not be executed, and instead `setImmedaite(done, error, client)` will be called where `error` is `null`.

Is this all an accurate reading of the actual behaviour?

**Comment by robertsLando** [comment]
What you said in your previous comment is correct. The `writeToStream` call returns true when we can keep writing on the stream and false when we need to let stream "breath" (said in other words without mentioning `highWatermark`).

So when the stream let's us write on it (and there are no errors) we immediatly call done using the `setImmediate`, otherwise we need to wait for the `drain` event to be able to write again.
