### ISSUE TITLE
[question]Aedes on React Native with Expo?

### ISSUE THREAD

**Issue by getindepender** [moscajs/aedes#728]
Hi,

Thanks for creating this great package!

I would like to use Aedes as a MQTT broker on a mobile phone (iOS as well as Android) with an Expo React Native managed app.

Is there anyone who has tried to do that before / are there examples? Or maybe just some tips how to get that working?

Kind regards,
steven

**Comment by robertsLando** [comment]
I dunno how react native works but it needs to have nodejs on the low level, Aedes uses nodejs internal packages that are not available on browser env
