### ISSUE TITLE
[question]How to know Puback 

### ISSUE THREAD

**Issue by koshi148** [moscajs/aedes#808]
Thanks for developing such great software.

When communicating with Qos1 in mqttBroker, please tell me how to output in the console that you have received a puback from the client.

**Comment by robertsLando** [comment]
https://github.com/moscajs/aedes/blob/main/docs/Aedes.md#event-ack

**Comment by iosifnicolae2** [comment]
Can we manually send an acknowledgment for each message within the publish handler? We aim to push each message to Kafka with QoS 1, so after successfully pushing the message to Kafka, we need to return an ACK packet to the client.

Thank you!

**Comment by robertsLando** [comment]
Nope, you can't. You should create a support for a custom ack handler

**Comment by iosifnicolae2** [comment]
Could you provide some suggestions on where I can begin implementing this?

 I assume I'll need to locate where `handlePuback` is called and determine a method to process each message synchronously.
https://github.com/moscajs/aedes/blob/c5d5b8e03944737adaea2761c1b571b5f7bb53e4/lib/handlers/puback.js#L3

**Comment by iosifnicolae2** [comment]
@robertsLando will it work like this?
```javascript
  const aedes = new Aedes({
    published: (packet, client, callback) => {
      console.log('published', packet.topic, packet.payload.toString());
      new Promise(resolve => {
        // do your work here
        console.log("sleeping 5 seconds")
        return setTimeout(resolve, 5000);
      })
          .then(() => callback())
          .catch(e => callback(e));
    }
  })
```

Do you see any problems with this implementation?
