### ISSUE TITLE
Thank You!

### ISSUE THREAD

**Issue by Acgua** [moscajs/aedes#818]
Hi,

This just to thank you very much for your great work on this MQTT server implementation!

Background info:
I have written a node.js/TypeScript plugin for the [ioBroker](https://github.com/ioBroker) system (plugin/integration is called "adapter" in ioBroker world), which is an open-source home automation system (like HomeAssistant, OpenHAB, etc.) based on node.js. 
I have integrated [Fully Kiosk Browser](https://www.fully-kiosk.com/en/#mqtt), which is an Android app which is widely used in the community on wall-mounted tablets, and which will always keep the screen on and shows the home automation dashboard / sites in full screen mode, has a power management, etc.
My plugin ("adapter") allows to receive all information and published messages (e.g. motion sensor or screen turned on/off, and many more) from these devices through MQTT events and by using Aedes. 

Aedes works greatly in this environment! Just as an example: a power user ([Link](https://forum.iobroker.net/post/960482) to German forum), who is using 20+ MQTT clients with my plugin in his home, reported no issues at all and working fine.
I am currently rolling it out for beta testing to get much more feedback

Link to the Aedes class I have written, which shows my current implementation of Aedes: https://github.com/Acgua/ioBroker.fully-mqtt/blob/main/src/lib/mqtt-server.ts

This just as an FYI and to let you know my appreciation for your great work.

**Comment by robertsLando** [comment]
Hi @Acgua! Glad you like this module and thanks for your feedback 🙏🏼
