### ISSUE TITLE
Exploring migrating from Mosca (w/MongoDB) to Aedes (also w/MongoDB).  Can Aedes use the existing MongoDB data, or does it differ, requiring me to start clean? 

### ISSUE THREAD

**Issue by tjf** [moscajs/aedes#850]
Is there a recommended migration path for existing data?

Also, is there anything documenting the difference between 'emitter' and 'persistence'?  I'm trying to discern the role of each, in this context.

Thank you! :-)

**Comment by robertsLando** [comment]
You need to start clean

**Comment by tjf** [comment]
Gotcha, thanks!
