### ISSUE TITLE
[question] How to get client ip address in Websocket mode

### ISSUE THREAD

**Issue by vttkrk** [moscajs/aedes#886]
I created a aedes server with the code below
```
const aedes = require("aedes")();
const { createServer } = require("aedes-server-factory");
const port = 8000;
const httpServer = createServer(aedes, { ws: true, trustProxy: false });
httpServer.listen(port, function () { console.log("Server started"} );
```

In preConnect handler

```
aedes.preConnect = (client, packet, callback) => {
  console.log(
    "client remoteAddress " + client.connDetails.ipAddress
  );
  callback(null, true);
};
```

I wonder is 'client.connDetails.ipAddress' the right way to get the client address. 
In [simple MQTT example ](https://github.com/moscajs/aedes/blob/HEAD/docs/Examples.md#simple-plain-mqtt-server) I can get the client remote address with '_client.conn.remoteAddress_' but it isn't work in websocket mode. I try to **console.log(client)** and found out that **client.connDetails.ipAddress** holds value "**::1**"
I think because the server is running on my local machine. But I can test if it work in production environment. 

Please suggest some correct way to get the client IP address.
Thanks!

**Comment by robertsLando** [comment]
> I wonder is 'client.connDetails.ipAddress' the right way to get the client address.

It depends on if the client connects using websockets or tcp socket, anyway everything parsed is placed in `connDetails` as you can see in source: https://github.com/moscajs/aedes-server-factory/blob/main/index.js#L82C9-L82C20
