### ISSUE TITLE
mqtt服务启动后无法打印内容

### ISSUE THREAD

**Issue by Torstentjh** [moscajs/aedes#916]
刚接触这些，不清楚怎么解决，我使用了这个库启动了mqtt服务，但是用mqttfx作为客户端连接时，aedes.on('client',.....),在监听的函数中打印了client.id，但是无法获取到client，这是代码

const aedes = require('aedes')();
const server = require('net').createServer(aedes.handle);

aedes.on('client', (client) => {
    console.log('Client connected:', client.id);
});
aedes.on('clientDisconnect', (client) => {
    console.log('Client disconnected:', client.id);
});

server.listen(1883, () => {
    console.log(`MQTT server listening on port 1883`);
});

**Comment by robertsLando** [comment]
English please

**Comment by gnought** [comment]
the code runs as it expects. @Torstentjh 
```
console.log('Client connected:', client.id);
```
