### ISSUE TITLE
[bug] Aedes is undefined in Typescript

### ISSUE THREAD

**Issue by benbai123** [moscajs/aedes#927]
**System Information**
- Aedes: 0.50.1
- NodeJS: 16.13.1
- Typescript: 5.3.3
- OS: Mac (M1)

**Describe the bug**
Run [official example](https://github.com/moscajs/aedes/blob/main/docs/Examples.md#typescript), Aedes is undefined and got error `TypeError: aedes_1.default is not a constructor`

**To Reproduce**

create 3 files below and run shell `npm install && npm run start`

* `package.json`

```
{
  "scripts": {
    "start": "npx tsc --p ./tsconfig.json && node dist/main.js"
  },
  "devDependencies": {
    "typescript": "^5.3.3"
  },
  "dependencies": {
    "@types/node": "^20.10.7",
    "aedes": "^0.50.1"
  }
}
```

* `tsconfig.json`

```
{
  "compilerOptions": {
    "rootDir": "src",
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "skipLibCheck": true,
    "strictNullChecks": false,
    "noImplicitAny": false,
    "strictBindCallApply": false,
    "forceConsistentCasingInFileNames": false,
    "noFallthroughCasesInSwitch": false
  },
  "include": ["src/"],
}

```

* `/src/main.ts`

```
import Aedes from 'aedes'
import { createServer } from 'net'

const port = 1883

const aedes = new Aedes()
const server = createServer(aedes.handle)

server.listen(port, function () {
  console.log('server started and listening on port ', port)
})
```

**Expected behavior**
Should start a broker

**Additional context**

* The compiled file `main.js`

```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const aedes_1 = require("aedes");
const net_1 = require("net");
const port = 1883;
const aedes = new aedes_1.default();
const server = (0, net_1.createServer)(aedes.handle);
server.listen(port, function () {
    console.log('server started and listening on port ', port);
});
//# sourceMappingURL=main.js.map
```

**Comment by robertsLando** [comment]
Does it works with 0.50.0? May be a regression introduced by #918 . @hjdhjd ?

**Comment by benbai123** [comment]
nope, tried 0.49.0 and 0.50.0, same error

**Comment by robertsLando** [comment]
Could you submit a PR to fix the issue?

**Comment by hjdhjd** [comment]
I don't think there is a PR needed here - the issue is with the compilation options the user is using, not the code itself.

tsconfig.json:

```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "declaration": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "lib": [
      "DOM",
      "ES2022"
    ],
    "module": "ES2022",
    "moduleResolution":"node",
    "outDir": "dist",
    "rootDir": "src",
    "sourceMap": true,
    "strict": true,
    "target": "ES2022"
  },
  "include": [
    "src"
  ]
}
```

Ensure package.json has ``"type": "module"`` in there as well.

@robertsLando I can confirm that everything is working as it should be with the existing release.

**Comment by benbai123** [comment]
confirmed, need `"type": "module"` and 2 key compiler options.

* 2 key compiler options 

```
{
  // ...
  "module": "ES2022",
  "moduleResolution":"node",
}
```

btw, the compiler options I used before are copied from NestJS

**Comment by benbai123** [comment]
tried run Aedes with NestJS, failed as expected.

**Comment by robertsLando** [comment]
> Ensure package.json has "type": "module" in there as well.

@hjdhjd So it only works with ESM now? Does it always require type module??
