### ISSUE TITLE
[question] Any way to add data to connect packet and authorize handler?

### ISSUE THREAD

**Issue by zg009** [moscajs/aedes#945]
Hello, is there a way for the auth handler to get extra information that would be sent besides username and password? It is not a big deal to do it myself, but would like pointers on where to start

**Comment by robertsLando** [comment]
> Hello, is there a way for the auth handler to get extra information that would be sent besides username and password?

You can fetch some informations in preConnect handler and then store them on client object so you can access them later on authorize. See example here: https://github.com/moscajs/aedes-protocol-decoder

**Comment by zg009** [comment]
@robertsLando Thank you!
