### ISSUE TITLE
[bug] Number of TCP Connections accepted on container is less than the one deployed in EC2 machine

### ISSUE THREAD

**Issue by zagadheesh** [moscajs/aedes#949]
**System Information**
- Aedes: 0.51.0
- NodeJS: 20.11.0
- OS: Amazon linux
- Arch: x86_64
- Mongo: Atlas M40

**Describe the bug**
We deployed aedes in AWS ECS where the conatiner is running in M5.2xlarge machine. Broker has been configured with TCP 1883 port. CPU and memory have been allocated so that the container can use more than 80% resources of machine. With the java simulator client we tried to open subscribers where each subscriber connects to different topic. But, in this case broker giving continous disconnections after accepting upto 10,000 connections. AEDES deployed in M5.2xlarge machine directly instead of container is accepting upto 1.5 Lakhs connections. In both cases we are trying to open connections in the chunks of 5000. On Every increment of 5k the CPU is spiking upto 99% and coming back to normal. Mongo has been used as a persistence and emitter.No errors are observed in both cases. We are unable to identify why the container is accepting very less number of connections compared to the one that is directly running in EC2.

**To Reproduce**
1. Deploy AEDES as a continer (dockerfile attched)
2. Run a simulator that simulates number of subscribers where each subscriber connects to different topic
3. Deploy AEDES in EC2
4. Run a simulator that simulates number of subscribers where each subscriber connects to different topic

**Expected behavior**
As explained, in bothe cases the number of connections accepted by broker should be same.

[aedes_dockerfile.txt](https://github.com/moscajs/aedes/files/15039789/aedes_dockerfile.txt)

[aedes.zip](https://github.com/moscajs/aedes/files/15039859/aedes.zip)

**Comment by zagadheesh** [comment]
Hi @Gianluca-Casagrande-Stiga , Thanks for your reply. Its only one instance of broker(child processess = number of cores) in either case. Mongo is in separate environment.

**Comment by mcollina** [comment]
Usually container environments are not tuned to let a massive number of connections to the vms. Some tuning is required.

**Comment by zagadheesh** [comment]
@mcollina is the tuning required in aedes configuration or container environment?

**Comment by robertsLando** [comment]
@zagadheesh container

**Comment by mcollina** [comment]
the container hosts generically

**Comment by zagadheesh** [comment]
@robertsLando  @mcollina Thanks for confirming.
