### ISSUE TITLE
[bug] Aedes is creating a subscription with the clientId set to 'test' and a global topic of '#'.

### ISSUE THREAD

**Issue by zagadheesh** [moscajs/aedes#974]
**System Information**
- Aedes: 0.52.0
- NodeJS: 16.15.0

**Describe the bug**
Aedes is creating a subscription with a global topic '#' and a clientId of 'test'. As a result, any publish operations to Aedes are being broadcast to the 'test' client.

**To Reproduce**
1. Start aedes
2. Observe the subscriptions being created

**Expected behavior**
Aedes shouldn't create subscription with global topic.

**Comment by robertsLando** [comment]
Code?

**Comment by zagadheesh** [comment]
Hi @robertsLando , I have noticed that the broker has created the following subscriptions, even though there were no subscriptions for almost an entire day. I'm curious as to how these subscriptions were generated.

{"_id":{"$oid":"66fcbbfe30163238e3864fa9"},"clientId":"test","topic":"$SYS/#","added":{"$date":{"$numberLong":"1727944974783"}},"qos":{"$numberInt":"0"}}

{"_id":{"$oid":"66fcbbfe30163238e3864fb3"},"clientId":"test","topic":"#","added":{"$date":{"$numberLong":"1727944974784"}},"qos":{"$numberInt":"0"}}

{"_id":{"$oid":"66fe29a530163238e3b3ba3e"},"clientId":"nmapdhyssbcapazmexnk","topic":"$SYS/#","added":{"$date":{"$numberLong":"1727932837395"}},"qos":{"$numberInt":"0"}}

{"_id":{"$oid":"66fe29a530163238e3b3ba42"},"clientId":"nmapdhyssbcapazmexnk","topic":"#","added":{"$date":{"$numberLong":"1727932837395"}},"qos":{"$numberInt":"0"}}

**Comment by robertsLando** [comment]
Try to put some logs on your code to see when aedes starts if you get a connected event from this clients, I'm pretty sure you have a program running on your pc that connects to your aedes instance... Try to reproduce this in a gh codespace for example, you will not see those entries
